"use client";

import { motion, AnimatePresence } from 'framer-motion';
import { X, Plus, FileText } from 'lucide-react';

interface ResultPanelProps {
  open: boolean;
  onClose: () => void;
  result: {
    title: string;
    narrative: string;
    sourceConnectors: string[];
    missingConnectors: { id: string; name: string; reason: string }[];
    llmModel: string;
    llmTokensUsed: number;
    guardianCategoriesDetected: string[];
  } | null;
}

export function ResultPanel({ open, onClose, result }: ResultPanelProps) {
  return (
    <AnimatePresence>
      {open && result && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40"
            onClick={onClose}
          />
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 30, stiffness: 250 }}
            className="fixed right-0 top-0 h-full w-full md:w-[640px] bg-card border-l border-border z-50 overflow-y-auto"
          >
            <div className="sticky top-0 bg-card border-b border-border p-4 flex items-center gap-3 z-10">
              <div className="w-10 h-10 rounded-lg bg-amber-500/20 border border-amber-500/40 flex items-center justify-center">
                <FileText className="w-5 h-5 text-amber-500" />
              </div>
              <div className="flex-1">
                <div className="text-[9px] font-bold text-amber-500 uppercase tracking-wider">Generated Report</div>
                <h2 className="text-base font-bold text-foreground truncate">{result.title}</h2>
              </div>
              <button
                onClick={onClose}
                className="p-1.5 rounded-lg hover:bg-muted/50"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="p-6 space-y-4">
              <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/30">
                <div className="text-[9px] font-bold text-emerald-500 uppercase tracking-wider mb-1">
                  Based on {result.sourceConnectors.length} connector{result.sourceConnectors.length !== 1 ? 's' : ''}
                </div>
                <div className="text-[11px] text-foreground">{result.sourceConnectors.join(' · ')}</div>
                <div className="text-[10px] text-muted-foreground mt-1.5">
                  Generated by <span className="font-mono text-purple-400">{result.llmModel}</span>
                  {' · '}
                  {result.llmTokensUsed} tokens
                  {' · Guardian processed: '}
                  {result.guardianCategoriesDetected.length === 0 ? 'nothing' : result.guardianCategoriesDetected.join(', ')}
                </div>
              </div>

              <div className="whitespace-pre-wrap text-sm text-foreground leading-relaxed">
                {result.narrative}
              </div>

              {result.missingConnectors.length > 0 && (
                <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/30">
                  <div className="flex items-center gap-1.5 mb-2">
                    <Plus className="w-3 h-3 text-amber-500" />
                    <div className="text-[10px] font-bold text-amber-500 uppercase tracking-wider">
                      Add more connectors for a richer report
                    </div>
                  </div>
                  <ul className="space-y-1">
                    {result.missingConnectors.map((m) => (
                      <li key={m.id} className="text-[11px] text-muted-foreground">
                        • <strong className="text-foreground">{m.name}</strong> — {m.reason}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
