export const missions = [
 {id:0,name:'The river of life',place:'Nile riverbank',type:'irrigation',pos:[5,38],icon:'water',subject:'History · geographical context',title:'Wake the riverside garden',intro:'For ancient Egyptian farmers, the Nile brought water and rich silt. Its yearly floods helped make the land beside the river fertile. Channels could carry water to fields. Now help the farmer: use the three numbered gate buttons in this puzzle to let the water through.',task:'Choose Guide me there. At the garden, the same button will say Open the gate puzzle.',objective:'Explain how the Nile supported farming.',learn:'Silt is fine soil carried by water. Fertile soil can support growing crops.',reward:'River keeper',fact:'The Nile was a source of water, fertile soil and a route for travel. Most ancient Egyptian settlements were close to it.'},
 {id:1,name:'Cargo for the village',place:'Harvest landing',type:'cargo',pos:[10,19],icon:'boat',subject:'Maths · daily life',title:'A fair share of the harvest',intro:'Grain was important for food and trade. This mission uses a modern maths model: share 24 grain baskets equally between three boats. Equal means each boat carries the same number.',task:'Load all 24 baskets. Each boat needs an equal share. Use the baskets to show your method, then explain the groups.',objective:'Represent and solve equal sharing: 24 divided by 3.',learn:'Share one basket to each boat, then repeat. The objects, groups and equation describe the same calculation.',reward:'Fair-share navigator',fact:'Our basket puzzle practises modern equal-sharing maths. It is not a claim about an ancient Egyptian measurement system.'},
 {id:2,name:'The scribe’s message',place:'House of writing',type:'scribe',pos:[30,19],icon:'scroll',subject:'English · historical enquiry',title:'Read what the river left behind',intro:'Scribes were trained writers. Ancient Egyptians used different writing systems, including hieroglyphs. Written records and objects help historians investigate the past.',task:'Read this original story message and choose the evidence that answers the question.',objective:'Retrieve information and justify an inference using a short text.',learn:'An inference joins what the text says with what you already know. Point to evidence, not just a guess.',reward:'Story seeker',fact:'This message is modern fiction written for the game, not a translation of a real ancient document.'},
 {id:3,name:'A thousand years apart',place:'Pyramid overlook',type:'timeline',pos:[40,-8],icon:'pyramid',subject:'History · chronology',title:'Put the past in its place',intro:'The great pyramids at Giza were royal tombs, built around 2500 BC. Tutankhamun was a pharaoh, an Egyptian ruler. He lived much later, around 1330 BC. His tomb was in the Valley of the Kings, not inside a pyramid. The discovery came in AD 1922.',task:'Arrange the three chapters from oldest to most recent. BC dates count down towards AD.',objective:'Sequence pyramid building, Tutankhamun and the 1922 discovery.',learn:'Ancient Egypt lasted thousands of years. Things called ancient Egyptian did not all happen at the same time.',reward:'Time traveller',fact:'The pyramids at Giza and Tutankhamun’s tomb are at different places and belong to different periods. This game’s landscape is a compressed story map.'},
 {id:4,name:'Light in the chamber',place:'House of remembrance',type:'shadow',pos:[57,-25],icon:'sun',subject:'Science · beliefs and evidence',title:'Reveal the hidden mark',intro:'Many ancient Egyptians believed in an afterlife. Tomb objects and the preservation of bodies tell us about those beliefs. In this fictional puzzle chamber, an opaque panel blocks light and makes a shadow.',task:'Predict, then move the panel. Match its shadow to the outline and explain the pattern you observed.',objective:'Investigate how the distance from a light changes a shadow’s size.',learn:'Opaque means light cannot pass through. Moving an opaque object nearer a light source can make its shadow larger.',reward:'Light explorer',fact:'Mummification preserved bodies and was connected to beliefs about an afterlife. Our light-lock is an invented puzzle, not an ancient technology.'},
 {id:5,name:'The careful discovery',place:'Valley dig camp · 1922',type:'dig',pos:[43,-47],icon:'brush',subject:'History · archaeology',title:'Discover. Record. Protect.',intro:'In November 1922, Howard Carter’s team uncovered Tutankhamun’s tomb in the Valley of the Kings. Egyptian workers were essential to the excavation. Recording where objects lay helps us understand them.',task:'Gently brush the sand from a replica. Record its position before choosing what the evidence can tell us.',objective:'Explain why archaeologists record evidence and recognise the excavation team.',learn:'An artefact is an object made or used by people. Archaeology studies physical traces of the past; careful records preserve their context.',reward:'Evidence guardian',fact:'This replica is an original game prop. It is not a scanned object from the tomb. The reward is for careful investigation, not taking treasure.'},
 {id:6,name:'Stories worth keeping',place:'Expedition museum',type:'museum',pos:[23,-53],icon:'museum',subject:'History · English · recall',title:'Build the final exhibition',intro:'An exhibition tells a story supported by evidence. Bring together what you discovered about the river, chronology, people and archaeological work.',task:'Choose accurate labels for your exhibition. Explain one choice before finishing your expedition.',objective:'Recall taught ideas and distinguish supported claims from fiction.',learn:'A successful exhibition makes clear what is evidence, what is an interpretation and what was invented for the game.',reward:'Keeper of the Nile',fact:'Your journal records practice in this game. Completing the expedition is not proof of mastery; revisit later and try a new task with an adult.'}
];
export const sources = [
 ['England KS2 history programme','https://www.gov.uk/government/publications/national-curriculum-in-england-history-programmes-of-study/national-curriculum-in-england-history-programmes-of-study'],
 ['British Museum · Ancient Egypt teaching resources','https://www.britishmuseum.org/learn/schools/ages-7-11/ancient-egypt'],
 ['Ashmolean · Ancient Egypt learning resources','https://www.ashmolean.org/learning-resource-ancient-egypt'],
 ['British Museum · Tutankhamun, ancient and modern perspectives','https://www.britishmuseum.org/visit/object-trails/tutankhamun-ancient-and-modern-perspectives'],
 ['Griffith Institute · The Egyptian workforce','https://tutankhamun.griffith.ox.ac.uk/stories/egyptian-workforce'],
 ['Griffith Institute · Howard Carter','https://tutankhamun.griffith.ox.ac.uk/people/howard-carter'],
 ['England primary mathematics programme','https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study'],
 ['England primary English programme','https://www.gov.uk/government/publications/national-curriculum-in-england-english-programmes-of-study/national-curriculum-in-england-english-programmes-of-study'],
 ['England primary science programme','https://www.gov.uk/government/publications/national-curriculum-in-england-science-programmes-of-study/national-curriculum-in-england-science-programmes-of-study'],
 ['EEF · Improving Primary Science','https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/primary-science-ks1-ks2']
];
