import {ASSET_BASE} from './asset-paths.js';
import './example-record.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/fraunces/latin-500.css';
const requested=new URLSearchParams(location.search).get('game');
const game=['nile','plot','fire'].includes(requested)?requested:'nile';
const titles={nile:'Nile Quest',plot:'The Gunpowder Plot',fire:'The Great Fire of London'};
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.title=`Alex’s example record · ${titles[game]}`;
document.querySelector('#app').innerHTML=`<main class="example-record"><a href="./index.html">✦ schoolgle WORLDS · All adventures</a><p class="example-kicker">FICTIONAL PUPIL · SAVED TEST PLAYTHROUGH</p><h1>What would a teacher see?</h1><p class="example-intro">Alex’s ${titles[game]} casebook</p><p>This example was captured by playing the actual activities with an automated test pupil. It includes deliberate mistakes and help. It is not a real child’s record, a learning study or a connected school account.</p><nav aria-label="Example games">${Object.entries(titles).map(([key,title])=>`<a href="?game=${key}&view=example" aria-current="${game===key?'page':'false'}">${title}</a>`).join('')}</nav><div id="example-body" role="status">Opening Alex’s recorded responses…</div><footer><a href="?game=${game}&demo=1">Play as Alex yourself →</a><a href="?game=${game}">Open the game and teacher guide →</a><p>Your own saves are unchanged by opening this example. Playing as Alex uses a separate demonstration save.</p></footer></main>`;
try{
 const response=await fetch(`${ASSET_BASE}examples/${game}-alex.json`);if(!response.ok)throw new Error('Example could not load');const data=await response.json();
 if(data.learner?.fictional!==true)throw new Error('Expected a fictional example');
 const events=game==='nile'?[...(data.evidence||[]).map(e=>({kind:'response',question:e.objective,response:e.details?.response||'See the model below',correct:e.correct,help:[e.support],at:e.at,model:e.details?.values,equation:e.details?.equation})),...Object.values(data.recall||{}).flat().map(e=>({kind:'recall',question:e.details?.question||'Return question',response:e.details?.response,correct:e.correct,help:[e.support],at:e.at,equation:e.details?.equation}))]:(data.attempts||[]).map(e=>({...e,question:e.question||e.response?.prompt||e.objective||e.action,response:typeof e.response==='string'?e.response:e.response?.response||(e.response?.person?e.response.person+' — '+e.response.role:Object.values(e.response||{}).join(' · ')),kind:e.action?.startsWith('return-recall')?'recall':e.kind}));
 const assessed=events.filter(e=>e.kind!=='observation');const corrections=assessed.filter(e=>e.correct===false);
 document.querySelector('#example-body').innerHTML=`<section class="example-stats"><article><b>${data.completed.length}/${game==='nile'?7:5}</b><span>core discoveries completed</span></article><article><b>${assessed.length}</b><span>recorded answer attempts</span></article><article><b>${corrections.length}</b><span>answers needing correction</span></article></section><p><strong>What this lets a teacher do:</strong> identify the particular idea needing discussion, see whether an answer followed a model or feedback, and choose a new classroom task to check understanding. Attempts are not comparable attainment scores.</p><div class="example-actions"><label>Show <select id="example-filter"><option value="all">All recorded actions</option><option value="corrections">Answers needing correction</option><option value="recall">Recall and return checks</option></select></label><a href="${ASSET_BASE}examples/${game}-alex.json" download="${game}-alex-example.json">Download this example (JSON)</a></div><div id="example-events"></div><p class="example-limit">This record captures button selections and submitted models or calculations. It cannot tell us an unspoken reasoning process. Correct game responses need follow-up with a new task and, where useful, a later check.</p>`;
 function draw(){const filter=document.querySelector('#example-filter').value;const visible=events.filter(e=>filter==='corrections'?e.correct===false:filter==='recall'?e.kind==='recall'||e.question==='return-recall':true);document.querySelector('#example-events').innerHTML=visible.map(e=>`<article class="example-event"><span class="example-result">${e.kind==='observation'?'Unassessed action':e.correct?'Matched task criterion':'Correction needed'}</span><h2>${safe(e.question)}</h2><p><strong>Submitted:</strong> ${safe(e.response)}</p>${e.model?`<p><strong>Model:</strong> ${safe(JSON.stringify(e.model))}</p>`:''}${e.equation?`<p><strong>Calculation:</strong> ${safe(e.equation)}</p>`:''}<p><strong>Help / context:</strong> ${safe(e.help?.join('; ')||'No additional help recorded')}</p><small>${safe(e.at)}</small></article>`).join('')||'<p>No matching actions in this example.</p>';}
 document.querySelector('#example-filter').onchange=draw;draw();
}catch{document.querySelector('#example-body').innerHTML='<p>This example could not load. Return to the game and choose Grown-ups to inspect a live practice record.</p>';}
