import * as THREE from 'three';
import {createPlotCostumeRig} from './plot-costume-rig.js';
// Original, stylised time-travel clothes: period-inspired, not replicas of an
// individual museum garment. Both choices are available to either explorer.
export const COSTUME_OPTIONS = [
 {id:'doublet',name:'Doublet and breeches',description:'A fitted blue doublet, full breeches and a warm cloak for our 1605 story.',pieces:['Doublet','Breeches','Linen collar','Stockings','Cloth cap','Cloak']},
 {id:'petticoat',name:'Bodice and petticoat',description:'A green bodice, a long pleated petticoat and a cloak, with a linen cap.',pieces:['Bodice','Petticoat','Linen neckline','Linen coif','Stockings','Cloak']}
];
export const CLOTHING_FACTS = [
 {id:'doublet',text:'A doublet was a fitted upper garment. A portrait from 1600–1610 shows one worn with full hose.',source:'National Trust · Piers Legh X, 1600–1610',url:'https://www.nationaltrustcollections.org.uk/object/499938'},
 {id:'coif',text:'A coif is a close-fitting cap. Plain linen coifs and richly embroidered ones were worn by different people.',source:'The Met · British coif, 1600–1630',url:'https://www.metmuseum.org/art/collection/search/228951'},
 {id:'evidence',text:'Clothes and portraits give us clues. Our explorer outfits are simplified designs inspired by the period, not exact copies.',source:'The Met · British waistcoat, 1615–20',url:'https://www.metmuseum.org/art/collection/search/81132'},
 {id:'layers',text:'Look for separate layers: the upper garment, the breeches or petticoat, and the cloak. Our colours and trims are game designs.',source:'V&A · Shakespeare’s magic: doublet, 1615–20',url:'https://www.vam.ac.uk/articles/vampa-trail-shakespeares-magic'}
];


export function createCostumePreview(container,{character='explorer',outfit='doublet',skinTone='warm',reducedMotion=false}={}){
 if(!container||typeof container.append!=='function')throw new TypeError('A costume preview container is required.');
 let settings={character,outfit,skinTone},quiet=!!reducedMotion,disposed=false,frame=0,last=0,angle=-.22,drag=null,transition=null,dirty=true,visible=true;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.05,25),events=new AbortController();
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const canvas=renderer.domElement;canvas.style.cssText='display:block;width:100%;height:100%;touch-action:pan-y;';canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-description','A 3D outfit preview. Drag sideways or use the left and right arrow keys to turn.');container.append(canvas);
 scene.add(new THREE.HemisphereLight(0xddeefa,0x775347,2.3));const key=new THREE.DirectionalLight(0xffe6bd,3.1);key.position.set(-3,5,4);key.castShadow=true;key.shadow.mapSize.set(512,512);Object.assign(key.shadow.camera,{left:-2,right:2,top:3,bottom:-1,near:.1,far:12});key.shadow.normalBias=.025;scene.add(key);const rim=new THREE.DirectionalLight(0xaccfe6,2.1);rim.position.set(3,3,-3);scene.add(rim);
 const turntable=new THREE.Group();scene.add(turntable);const rig=createPlotCostumeRig({...settings,height:2.4});turntable.add(rig.root);
 const platform=new THREE.Mesh(new THREE.CylinderGeometry(.72,.77,.09,32),new THREE.MeshStandardMaterial({color:0x6b5142,roughness:.9}));platform.position.y=-.05;platform.receiveShadow=true;scene.add(platform);
 function label(){const state=rig.getState();Object.assign(canvas.dataset,{character:state.character,outfit:state.outfit,skinTone:state.skinTone,reducedMotion:String(quiet)});canvas.setAttribute('aria-label',`${state.character==='explorer-girl'?'Maya':'Leo'} wearing ${state.outfit==='modern'?'the original explorer clothes':COSTUME_OPTIONS.find(o=>o.id===state.outfit).name}. Drag or use arrow keys to turn the 3D preview.`);}
 function apply(){rig.setAppearance(settings);label();dirty=true;}
 function resize(){if(disposed)return;const r=container.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height||280),false);camera.aspect=Math.max(1,r.width)/Math.max(1,r.height||280);const fit=Math.max(3.06,1.75/camera.aspect);camera.position.set(0,1.30,fit/(2*Math.tan(THREE.MathUtils.degToRad(16))));camera.lookAt(0,1.23,0);camera.updateProjectionMatrix();dirty=true;}
 const observer=new ResizeObserver(resize);observer.observe(container);const visibility=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting??true;dirty=true;}):null;visibility?.observe(container);
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,angle};canvas.setPointerCapture(e.pointerId);},{signal:events.signal});canvas.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;angle=drag.angle+(e.clientX-drag.x)*.014;dirty=true;},{signal:events.signal});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>{drag=null;},{signal:events.signal});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();angle+=e.key==='ArrowLeft'?-.22:.22;dirty=true;}},{signal:events.signal});
 function tick(now){if(disposed)return;frame=requestAnimationFrame(tick);if(!visible||document.hidden){last=now;return;}const dt=last?Math.min((now-last)/1000,.05):0;last=now;let turn=0;if(transition){const p=Math.min(1,(now-transition.start)/480);if(p>=.5&&!transition.applied){settings.outfit=transition.next;apply();transition.applied=true;}turn=Math.sin(p*Math.PI)*.32;if(p===1){transition=null;delete canvas.dataset.changing;}}turntable.rotation.y=angle+turn;rig.animate(dt,'Idle',quiet);if(dirty||!quiet||transition){renderer.render(scene,camera);dirty=false;}}
 label();resize();frame=requestAnimationFrame(tick);
 return {setCharacter(id){settings.character=id;apply();},setOutfit(id){const next=['modern','doublet','petticoat'].includes(id)?id:'doublet';if(next===(transition?.next||settings.outfit))return;if(quiet){settings.outfit=next;apply();}else{transition={next,start:performance.now(),applied:false};canvas.dataset.changing='true';}},setSkinTone(id){settings.skinTone=id;apply();},setReducedMotion(value){quiet=!!value;if(quiet&&transition){settings.outfit=transition.next;transition=null;delete canvas.dataset.changing;apply();}label();dirty=true;},dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(frame);observer.disconnect();visibility?.disconnect();events.abort();rig.dispose();platform.geometry.dispose();platform.material.dispose();key.shadow.map?.dispose();renderer.dispose();renderer.forceContextLoss();canvas.remove();}};
}
