import './plot-letter.css';

// An original illustrated letter packet, not a facsimile of the Monteagle
// letter or its seal. The learning text remains the existing modern adaptation.
const sealMark=()=>`<svg viewBox="0 0 100 100" aria-hidden="true" focusable="false"><circle cx="50" cy="50" r="37"/><circle cx="50" cy="50" r="31"/><path d="M26 60Q17 47 27 34M74 60Q83 47 73 34M24 51l-7-5m8-2-6-7m8 0-3-8M76 51l7-5m-8-2 6-7m-8 0 3-8"/><path class="seal-monogram" d="M33 64V37l17 18 17-18v27M29 64h10m22 0h10"/></svg>`;
const progress=step=>`<div class="letter-action-trail" aria-label="Letter investigation steps"><span ${step===0?'aria-current="step"':''}><b>${step?'✓':'1'}</b>Open</span><i aria-hidden="true">—</i><span ${step===1?'aria-current="step"':''}><b>2</b>Find the warning</span></div>`;

export function sealedLetter(reducedMotion=false){return `<div class="letter-desk" data-letter-motion="${reducedMotion?'still':'animate'}">${progress(0)}<div class="letter-packet-rest"><button id="plot-seal" class="plot-envelope letter-packet" aria-label="Open the letter seal" aria-describedby="letter-seal-instruction"><span class="letter-paper-edge" aria-hidden="true"></span><span class="letter-fold-top" aria-hidden="true"></span><span class="letter-fold-bottom" aria-hidden="true"></span><span class="envelope-address">To Lord Monteagle</span><span class="wax-seal">${sealMark()}</span><small>Break the seal · Open the letter</small></button></div><p id="letter-seal-instruction" class="letter-desk-instruction"><strong>Tap or click the red wax seal.</strong><br>Keyboard: Tab to the letter, then Enter or Space.</p><span class="letter-desk-caption">An illustrated reconstruction</span></div>`;}

export function openedLetter(reducedMotion=false){return `<div class="letter-reveal" data-letter-motion="${reducedMotion?'still':'animate'}">${progress(1)}<div class="plot-letter letter-open-sheet"><span class="letter-opening-flap letter-opening-top" aria-hidden="true"></span><span class="letter-opening-flap letter-opening-bottom" aria-hidden="true"></span><span class="letter-released-seal" aria-hidden="true">${sealMark()}</span><div class="letter-ink"><span class="letter-received">RECEIVED 26 OCTOBER 1605</span><h3>My lord…</h3><div class="letter-source-lines"><button data-line="0">I care about your safety.</button><button data-line="1">Stay away from Parliament on the opening day.</button><button data-line="2">There is danger, though you may not see it.</button></div><small>Short modern-language adaptation, not the original wording.</small></div></div><p class="letter-evidence-instruction"><span aria-hidden="true">↳</span> Choose one line of the letter as your evidence.</p></div>`;}
