import {practiceKey} from './demo-session.js';
export const PLOT_KEY=practiceKey('schoolgle-midnight-letter-v1');
export const PLOT_VERSION='1605.2';
export const objectives=['Identify people and distinguish their roles','Use a historical source to support an inference','Distinguish what evidence shows from what remains unknown','Sequence events and explain cause and consequence','Distinguish commemoration from contemporary evidence and recall learning'];
export function freshPlot(){return {version:1,completed:[],attempts:[],settings:{reducedMotion:false,character:'explorer',largeText:false,outfit:'doublet',skinTone:'warm',costumeReady:false},started:false};}
const observations=new Set(['open-source','inspect-search-clue','listen-rhyme','place-timeline-card','undo-timeline-card','read-aloud','wardrobe-character','wardrobe-outfit','wardrobe-inspect','wardrobe-read-aloud']);
function cleanResponse(value,depth=0){if(depth>2)return null;if(typeof value==='string')return value.slice(0,1000);if(typeof value==='number')return Number.isFinite(value)?value:null;if(typeof value==='boolean'||value===null)return value;if(Array.isArray(value))return value.slice(0,12).map(v=>cleanResponse(v,depth+1));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['__proto__','constructor','prototype'].includes(k)).slice(0,12).map(([k,v])=>[k.slice(0,60),cleanResponse(v,depth+1)]));return null;}
function cleanAttempt(a){if(!Number.isInteger(a?.chapter)||a.chapter<0||a.chapter>4||typeof a.action!=='string'||a.action.length>100||!Number.isFinite(Date.parse(a.at)))return null;const observation=observations.has(a.action);if(!observation&&typeof a.correct!=='boolean')return null;return{at:new Date(a.at).toISOString(),version:typeof a.version==='string'?a.version.slice(0,40):'unversioned',chapter:a.chapter,objective:a.action.startsWith('wardrobe-')?'Explore clothing in early Stuart England (unassessed)':objectives[a.chapter],action:a.action,kind:observation?'observation':'response',response:cleanResponse(a.response),correct:observation?null:a.correct,help:Array.isArray(a.help)?a.help.filter(v=>typeof v==='string').slice(0,20).map(v=>v.slice(0,160)):[]};}
export function readPlotSave(raw){const s=freshPlot();try{const x=JSON.parse(raw);if(x?.version!==1)return s;for(let i=0;i<5;i++){if(Array.isArray(x.completed)&&x.completed.includes(i))s.completed.push(i);else break;}s.started=x.started===true;for(const k of ['reducedMotion','largeText','costumeReady'])if(typeof x.settings?.[k]==='boolean')s.settings[k]=x.settings[k];if(['explorer','explorer-girl'].includes(x.settings?.character))s.settings.character=x.settings.character;if(['doublet','petticoat'].includes(x.settings?.outfit))s.settings.outfit=x.settings.outfit;else s.settings.costumeReady=false;if(['warm','deep','light'].includes(x.settings?.skinTone))s.settings.skinTone=x.settings.skinTone;s.attempts=Array.isArray(x.attempts)?x.attempts.slice(-200).map(cleanAttempt).filter(Boolean):[];}catch{}return s;}
export function canVisit(s,i){return Number.isInteger(i)&&i>=0&&i<5&&i<=s.completed.length;}
export function recordPlot(s,chapter,action,response,correct,help=[]){const a=cleanAttempt({at:new Date().toISOString(),version:PLOT_VERSION,chapter,action,response,correct,help:[...help]});if(!a)return false;s.attempts.push(a);s.attempts=s.attempts.slice(-200);return true;}
export function completePlot(s,i){if(!canVisit(s,i)||s.completed.includes(i))return false;s.completed.push(i);return true;}
