import {sources} from './content.js';
import {demoTeacherPanel} from './demo-session.js';
import {curriculumGuide,researchRationale,schoolAccessGuide} from './teacher-guide.js';
export const safe=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const subjects=[
 ['Mathematics','Build 24 ÷ 3 with baskets, explain equal groups, then try 15 ÷ 3 in the Sphinx challenge.','A new sharing task with physical counters, explained aloud.'],
 ['English','Infer why a field needs water, then select the sentence that supports the inference.','An unfamiliar paragraph and a spoken or written explanation.'],
 ['Science','Predict, change panel distance, compare the shadow and explain the pattern.','Repeat with a real torch, object and fixed screen.'],
 ['History','Explain Nile farming, order three periods, record find context and evaluate museum labels.','Use an unfamiliar object or source and discuss what it can and cannot tell us.']
];
export function teacherHub(state){return `<div class="eyebrow">TEACHER & FAMILY STUDIO • LOCAL PROTOTYPE</div><h2 id="dialog-title">An adventure with learning you can inspect.</h2><p>Children solve problems in an Egyptian story world. All seven core discoveries require their activity steps before the expedition is complete. The Sphinx challenge is an optional extra.</p>${demoTeacherPanel('nile')}<div class="teacher-stats"><article><b>4</b><span>connected subjects</span></article><article><b>7 + 1</b><span>core discoveries + bonus</span></article><article><b>${state.completed.length}/7</b><span>completed in this browser</span></article></div><div class="studio-actions"><button id="teacher-live" class="primary">Open this browser’s learning record</button><button id="teacher-demo" class="secondary">Preview a school dashboard</button><button id="teacher-plan" class="secondary">Plan a guided lesson</button><button id="teacher-share" class="secondary">Sharing & school access</button></div><h3>What is the education mode?</h3><p><strong>Explore and practise</strong> is the child’s untimed adventure. <strong>Teach together</strong> uses the same learning sequence with automatic travel and an adult-led lesson plan. It is suitable for a shared screen; one browser record is not a class assessment.</p><div class="subject-cards">${subjects.map(([name,task,probe])=>`<article><span class="mini-label">${name}</span><h3>${task}</h3><p><strong>Check beyond the game:</strong> ${probe}</p></article>`).join('')}</div><h3>The teaching cycle</h3><ol class="teaching-cycle"><li><strong>Learn & plan</strong><span>Meet a clear goal and a useful representation.</span></li><li><strong>Do & check</strong><span>Manipulate, calculate or select evidence.</span></li><li><strong>Explain & revisit</strong><span>Connect the result to a reason; try a new context later.</span></li></ol><p class="teacher-notice">England lower KS2 is the initial review target. This samples selected objectives; it is not a complete Ancient Egypt unit, UK-wide curriculum map, White Rose product or validated attainment test.</p>${curriculumGuide('nile')}${researchRationale()}<details class="evidence-detail"><summary>Historical framing and further sources</summary><p>EEF guidance informs modelling, feedback and teacher-supported use. EEF has not evaluated or endorsed Nile Quest. Gems record game completion, not mastery. The stylised map combines places and periods; decorative signs are not a translated inscription.</p><ul class="source-list">${sources.map(([name,url])=>`<li><a href="${url}" target="_blank" rel="noreferrer">${name} ↗</a></li>`).join('')}<li><a href="https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/metacognition" target="_blank" rel="noreferrer">EEF metacognition: second edition ↗</a></li></ul></details>`;}

export function attemptCard(e){const d=e.details||{};return `<li class="attempt-card"><div><span class="evidence-result ${e.correct?'correct':'retry'}">${e.correct?'Correct response':'Needs another try'}</span><small>${safe(d.activity==='sphinx-sharing'?'Sphinx bonus · ':'')}${safe(d.phase||'Activity')} · ${safe(new Date(e.at).toLocaleString('en-GB'))}</small></div><strong>${safe(e.objective)}</strong><p><b>Submitted:</b> ${safe(d.response||'Response not captured in this older attempt.')}</p>${d.equation?`<p><b>Calculation:</b> ${safe(d.equation)}</p>`:''}${d.values?`<p><b>Model:</b> [${d.values.map(safe).join(', ')}] ${safe(d.representation||'')}</p>`:''}${['loadActions','unloadActions','shareRounds'].some(k=>Number.isInteger(d[k]))?`<p><b>Model actions:</b> ${[['loadActions','single loads'],['unloadActions','unloads'],['shareRounds','one-to-each rounds']].filter(([k])=>Number.isInteger(d[k])).map(([k,label])=>`${d[k]} ${label}`).join(' · ')}. Actions show tool use, not a confirmed mental strategy.</p>`:''}${d.distanceSetting!==undefined?`<p><b>Panel control:</b> ${d.distanceSetting} (game setting, not a physical measurement)</p>`:''}<p class="small"><b>Support/context:</b> ${safe(e.support)}</p></li>`;}
export function detailedEvidence(state){return `<h3>What was actually submitted?</h3><p class="muted small">An action or selected explanation is an observation, not proof of the child’s mental strategy. Read-aloud is an access choice. A prediction can be revised after testing; inspect the later explanation too. Older attempts may not contain the response itself.</p><details class="evidence-detail"><summary>Inspect responses, models and calculations (${state.evidence.length} attempts)</summary><ol class="attempt-list">${[...state.evidence].reverse().map(attemptCard).join('')||'<li>No submitted responses yet. Play a discovery, then return here.</li>'}</ol></details>${curriculumGuide('nile')}<h3>Useful next teaching steps</h3><div class="next-teaching">${subjects.map(([name,,probe],i)=>{const ids=[[1],[2],[4],[0,3,5,6]][i],e=state.evidence.filter(e=>ids.includes(e.mission)),wrong=e.some(e=>!e.correct);return `<article><strong>${name}</strong><span>${e.length?wrong?'Some answers needed another try. Revisit the specific response above.':'Successful game responses recorded; check transfer independently.':'No evidence in this browser yet.'}</span><p>${probe}</p></article>`;}).join('')}</div><section class="print-together"><h3>Sphinx bonus</h3><p>${state.bonus?.sphinx?'Completed · 15 extra gems earned once.':'Not completed. Available after the harvest boats.'} Completion is separate from the seven core discoveries.</p></section>`;}

export function lessonPlan(){return `<div class="eyebrow">TEACH TOGETHER • SUGGESTED 25–35 MINUTES</div><h2 id="dialog-title">One adventure. A purposeful lesson.</h2><p>Use the world on a shared display, or support individual devices. These are suggested timings, not timers imposed on children.</p><ol class="lesson-plan"><li><b>Before play · 5 minutes</b><p>Locate Egypt and the Nile on a real map. Ask what crops need. Establish prior knowledge. Explain that the adventure combines historical places and periods.</p></li><li><b>Model and practise · 10 minutes</b><p>Complete the garden and harvest boats. Think aloud: “I need equal groups and no baskets left.” Pause so pupils can build the same model with counters.</p></li><li><b>Transfer · 5–10 minutes</b><p>Try the optional Sphinx challenge: 15 ÷ 3. Ask a child to explain the groups before selecting the game explanation. Record their spoken reasoning separately in your normal assessment system.</p></li><li><b>Check and return · 5 minutes</b><p>Give a new problem away from the screen, such as 12 objects shared among three children. Return on another day with different numbers. A same-day retry is not delayed recall.</p></li></ol><p>The remaining discoveries can form a second session on reading, chronology, light and archaeological evidence. One shared-screen record belongs to that session; it cannot establish what each pupil knows.</p><button id="teacher-launch" class="primary">Start Teach together</button><p class="muted small">Turns on automatic travel and keeps current progress. All required activity steps still apply.</p>`;}

// Deliberate fixtures, kept separate from the local player's evidence and export.
export const demoLearners=[
 {name:'Demo explorer A',status:'Discuss the whole total',model:'[4, 4, 4] with 3 left',response:'15 ÷ 3 = 4',support:'Model visible; corrective feedback',next:'Rebuild 15 using counters. Ask what happens to the three left over.'},
 {name:'Demo explorer B',status:'Check transfer',model:'[5, 5, 5]',response:'15 ÷ 3 = 5',support:'Model visible; correct on first submitted calculation',next:'Offer 12 objects and three groups away from the game. Ask for an explanation.'},
 {name:'Demo explorer C',status:'Support then retry',model:'[5, 5, 5]',response:'First 3, then 5',support:'Read-aloud; explanation and retry',next:'Ask whether the answer counts groups or items in one group. Reading support is not a maths deficit.'}
];
export function schoolDemo(selected=0){const d=demoLearners[selected];return `<div class="eyebrow">SCHOOL DASHBOARD PREVIEW • INVENTED DATA</div><h2 id="dialog-title">See the reasoning, then decide what to teach.</h2><p class="teacher-notice">These three examples are invented dashboard fixtures, not responses from Alex’s playable demonstration. Alex’s record is created only by actual game interactions. These three examples are fictional. This is a design preview, not a connected school account. No real pupil records or class totals are shown.</p><div class="demo-dashboard"><nav aria-label="Example learners">${demoLearners.map((p,i)=>`<button class="demo-learner" data-demo="${i}" aria-pressed="${i===selected}"><strong>${p.name}</strong><span>${p.status}</span></button>`).join('')}</nav><article class="demo-detail"><span class="mini-label">MATHS • EQUAL SHARING</span><h3>${d.name}</h3><dl><dt>Observed model</dt><dd>${d.model}</dd><dt>Submitted calculation</dt><dd>${d.response}</dd><dt>Context</dt><dd>${d.support}</dd></dl><h4>Teacher follow-up</h4><p>${d.next}</p><small>No automatic mastery label. The teacher makes the judgement using several sources of evidence.</small></article></div><h3>What a paid school service would add</h3><p>Verified staff access, securely linked pupil records, class/objective views, assessment notes, assignment and reporting. Those account and sharing services are not implemented in this local prototype.</p><button id="teacher-live" class="secondary">View actual browser evidence instead</button>`;}

export function sharingInfo(){const local=typeof location==='undefined'||['localhost','127.0.0.1','[::1]'].includes(location.hostname);return `<div class="eyebrow">SHARING & SCHOOL ACCESS</div><h2 id="dialog-title">From local prototype to a school pilot.</h2><h3>What can I share today?</h3><p>${local?'This is a local preview. A 127.0.0.1 address opens only on the computer serving it. Demonstrate it here or by screen sharing.':'Share this playtest’s web address to open the adventure on another device. Each device keeps its own practice; a shared link does not share a child’s saved responses.'} Download the practice record or print it for a teacher to review; it contains browser activity, not an authenticated pupil record.</p><h3>How schools would access it</h3><ol class="lesson-plan"><li><b>Public review link</b><p>${local?'Use the reviewed Schoolgle website build for a shareable playtest link.':'This hosted playtest opens in the browser. No pupil account is needed; check device and accessibility needs before a class session.'}</p></li><li><b>School joins Schoolgle</b><p>Verify the organisation and staff roles. A school-name search alone must never grant access to pupil evidence.</p></li><li><b>School invites the family</b><p>A scoped invitation goes through the school’s established parent contact. Confirm the authorised pupil link before sharing any record. Transfers, revocation and errors need a managed process.</p></li></ol>${schoolAccessGuide()}<h3>How we would sell it</h3><p><strong>Free pupil adventures; affordable teacher insight.</strong> Demonstrate a learning objective, the child’s actual response, the support used and the next classroom action. A school reporting price around <strong>£300 per year</strong> is a proposed pilot offer to validate, not an available subscription or evidence of demand.</p><p>Start with a small supervised teacher pilot, then test usability and new-task learning outside the game before making attainment claims. Honest positioning: curriculum-informed practice, informed by EEF guidance. No EEF endorsement or proven learning improvement is claimed.</p><button id="teacher-live" class="secondary">Open the record you can share now</button>`;}
