const curriculum = subject => `https://www.gov.uk/government/publications/national-curriculum-in-england-${subject}-programmes-of-study/national-curriculum-in-england-${subject}-programmes-of-study`;
const link = (url, name) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`;

// These are mappings of implemented tasks, not a full scheme or an attainment scale.
export const taskMappings = {
  nile: [
    ['River garden', 'History · KS2 Ancient Egypt context', 'Explain why farming developed beside the Nile.', 'Open a connected water route, then choose why the field belongs here.', 'Selected explanation. Opening a gate alone does not show historical understanding.', 'Ask why a field far from water might be harder to cultivate.', 'history'],
    ['Harvest boats', 'Maths · Year 3 division', 'Represent 24 ÷ 3 as equal sharing.', 'Load three boats, check the whole total and select an explanation.', 'Submitted basket counts, generated equation, model actions and explanation. The equation here is generated from the model, not typed by the child.', 'Give 12 counters and three people. Ask the child to build, say and write the calculation.', 'mathematics'],
    ['Scribe’s message', 'English · Years 3–4 comprehension', 'Support an inference with evidence from a text.', 'Infer what the dry field needs, then select the supporting sentence.', 'Chosen inference and sentence, with support context. Listening-supported comprehension is not a decoding assessment.', 'Use a fresh short paragraph; ask for a spoken or written reason and its evidence.', 'english'],
    ['Pyramid timeline', 'History · KS2 chronology', 'Distinguish the pyramids, Tutankhamun and the 1922 discovery.', 'Order three events from earliest to latest.', 'Submitted event sequence and corrections. Correct order does not establish precise date recall.', 'Place these events on a longer classroom timeline. Explain why Tutankhamun was not buried in a Giza pyramid.', 'history'],
    ['Light chamber', 'Science · Year 3 light', 'Explore how an opaque object’s position affects a shadow.', 'Predict, adjust the panel, match the shadow and select an explanation.', 'Prediction, submitted panel setting and explanation. The setting is a game control, not a measured length.', 'Use a real torch and fixed screen. Move only the object; predict, observe and explain.', 'science'],
    ['Careful discovery', 'History · KS2 enquiry', 'Explain why find context matters.', 'Uncover a replica, identify its grid square and explain the importance of recording.', 'Selected grid square and reason. Brushing completion is an action, not an archaeology qualification.', 'Give a new object and context; ask what we can infer and what remains unknown.', 'history'],
    ['Final exhibition', 'History · KS2 evidence and recall', 'Select supported claims about Egypt and excavation.', 'Choose labels about the Nile, the tomb and the team, then explain context.', 'Every submitted label and final explanation, including retries. This is within-session recall.', 'Revisit on another day without the labels; ask for a new display caption.', 'history'],
    ['Return practice', 'History and maths · new contexts', 'Revisit farming, equal sharing and archaeological context.', 'Answer a new-village question, 18 ÷ 3 and a question about a newly found cup.', 'Selected answers, the 18 ÷ 3 equation, dates and retry support, stored separately from activity attempts.', 'Use the return check on another day, then ask for reasoning without answer choices. Its date does not by itself prove retention.', 'mathematics'],
    ['Optional Sphinx', 'Maths · Year 3 division', 'Apply equal sharing to 15 ÷ 3.', 'Build three shares, enter an answer and select a reason.', 'Basket model, entered calculation and selected explanation are separate evidence. Fifteen bonus gems are awarded once.', 'Change the total and context away from the screen; distinguish number of groups from size of each group.', 'mathematics']
  ],
  plot: [
    ['1 · The people', 'History · KS1 people and events', 'Distinguish the king, the plot leader and the man found with gunpowder.', 'Match James I, Robert Catesby and Guy Fawkes to roles.', 'Each selected person–role pair and corrections; the teaching text is visible.', 'Put the names away. Ask the child to explain two different roles in their own words.', 'history'],
    ['2 · The warning', 'History enquiry · English comprehension', 'Find evidence in an adapted letter and recognise uncertainty.', 'Select the warning line, then a label about the unknown writer.', 'Chosen line and source-limits label. Opening the seal is recorded as unassessed exploration.', 'Show a different short message. Ask what it tells us and what it does not establish.', 'english'],
    ['3 · The search', 'History · KS1 cause and evidence', 'Connect the discovery to the prevention of the attack.', 'Inspect three reconstructed clues, then select why finding them mattered.', 'Clue inspections are unassessed; the selected causal explanation is checked.', 'Ask why finding a danger before an event can change what happens next.', 'history'],
    ['4 · The story', 'History · KS1 sequence and explanation', 'Sequence warning, search and prevented attack; explain a connection.', 'Arrange three dated events and finish a “because” explanation.', 'Submitted sequence, edits and chosen cause. Moving a card is an observation; the completed sequence is assessed.', 'Retell with first, next and because, using blank cards rather than the game’s wording.', 'history'],
    ['5 · Remember, remember', 'History · KS1 commemoration and sources', 'Distinguish remembrance from an eyewitness report.', 'Classify the rhyme, recall the warning and select an accurate final caption.', 'Rhyme classification, warning response and final explanation. Hearing the rhyme is an access action.', 'Compare a present-day remembrance image with a contemporary source. Explain how their purposes differ.', 'history'],
    ['Optional return check', 'History · revisiting taught ideas', 'Revisit roles, the warning and the limits of a remembrance rhyme.', 'Answer three separate questions after completing all five discoveries.', 'Every submitted answer, question, timestamp, elapsed time where available and feedback on retries. No extra gems or mastery score.', 'Return on another day; add an unfamiliar source and an oral explanation. Same-day practice cannot demonstrate delayed retention.', 'history']
  ]
};

export function curriculumGuide(game) {
  const rows = taskMappings[game];
  if (!rows) return '';
  return `<section class="teacher-guide"><details><summary>What is taught? Open the task and evidence map</summary><p>${game === 'nile' ? 'Nile Quest samples England lower KS2 objectives, with Year 3 maths and science and Years 3–4 comprehension. Ancient Egypt is one KS2 civilisation depth-study option, not a prescribed Year 3 topic. This is part of a unit, not the whole civilisation overview or depth study.' : 'The Midnight Letter is a history investigation for roughly ages 6–9, with reading support. It offers one possible KS1 event beyond living memory; Gunpowder Plot is a school topic choice. Older children can deepen the enquiry. No maths or science assessment is built into this episode.'}</p><p>These are our task-to-curriculum mappings. Select the level using what pupils already know; an age label is not a placement test. English selections practise comprehension, not independent writing.</p><div class="teacher-mapping">${rows.map(([name,area,outcome,task,evidence,next,subject]) => `<article><h4>${name}</h4><p class="teacher-map-area">${area} · ${link(curriculum(subject), 'DfE programme')}</p><dl><dt>Intended learning</dt><dd>${outcome}</dd><dt>What the child does</dt><dd>${task}</dd><dt>What is actually captured</dt><dd>${evidence}</dd><dt>Check next in class</dt><dd>${next}</dd></dl></article>`).join('')}</div><p>Access choices such as reading aloud, larger text and reduced motion are supports, not evidence of a learning difficulty. Neither game diagnoses SEND, assesses all curriculum objectives or carries White Rose approval.</p></details></section>`;
}

export function researchRationale() {
  return `<section class="teacher-guide"><details><summary>Why these teaching choices? EEF guidance and curriculum status</summary><p><strong>EEF-informed, not EEF-endorsed.</strong> These games have not been evaluated by EEF. We apply guidance to a prototype; enjoyment, gems and successful retries do not establish a learning gain.</p><ul><li><strong>Make the thinking visible:</strong> model a subject-specific strategy, ask the learner to check it, then reduce prompts as appropriate. This applies the planning, monitoring and evaluation approach in ${link('https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/metacognition', 'EEF metacognition, second edition (2025)')}.</li><li><strong>Use technology for a teaching purpose:</strong> interactive models, practice and inspectable responses give the world a purpose beyond decoration. See ${link('https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/digital', 'EEF digital technology guidance (2019)')}.</li><li><strong>Act on feedback:</strong> inspect the particular wrong response, offer a useful prompt and check a fresh task afterwards. Applying ${link('https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/feedback', 'EEF teacher feedback guidance')} to automated game feedback is a design judgement, not proof that this feedback works.</li></ul><p><strong>Current England curriculum:</strong> the maps link to published programmes of study. They are not a UK-wide map. The government plans a revised curriculum for first teaching in September 2028, with publication planned for spring 2027; those future programmes are not claimed as implemented here. ${link('https://www.gov.uk/government/publications/curriculum-and-assessment-review-final-report-government-response', 'DfE response and reform plans')}.</p><p>Before a school impact claim, run a supervised pilot: establish prior knowledge, inspect usability and support, then check independent new-task performance and a later revisit. Record how the game was taught as well as the result. Guidance provides a rationale; a school pilot must test this product.</p></details></section>`;
}

export function schoolAccessGuide() {
 const local=typeof location==='undefined'||['localhost','127.0.0.1','[::1]'].includes(location.hostname);
  return `<section class="teacher-guide"><details><summary>What do teachers get now, and what would a school subscription add?</summary><div class="teacher-offer"><article><h4>Available in this prototype</h4><ul><li>Grown-up view on the same device, with real submitted responses and help.</li><li>Curriculum maps, teaching prompts and a downloadable local practice record.</li><li>A separate fictional Alex save for trying mistakes and corrections yourself.</li></ul></article><article><h4>Proposed school service</h4><ul><li>Verified staff login and securely linked pupil records.</li><li>Class and objective views, teacher observations and reports for families.</li><li>Free pupil adventures; a proposed affordable school price around £300/year, to test in a pilot.</li></ul></article></div><p><strong>No teacher login, school roster or cloud pupil dashboard is connected yet.</strong> A school-name selection would not authorise access to a child’s record. A future service needs verified staff and authorised family links, including correction and revocation.</p><p>${local?'This local preview opens on the computer serving it. Use the hosted Schoolgle playtest address for another device.':'Share this playtest address to let another device explore. Progress and practice records stay separate on each browser.'} A JSON download is a local practice record, not a secure school transfer.</p><p><strong>A clear school pitch:</strong> “Purposeful adventures with responses teachers can inspect and use for the next lesson.” Evaluate teacher usefulness and learning transfer before claiming improved attainment.</p></details></section>`;
}
