"use client";

import React from "react";
import type { GeneratedResourcesJSON, WorksheetQuestion, DiffGroup } from "@/types/lesson-studio";

interface WorksheetRendererProps {
  resources: GeneratedResourcesJSON;
  group: DiffGroup;
  lessonTitle: string;
  subject: string;
  className: string;
  date: string;
}

const GROUP_CONFIG: Record<string, { label: string; color: string; packColor: string }> = {
  deeper:   { label: "Deeper (Blue Pack)",   color: "text-blue-700",   packColor: "border-blue-400" },
  core:     { label: "Core (Green Pack)",     color: "text-green-700",  packColor: "border-green-400" },
  scaffold: { label: "Scaffold (Yellow Pack)", color: "text-amber-700", packColor: "border-amber-400" },
  guided:   { label: "Guided (Red Pack)",     color: "text-red-700",    packColor: "border-red-400" },
};

export function WorksheetRenderer({ resources, group, lessonTitle, subject, className, date }: WorksheetRendererProps) {
  const questions = resources.worksheetQuestions?.[group === "all" ? "core" : group] ?? [];
  const config = GROUP_CONFIG[group] ?? GROUP_CONFIG.core;

  if (!questions.length) {
    return (
      <div className="text-center text-sm text-slate-400 py-8">
        No worksheet questions generated for this group.
      </div>
    );
  }

  return (
    <div className={`bg-white p-8 max-w-[210mm] mx-auto border-t-4 ${config.packColor} print:shadow-none`} id={`worksheet-${group}`}>
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-slate-200 pb-3 mb-4">
        <div>
          <h1 className="text-lg font-bold text-slate-900">{lessonTitle}</h1>
          <p className="text-xs text-slate-500">{subject} • {className} • {date}</p>
        </div>
        <div className={`text-xs font-bold px-3 py-1 rounded-full border ${config.packColor} ${config.color}`}>
          {config.label}
        </div>
      </div>

      {/* Name field */}
      <div className="flex items-center gap-2 mb-6">
        <span className="text-sm font-medium text-slate-700">Name:</span>
        <div className="flex-1 border-b-2 border-dotted border-slate-300 h-6" />
      </div>

      {/* Questions */}
      <div className="space-y-6">
        {questions.map((q: WorksheetQuestion, i: number) => (
          <div key={i} className="relative">
            <div className="flex items-start gap-3">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-slate-100 text-xs font-bold text-slate-600 flex items-center justify-center">
                {i + 1}
              </span>
              <div className="flex-1">
                <p className="text-sm text-slate-800 font-medium">{q.q}</p>

                {/* Fill-in parts */}
                {q.type === "fill" && q.parts && (
                  <div className="mt-2 space-y-2">
                    {q.parts.map((part, pi) => (
                      <div key={pi} className="text-sm text-slate-700 font-mono bg-slate-50 p-2 rounded border border-slate-200">
                        {part}
                      </div>
                    ))}
                  </div>
                )}

                {/* Yes/No */}
                {q.type === "yesno" && (
                  <div className="mt-2 flex gap-4">
                    <label className="flex items-center gap-1 text-sm text-slate-600">
                      <span className="w-5 h-5 rounded-full border-2 border-slate-300 inline-block" /> Yes
                    </label>
                    <label className="flex items-center gap-1 text-sm text-slate-600">
                      <span className="w-5 h-5 rounded-full border-2 border-slate-300 inline-block" /> No
                    </label>
                  </div>
                )}

                {/* Open answer space */}
                {q.type === "open" && (
                  <div className="mt-2 border-2 border-slate-200 rounded-lg h-24 bg-[repeating-linear-gradient(transparent,transparent_23px,#e2e8f0_23px,#e2e8f0_24px)]" />
                )}

                {/* Hint */}
                {q.hint && (
                  <div className="mt-1 text-xs text-amber-600 italic">💡 Hint: {q.hint}</div>
                )}

                {/* Marks */}
                <div className="mt-1 text-right">
                  <span className="text-[10px] text-slate-400 border border-slate-200 rounded px-1.5 py-0.5">
                    /{q.marks}
                  </span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-3 border-t border-slate-200 text-right text-[10px] text-slate-400">
        Generated by Lesson Studio • {new Date().toLocaleDateString("en-GB")}
      </div>
    </div>
  );
}
