import { protectedRoute, apiSuccess, apiError } from "@/lib/api-utils";

// Demo floor plan data — a simple UK primary school ground floor
const DEMO_FLOOR_PLAN = {
  id: "demo-primary-school",
  title: "Demo Primary School — Ground Floor",
  width: 900,
  height: 560,
  rooms: [
    {
      id: "reception",
      name: "Reception",
      type: "reception",
      polygon_points: "20,20 200,20 200,120 20,120",
      fill_color: "#f0f9ff",
      area_sqm: 32,
      assets_count: 3,
      issues_count: 0,
      accessible: true,
      temperature: 21,
      booking_status: "available" as const,
      daily_check_order: 1,
      daily_check_done: true,
    },
    {
      id: "office",
      name: "Office",
      type: "office",
      polygon_points: "200,20 360,20 360,120 200,120",
      fill_color: "#fdf4ff",
      area_sqm: 28,
      assets_count: 5,
      issues_count: 1,
      accessible: true,
      temperature: 22,
      daily_check_order: 2,
      daily_check_done: true,
    },
    {
      id: "hall",
      name: "Main Hall",
      type: "hall",
      polygon_points: "20,140 360,140 360,340 20,340",
      fill_color: "#fffbeb",
      area_sqm: 136,
      assets_count: 8,
      issues_count: 1,
      fire_exit: true,
      fire_route: true,
      accessible: true,
      temperature: 19,
      booking_status: "booked" as const,
      daily_check_order: 3,
      daily_check_done: false,
    },
    {
      id: "kitchen",
      name: "Kitchen",
      type: "kitchen",
      polygon_points: "20,360 200,360 200,540 20,540",
      fill_color: "#fff1f2",
      area_sqm: 54,
      assets_count: 12,
      issues_count: 2,
      temperature: 24,
      daily_check_order: 4,
      daily_check_done: false,
    },
    {
      id: "store",
      name: "Store Room",
      type: "storage",
      polygon_points: "200,360 360,360 360,450 200,450",
      fill_color: "#f8fafc",
      area_sqm: 18,
      assets_count: 2,
      issues_count: 0,
      temperature: 17,
    },
    {
      id: "toilets",
      name: "Toilets",
      type: "toilet",
      polygon_points: "200,450 360,450 360,540 200,540",
      fill_color: "#f0fdfa",
      area_sqm: 22,
      assets_count: 4,
      issues_count: 1,
      accessible: true,
      temperature: 19,
      daily_check_order: 5,
      daily_check_done: false,
    },
    {
      id: "classroom-1",
      name: "Classroom 1",
      type: "classroom",
      polygon_points: "400,20 620,20 620,160 400,160",
      fill_color: "#f0fdf4",
      area_sqm: 56,
      assets_count: 6,
      issues_count: 0,
      accessible: true,
      temperature: 21,
      booking_status: "booked" as const,
      daily_check_order: 6,
      daily_check_done: false,
    },
    {
      id: "classroom-2",
      name: "Classroom 2",
      type: "classroom",
      polygon_points: "660,20 880,20 880,160 660,160",
      fill_color: "#f0fdf4",
      area_sqm: 56,
      assets_count: 6,
      issues_count: 0,
      accessible: true,
      temperature: 20,
      booking_status: "booked" as const,
      daily_check_order: 7,
      daily_check_done: false,
    },
    {
      id: "classroom-3",
      name: "Classroom 3",
      type: "classroom",
      polygon_points: "400,200 620,200 620,340 400,340",
      fill_color: "#eff6ff",
      area_sqm: 56,
      assets_count: 6,
      issues_count: 1,
      accessible: true,
      temperature: 22,
      booking_status: "booked" as const,
      daily_check_order: 8,
      daily_check_done: false,
    },
    {
      id: "classroom-4",
      name: "Classroom 4",
      type: "classroom",
      polygon_points: "660,200 880,200 880,340 660,340",
      fill_color: "#eff6ff",
      area_sqm: 56,
      assets_count: 6,
      issues_count: 0,
      fire_exit: true,
      accessible: true,
      temperature: 21,
      booking_status: "partial" as const,
      daily_check_order: 9,
      daily_check_done: false,
    },
    {
      id: "corridor",
      name: "Corridor",
      type: "corridor",
      polygon_points: "360,20 400,20 400,540 360,540",
      fill_color: "#f1f5f9",
      area_sqm: 40,
      assets_count: 2,
      issues_count: 0,
      fire_route: true,
      accessible: true,
      temperature: 18,
      daily_check_order: 10,
      daily_check_done: false,
    },
    {
      id: "staff-room",
      name: "Staff Room",
      type: "office",
      polygon_points: "400,380 620,380 620,540 400,540",
      fill_color: "#fdf4ff",
      area_sqm: 48,
      assets_count: 4,
      issues_count: 0,
      accessible: true,
      temperature: 21,
      booking_status: "available" as const,
    },
    {
      id: "sen-room",
      name: "SEND Room",
      type: "classroom",
      polygon_points: "660,380 880,380 880,540 660,540",
      fill_color: "#fef9c3",
      area_sqm: 36,
      assets_count: 3,
      issues_count: 0,
      accessible: true,
      temperature: 21,
      booking_status: "available" as const,
    },
  ],
};

export const GET = protectedRoute(async () => {
  return apiSuccess({
    success: true,
    data: DEMO_FLOOR_PLAN,
  });
});

export const POST = protectedRoute(async () => {
  return apiError(
    "Floor plan upload is not yet implemented. Coming soon.",
    501,
  );
});
