// Mid-year 2025/26 teacher assessment data — self-reported by Pennine Academies. Source: Trust-wide data capture spreadsheet.

import { SchoolSelfReport } from './types';

export const PENNINE_SELF_REPORTS: SchoolSelfReport[] = [
  // ─── CVPS — Clayton Village Primary School ───────────────────────────
  // 193 NOR, 15% FSM
  {
    school: 'CVPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 30,
        allPupils:  { reading: 63, writing: 43, maths: 63, combined: null },
        fsm6:       { reading: 50, writing: 25, maths: 50, combined: null },
        nonFsm:     { reading: 67, writing: 48, maths: 67, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 43,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 28,
        allPupils:  { reading: 64, writing: 50, maths: 71, combined: 50 },
        fsm6:       { reading: 60, writing: 20, maths: 60, combined: 20 },
        nonFsm:     { reading: 65, writing: 57, maths: 74, combined: 57 },
        gd:         { reading:  7, writing:  0, maths:  7, combined:  0 },
        phonics: 64,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 27,
        allPupils:  { reading: 63, writing: 52, maths: 70, combined: 48 },
        fsm6:       { reading: 50, writing: 33, maths: 67, combined: 33 },
        nonFsm:     { reading: 67, writing: 57, maths: 71, combined: 52 },
        gd:         { reading: 11, writing:  4, maths: 11, combined:  4 },
        phonics: 85,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 30,
        allPupils:  { reading: 57, writing: 47, maths: 63, combined: 43 },
        fsm6:       { reading: 25, writing: 25, maths: 25, combined: 25 },
        nonFsm:     { reading: 62, writing: 50, maths: 69, combined: 46 },
        gd:         { reading: 10, writing:  3, maths: 10, combined:  3 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 29,
        allPupils:  { reading: 62, writing: 52, maths: 69, combined: 52 },
        fsm6:       { reading: 40, writing: 20, maths: 40, combined: 20 },
        nonFsm:     { reading: 67, writing: 58, maths: 75, combined: 58 },
        gd:         { reading: 10, writing:  0, maths: 14, combined:  0 },
        mtc: 62,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 25,
        allPupils:  { reading: 64, writing: 52, maths: 72, combined: 52 },
        fsm6:       { reading: 33, writing: 33, maths: 33, combined: 33 },
        nonFsm:     { reading: 68, writing: 55, maths: 77, combined: 55 },
        gd:         { reading: 12, writing:  4, maths: 12, combined:  4 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 24,
        allPupils:  { reading: 67, writing: 54, maths: 71, combined: 50 },
        fsm6:       { reading: 50, writing: 25, maths: 50, combined: 25 },
        nonFsm:     { reading: 71, writing: 59, maths: 76, combined: 53 },
        gd:         { reading:  8, writing:  0, maths:  8, combined:  0 },
      },
    ],
  },

  // ─── CHPS — Crossley Hall Primary School ─────────────────────────────
  // 676 NOR, 29.6% FSM, 76.2% EAL
  {
    school: 'CHPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 90,
        allPupils:  { reading: 54, writing: 38, maths: 58, combined: null },
        fsm6:       { reading: 42, writing: 27, maths: 46, combined: null },
        nonFsm:     { reading: 59, writing: 42, maths: 63, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 38,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 87,
        allPupils:  { reading: 61, writing: 45, maths: 62, combined: 40 },
        fsm6:       { reading: 48, writing: 30, maths: 48, combined: 26 },
        nonFsm:     { reading: 66, writing: 51, maths: 68, combined: 46 },
        gd:         { reading:  5, writing:  1, maths:  3, combined:  1 },
        phonics: 59,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 98,
        allPupils:  { reading: 62, writing: 49, maths: 67, combined: 47 },
        fsm6:       { reading: 50, writing: 36, maths: 54, combined: 32 },
        nonFsm:     { reading: 67, writing: 54, maths: 72, combined: 53 },
        gd:         { reading:  8, writing:  2, maths:  8, combined:  2 },
        phonics: 78,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 95,
        allPupils:  { reading: 56, writing: 43, maths: 59, combined: 39 },
        fsm6:       { reading: 39, writing: 29, maths: 43, combined: 25 },
        nonFsm:     { reading: 63, writing: 49, maths: 66, combined: 45 },
        gd:         { reading:  5, writing:  1, maths:  6, combined:  1 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 98,
        allPupils:  { reading: 63, writing: 50, maths: 64, combined: 46 },
        fsm6:       { reading: 46, writing: 33, maths: 46, combined: 29 },
        nonFsm:     { reading: 71, writing: 57, maths: 72, combined: 54 },
        gd:         { reading:  7, writing:  1, maths:  5, combined:  1 },
        mtc: 60,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 100,
        allPupils:  { reading: 67, writing: 55, maths: 65, combined: 51 },
        fsm6:       { reading: 50, writing: 37, maths: 47, combined: 33 },
        nonFsm:     { reading: 74, writing: 62, maths: 73, combined: 59 },
        gd:         { reading:  8, writing:  2, maths:  7, combined:  2 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 94,
        allPupils:  { reading: 71, writing: 67, maths: 69, combined: 51 },
        fsm6:       { reading: 55, writing: 52, maths: 52, combined: 35 },
        nonFsm:     { reading: 78, writing: 73, maths: 76, combined: 58 },
        gd:         { reading: 10, writing:  3, maths:  9, combined:  3 },
      },
    ],
  },

  // ─── FPS — Farnham Primary School ────────────────────────────────────
  // 449 NOR, 25.8% FSM, 85.1% EAL
  {
    school: 'FPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 60,
        allPupils:  { reading: 58, writing: 42, maths: 62, combined: null },
        fsm6:       { reading: 44, writing: 28, maths: 50, combined: null },
        nonFsm:     { reading: 63, writing: 47, maths: 66, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 42,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 62,
        allPupils:  { reading: 65, writing: 47, maths: 66, combined: 44 },
        fsm6:       { reading: 50, writing: 31, maths: 50, combined: 28 },
        nonFsm:     { reading: 70, writing: 52, maths: 72, combined: 49 },
        gd:         { reading:  6, writing:  2, maths:  5, combined:  2 },
        phonics: 63,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 65,
        allPupils:  { reading: 66, writing: 52, maths: 69, combined: 49 },
        fsm6:       { reading: 47, writing: 33, maths: 53, combined: 33 },
        nonFsm:     { reading: 73, writing: 59, maths: 75, combined: 55 },
        gd:         { reading:  8, writing:  2, maths:  8, combined:  2 },
        phonics: 82,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 63,
        allPupils:  { reading: 60, writing: 46, maths: 65, combined: 43 },
        fsm6:       { reading: 40, writing: 27, maths: 47, combined: 27 },
        nonFsm:     { reading: 67, writing: 52, maths: 72, combined: 49 },
        gd:         { reading:  6, writing:  2, maths:  8, combined:  2 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 68,
        allPupils:  { reading: 68, writing: 53, maths: 66, combined: 49 },
        fsm6:       { reading: 50, writing: 33, maths: 44, combined: 28 },
        nonFsm:     { reading: 74, writing: 60, maths: 74, combined: 57 },
        gd:         { reading:  7, writing:  1, maths:  6, combined:  1 },
        mtc: 65,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 66,
        allPupils:  { reading: 70, writing: 55, maths: 68, combined: 52 },
        fsm6:       { reading: 53, writing: 35, maths: 47, combined: 29 },
        nonFsm:     { reading: 76, writing: 62, maths: 76, combined: 60 },
        gd:         { reading:  9, writing:  2, maths:  6, combined:  2 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 64,
        allPupils:  { reading: 73, writing: 59, maths: 73, combined: 56 },
        fsm6:       { reading: 56, writing: 38, maths: 56, combined: 31 },
        nonFsm:     { reading: 80, writing: 67, maths: 80, combined: 67 },
        gd:         { reading: 11, writing:  2, maths:  8, combined:  2 },
      },
    ],
  },

  // ─── GHPS — Grove House Primary School ───────────────────────────────
  // 417 NOR, 27.3% FSM — NO EYFS DATA SUBMITTED
  {
    school: 'GHPS',
    yearGroups: [
      {
        yearGroup: 'Y1',
        cohortSize: 57,
        allPupils:  { reading: 65, writing: 47, maths: 67, combined: 44 },
        fsm6:       { reading: 47, writing: 27, maths: 53, combined: 27 },
        nonFsm:     { reading: 71, writing: 54, maths: 73, combined: 51 },
        gd:         { reading:  7, writing:  2, maths:  9, combined:  2 },
        phonics: 63,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 60,
        allPupils:  { reading: 65, writing: 53, maths: 68, combined: 50 },
        fsm6:       { reading: 50, writing: 38, maths: 56, combined: 31 },
        nonFsm:     { reading: 71, writing: 60, maths: 74, combined: 57 },
        gd:         { reading: 10, writing:  3, maths: 10, combined:  3 },
        phonics: 80,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 58,
        allPupils:  { reading: 62, writing: 48, maths: 66, combined: 45 },
        fsm6:       { reading: 44, writing: 31, maths: 50, combined: 25 },
        nonFsm:     { reading: 69, writing: 54, maths: 72, combined: 51 },
        gd:         { reading:  7, writing:  2, maths:  9, combined:  2 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 62,
        allPupils:  { reading: 68, writing: 55, maths: 71, combined: 52 },
        fsm6:       { reading: 47, writing: 33, maths: 53, combined: 27 },
        nonFsm:     { reading: 76, writing: 63, maths: 78, combined: 61 },
        gd:         { reading: 10, writing:  3, maths: 13, combined:  3 },
        mtc: 68,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 56,
        allPupils:  { reading: 70, writing: 59, maths: 73, combined: 55 },
        fsm6:       { reading: 50, writing: 38, maths: 56, combined: 31 },
        nonFsm:     { reading: 78, writing: 67, maths: 80, combined: 64 },
        gd:         { reading: 11, writing:  4, maths: 13, combined:  4 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 58,
        allPupils:  { reading: 76, writing: 69, maths: 78, combined: 66 },
        fsm6:       { reading: 56, writing: 50, maths: 56, combined: 44 },
        nonFsm:     { reading: 85, writing: 77, maths: 88, combined: 74 },
        gd:         { reading: 14, writing:  5, maths: 17, combined:  5 },
      },
    ],
  },

  // ─── HPS — Hollingwood Primary School ────────────────────────────────
  // 482 NOR, 25.9% FSM — trust star performer
  {
    school: 'HPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 60,
        allPupils:  { reading: 68, writing: 52, maths: 70, combined: null },
        fsm6:       { reading: 53, writing: 33, maths: 53, combined: null },
        nonFsm:     { reading: 73, writing: 58, maths: 75, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 52,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 68,
        allPupils:  { reading: 72, writing: 57, maths: 74, combined: 54 },
        fsm6:       { reading: 57, writing: 36, maths: 57, combined: 29 },
        nonFsm:     { reading: 78, writing: 64, maths: 80, combined: 62 },
        gd:         { reading: 10, writing:  3, maths: 12, combined:  3 },
        phonics: 74,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 70,
        allPupils:  { reading: 73, writing: 60, maths: 76, combined: 57 },
        fsm6:       { reading: 56, writing: 44, maths: 61, combined: 39 },
        nonFsm:     { reading: 80, writing: 67, maths: 82, combined: 65 },
        gd:         { reading: 13, writing:  4, maths: 14, combined:  4 },
        phonics: 86,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 72,
        allPupils:  { reading: 69, writing: 56, maths: 72, combined: 53 },
        fsm6:       { reading: 50, writing: 36, maths: 57, combined: 29 },
        nonFsm:     { reading: 76, writing: 63, maths: 78, combined: 62 },
        gd:         { reading: 11, writing:  3, maths: 11, combined:  3 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 68,
        allPupils:  { reading: 74, writing: 62, maths: 76, combined: 59 },
        fsm6:       { reading: 53, writing: 40, maths: 60, combined: 33 },
        nonFsm:     { reading: 82, writing: 71, maths: 82, combined: 69 },
        gd:         { reading: 12, writing:  4, maths: 15, combined:  4 },
        mtc: 76,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 65,
        allPupils:  { reading: 75, writing: 63, maths: 77, combined: 60 },
        fsm6:       { reading: 56, writing: 44, maths: 56, combined: 38 },
        nonFsm:     { reading: 82, writing: 70, maths: 85, combined: 69 },
        gd:         { reading: 14, writing:  5, maths: 14, combined:  5 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 64,
        allPupils:  { reading: 80, writing: 72, maths: 83, combined: 71 },
        fsm6:       { reading: 63, writing: 56, maths: 69, combined: 50 },
        nonFsm:     { reading: 87, writing: 80, maths: 89, combined: 78 },
        gd:         { reading: 16, writing:  6, maths: 19, combined:  6 },
      },
    ],
  },

  // ─── LPS — Laycock Primary School ────────────────────────────────────
  // 88 NOR, 47.7% FSM — tiny school
  {
    school: 'LPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 12,
        allPupils:  { reading: 58, writing: 42, maths: 58, combined: null },
        fsm6:       { reading: 43, writing: 29, maths: 43, combined: null },
        nonFsm:     { reading: 71, writing: 57, maths: 71, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 42,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 13,
        allPupils:  { reading: 62, writing: 46, maths: 62, combined: 38 },
        fsm6:       { reading: 43, writing: 29, maths: 43, combined: 14 },
        nonFsm:     { reading: 83, writing: 67, maths: 83, combined: 67 },
        gd:         { reading:  8, writing:  0, maths:  8, combined:  0 },
        phonics: 54,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 14,
        allPupils:  { reading: 64, writing: 50, maths: 64, combined: 43 },
        fsm6:       { reading: 50, writing: 33, maths: 50, combined: 17 },
        nonFsm:     { reading: 75, writing: 63, maths: 75, combined: 63 },
        gd:         { reading:  7, writing:  0, maths:  7, combined:  0 },
        phonics: 77,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 11,
        allPupils:  { reading: 55, writing: 36, maths: 55, combined: 36 },
        fsm6:       { reading: 40, writing: 20, maths: 40, combined: 20 },
        nonFsm:     { reading: 67, writing: 50, maths: 67, combined: 50 },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 13,
        allPupils:  { reading: 62, writing: 46, maths: 62, combined: 38 },
        fsm6:       { reading: 43, writing: 29, maths: 43, combined: 14 },
        nonFsm:     { reading: 83, writing: 67, maths: 83, combined: 67 },
        gd:         { reading:  8, writing:  0, maths:  8, combined:  0 },
        mtc: 54,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 12,
        allPupils:  { reading: 58, writing: 42, maths: 58, combined: 33 },
        fsm6:       { reading: 43, writing: 14, maths: 43, combined: 14 },
        nonFsm:     { reading: 80, writing: 80, maths: 80, combined: 60 },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 11,
        allPupils:  { reading: 64, writing: 55, maths: 64, combined: 55 },
        fsm6:       { reading: 50, writing: 33, maths: 50, combined: 33 },
        nonFsm:     { reading: 83, writing: 83, maths: 83, combined: 83 },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
      },
    ],
  },

  // ─── LGPS — Lidget Green Primary School ──────────────────────────────
  // 516 NOR, 34.9% FSM, 73.3% EAL
  {
    school: 'LGPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 72,
        allPupils:  { reading: 53, writing: 36, maths: 57, combined: null },
        fsm6:       { reading: 36, writing: 20, maths: 40, combined: null },
        nonFsm:     { reading: 62, writing: 44, maths: 66, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
        gld: 36,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 75,
        allPupils:  { reading: 56, writing: 39, maths: 59, combined: 36 },
        fsm6:       { reading: 38, writing: 21, maths: 41, combined: 17 },
        nonFsm:     { reading: 65, writing: 48, maths: 67, combined: 44 },
        gd:         { reading:  4, writing:  0, maths:  3, combined:  0 },
        phonics: 53,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 78,
        allPupils:  { reading: 59, writing: 44, maths: 62, combined: 41 },
        fsm6:       { reading: 41, writing: 26, maths: 44, combined: 22 },
        nonFsm:     { reading: 68, writing: 53, maths: 72, combined: 51 },
        gd:         { reading:  5, writing:  1, maths:  5, combined:  1 },
        phonics: 71,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 76,
        allPupils:  { reading: 53, writing: 37, maths: 55, combined: 33 },
        fsm6:       { reading: 35, writing: 19, maths: 35, combined: 15 },
        nonFsm:     { reading: 62, writing: 46, maths: 65, combined: 42 },
        gd:         { reading:  3, writing:  0, maths:  3, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 74,
        allPupils:  { reading: 58, writing: 43, maths: 59, combined: 39 },
        fsm6:       { reading: 38, writing: 23, maths: 38, combined: 19 },
        nonFsm:     { reading: 68, writing: 53, maths: 70, combined: 49 },
        gd:         { reading:  5, writing:  1, maths:  4, combined:  1 },
        mtc: 55,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 73,
        allPupils:  { reading: 55, writing: 33, maths: 52, combined: 25 },
        fsm6:       { reading: 36, writing: 14, maths: 32, combined:  9 },
        nonFsm:     { reading: 65, writing: 43, maths: 63, combined: 33 },
        gd:         { reading:  4, writing:  0, maths:  3, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 70,
        allPupils:  { reading: 63, writing: 51, maths: 60, combined: 44 },
        fsm6:       { reading: 44, writing: 33, maths: 40, combined: 24 },
        nonFsm:     { reading: 72, writing: 60, maths: 70, combined: 55 },
        gd:         { reading:  6, writing:  1, maths:  4, combined:  1 },
      },
    ],
  },
];
