// Mid-year 2025/26 teacher assessment data — self-reported by Pennine Academies. Source: Trust-wide data capture spreadsheet.

import { SchoolSelfReport } from './types';

export const PENNINE_SELF_REPORTS: SchoolSelfReport[] = [
  // ─── CVPS — Clayton Village Primary School ───────────────────────────
  {
    school: 'CVPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 27,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
        gld: 64,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 27,
        allPupils:  { reading: 73, writing: 64, maths: 59, combined: 55 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
        phonics: 64,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 27,
        allPupils:  { reading: 68, writing: 64, maths: 68, combined: 64 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 10, writing:  0, maths:  5, combined:  0 },
        phonics: 77,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 30,
        allPupils:  { reading: 71, writing: 71, maths: 75, combined: 67 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  8, writing:  8, maths: 13, combined:  4 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 26,
        allPupils:  { reading: 85, writing: 80, maths: 75, combined: 60 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 35, writing: 10, maths: 15, combined:  5 },
        mtc: 65,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 30,
        allPupils:  { reading: 75, writing: 75, maths: 75, combined: 70 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  5, writing:  0, maths: 20, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 25,
        allPupils:  { reading: 81, writing: 75, maths: 75, combined: 75 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 38, writing: 19, maths: 31, combined: 19 },
      },
    ],
  },

  // ─── CHPS — Crossley Hall Primary School ─────────────────────────────
  {
    school: 'CHPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 70,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
      },
      {
        yearGroup: 'Y1',
        cohortSize: 64,
        allPupils:  { reading: 45, writing: 48, maths: 48, combined: 44 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined: null },
      },
      {
        yearGroup: 'Y2',
        cohortSize: 81,
        allPupils:  { reading: 59, writing: 55, maths: 66, combined: 53 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 21, writing:  0, maths:  9, combined:  0 },
      },
      {
        yearGroup: 'Y3',
        cohortSize: 88,
        allPupils:  { reading: 73, writing: 69, maths: 73, combined: 67 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 33, writing:  0, maths: 31, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 81,
        allPupils:  { reading: 56, writing: 46, maths: 65, combined: 42 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 17, writing:  0, maths: 21, combined: null },
      },
      {
        yearGroup: 'Y5',
        cohortSize: 90,
        allPupils:  { reading: 70, writing: 64, maths: 66, combined: 60 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 13, writing:  0, maths: 15, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 87,
        allPupils:  { reading: 70, writing: 76, maths: 65, combined: 54 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 35, writing:  0, maths: 13, combined:  0 },
      },
    ],
  },

  // ─── FPS — Farnham Primary School ────────────────────────────────────
  {
    school: 'FPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 45,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
        gld: 57,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 59,
        allPupils:  { reading: 53, writing: 53, maths: 68, combined: 51 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
        phonics: 65,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 56,
        allPupils:  { reading: 60, writing: 52, maths: 63, combined: 48 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 13, writing:  2, maths: 23, combined:  2 },
      },
      {
        yearGroup: 'Y3',
        cohortSize: 57,
        allPupils:  { reading: 61, writing: 61, maths: 70, combined: 57 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 11, writing:  0, maths:  9, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 61,
        allPupils:  { reading: 60, writing: 57, maths: 60, combined: 55 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 10, writing:  5, maths: 10, combined:  5 },
      },
      {
        yearGroup: 'Y5',
        cohortSize: 56,
        allPupils:  { reading: 64, writing: 56, maths: 62, combined: 49 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  8, writing:  0, maths:  5, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 61,
        allPupils:  { reading: 68, writing: 68, maths: 73, combined: 62 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 11, writing:  0, maths:  4, combined:  0 },
      },
    ],
  },

  // ─── GHPS — Grove House Primary School ───────────────────────────────
  // NO EYFS DATA SUBMITTED
  {
    school: 'GHPS',
    yearGroups: [
      {
        yearGroup: 'Y1',
        cohortSize: 56,
        allPupils:  { reading: 39, writing: 54, maths: 59, combined: 44 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  5, writing:  5, maths:  0, combined:  0 },
        phonics: 53,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 58,
        allPupils:  { reading: 66, writing: 69, maths: 74, combined: 62 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 14, writing:  3, maths: 11, combined:  0 },
        phonics: 81,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 47,
        allPupils:  { reading: 55, writing: 54, maths: 71, combined: 44 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  6, writing:  5, maths: 19, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 53,
        allPupils:  { reading: 73, writing: 65, maths: 65, combined: 51 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  5, writing: 16, maths: 14, combined:  3 },
      },
      {
        yearGroup: 'Y5',
        cohortSize: 59,
        allPupils:  { reading: 74, writing: 80, maths: 71, combined: 71 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 14, writing: 17, maths: 23, combined:  6 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 53,
        allPupils:  { reading: 57, writing: 54, maths: 51, combined: 43 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 17, writing:  9, maths:  9, combined:  3 },
      },
    ],
  },

  // ─── HPS — Hollingwood Primary School ────────────────────────────────
  {
    school: 'HPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 54,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
      },
      {
        yearGroup: 'Y1',
        cohortSize: 60,
        allPupils:  { reading: 50, writing: 52, maths: 61, combined: 50 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
      },
      {
        yearGroup: 'Y2',
        cohortSize: 61,
        allPupils:  { reading: 65, writing: 63, maths: 67, combined: 59 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths: 11, combined:  0 },
      },
      {
        yearGroup: 'Y3',
        cohortSize: 61,
        allPupils:  { reading: 70, writing: 70, maths: 75, combined: 63 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths: 13, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 64,
        allPupils:  { reading: 56, writing: 59, maths: 49, combined: 37 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 22, writing: 15, maths: 15, combined:  5 },
        mtc: 64,
      },
      {
        yearGroup: 'Y5',
        cohortSize: 66,
        allPupils:  { reading: 59, writing: 57, maths: 55, combined: 36 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 13, writing: 14, maths: 14, combined:  5 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 65,
        allPupils:  { reading: 90, writing: 85, maths: 83, combined: 83 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 60, writing: 13, maths: 38, combined: 13 },
      },
    ],
  },

  // ─── LPS — Laycock Primary School ────────────────────────────────────
  // Tiny school — small cohorts make percentages statistically unreliable
  {
    school: 'LPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 6,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
        gld: 100,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 12,
        allPupils:  { reading: 80, writing: 60, maths: 80, combined: 60 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing:  0, maths:  0, combined:  0 },
        phonics: 100,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 13,
        allPupils:  { reading: 58, writing: 58, maths: 58, combined: 58 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
        phonics: 25,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 13,
        allPupils:  { reading: 88, writing: 88, maths: 88, combined: 88 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 13, writing:  0, maths:  9, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 13,
        allPupils:  { reading: 100, writing: 100, maths: 100, combined: 100 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths: 66, combined:  0 },
      },
      {
        yearGroup: 'Y5',
        cohortSize: 10,
        allPupils:  { reading: 25, writing: 25, maths: 25, combined: 25 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 25, writing:  0, maths: 25, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 12,
        allPupils:  { reading: 100, writing: 50, maths: 100, combined: 42 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 25, writing:  0, maths: 50, combined:  0 },
      },
    ],
  },

  // ─── LGPS — Lidget Green Primary School ──────────────────────────────
  {
    school: 'LGPS',
    yearGroups: [
      {
        yearGroup: 'EYFS',
        cohortSize: 50,
        allPupils:  { reading: null, writing: null, maths: null, combined: null },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: null, writing: null, maths: null, combined: null },
        gld: 45,
      },
      {
        yearGroup: 'Y1',
        cohortSize: 64,
        allPupils:  { reading: 69, writing: 59, maths: 66, combined: 59 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
        phonics: 46,
      },
      {
        yearGroup: 'Y2',
        cohortSize: 61,
        allPupils:  { reading: 63, writing: 57, maths: 63, combined: 54 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  0, writing:  0, maths:  0, combined:  0 },
        phonics: 92,
      },
      {
        yearGroup: 'Y3',
        cohortSize: 61,
        allPupils:  { reading: 59, writing: 50, maths: 56, combined: 50 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  9, writing:  0, maths:  6, combined:  0 },
      },
      {
        yearGroup: 'Y4',
        cohortSize: 82,
        allPupils:  { reading: 63, writing: 53, maths: 68, combined: 53 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  5, writing:  0, maths:  8, combined:  0 },
      },
      {
        yearGroup: 'Y5',
        cohortSize: 76,
        allPupils:  { reading: 55, writing: 50, maths: 53, combined: 39 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading:  5, writing:  0, maths:  5, combined:  0 },
      },
      {
        yearGroup: 'Y6',
        cohortSize: 83,
        allPupils:  { reading: 81, writing: 72, maths: 75, combined: 67 },
        fsm6:       { reading: null, writing: null, maths: null, combined: null },
        nonFsm:     { reading: null, writing: null, maths: null, combined: null },
        gd:         { reading: 30, writing:  2, maths: 21, combined:  2 },
      },
    ],
  },
];
