import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const dir='test-results/atmosphere';fs.mkdirSync(dir,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],checks=[];
const pass=s=>{checks.push(s);console.log('PASS',s);};
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:4173/?game=nile');await page.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached'});await page.waitForTimeout(700);await page.screenshot({path:`dir/landing.png`.replace('dir',dir)});
 assert.match(await page.locator('.welcome-copy').innerText(),/sphinx/);assert.deepEqual(await page.evaluate(()=>window.__nile.snapshot().sphinxInfo.dimensions.map(v=>Math.round(v*10)/10)),[6.4,8,12.8]);pass('Original sphinx loads at the intended world scale; new story invitation appears');
 await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();await page.locator('#settings').click();await page.locator('#lighting').selectOption('day');await page.getByRole('button',{name:'Ready to explore',exact:true}).click();await page.waitForTimeout(700);await page.screenshot({path:`${dir}/day-village.png`});
 await page.reload();await page.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached'});assert.equal(await page.evaluate(()=>window.__nile.snapshot().settings.lighting),'day');pass('Brighter daylight preference persists after reload');
 await page.locator('#begin').click();await page.locator('#settings').click();await page.locator('#lighting').selectOption('evening');await page.locator('[data-setting="reducedMotion"]').check();await page.getByRole('button',{name:'Ready to explore',exact:true}).click();await page.waitForTimeout(400);const a=await page.locator('#world canvas').screenshot();await page.waitForTimeout(400);const b=await page.locator('#world canvas').screenshot();assert.ok(a.equals(b));pass('Evening atmosphere remains still with reduced motion enabled');
 await page.screenshot({path:`${dir}/evening-village.png`});
 const tablet=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true});tablet.on('pageerror',e=>errors.push(e.message));await tablet.goto('http://127.0.0.1:4173/?game=nile');await tablet.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await tablet.waitForSelector('#loading',{state:'detached'});await tablet.locator('#access-start').click();await tablet.locator('#lighting').selectOption('day');await tablet.getByRole('button',{name:'Ready to explore',exact:true}).click();assert.equal(await tablet.evaluate(()=>window.__nile.snapshot().settings.lighting),'day');assert.ok(await tablet.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await tablet.screenshot({path:`${dir}/tablet-day.png`});await tablet.close();pass('Touch-layout lighting choice works at 1024×768 without horizontal overflow');
 // Isolated visual review uses the real renderer and geometry, not pupil progress.
 await page.route('**/atmosphere-harness',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="en"><title>Atmosphere review harness</title><style>body{margin:0}canvas{display:block}</style><div id="world"></div><script type="module">import {NileWorld} from "/src/world.js";window.world=new NileWorld(document.getElementById("world"));await world.heroPromise;world.setSettings({reducedMotion:true,lighting:"evening",quality:"high"});world.start([43,20]);window.ready=true;</script></html>'}));
 await page.goto('http://127.0.0.1:4173/atmosphere-harness');await page.waitForFunction(()=>window.ready);
 for(const [name,position,angle,pitch,zoom]of [['sphinx',[43,17],.28,.35,13],['temple',[58,2],.05,.38,12],['carvings',[19,48],.1,.25,8]]){
  await page.evaluate(({position,angle,pitch,zoom})=>{world.start(position);world.angle=angle;world.pitch=pitch;world.zoom=zoom;}, {position,angle,pitch,zoom});await page.waitForTimeout(350);await page.screenshot({path:`${dir}/${name}.png`});
 }
 const before=await page.evaluate(()=>world.tombDoor.position.y);await page.evaluate(()=>world.worldReward(4));assert.ok(await page.evaluate(()=>world.tombDoor.position.y)>before);assert.ok(await page.evaluate(()=>world.tombDoor.children.length)>0);pass('Carved door decoration moves with the existing earned tomb-door reward');
 assert.deepEqual(errors,[]);pass('No shader compilation errors, browser exceptions or rendering console errors');
}finally{fs.writeFileSync(`${dir}/report.json`,JSON.stringify({checks,errors},null,2));await browser.close();}
