import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const BASE_URL=process.env.NILE_TEST_URL||'http://127.0.0.1:4173/?game=nile';
const BASE_ORIGIN=new URL(BASE_URL).origin;
fs.mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:'test-results/video',size:{width:1280,height:800}}});
const page=await context.newPage();page.setDefaultTimeout(12000);
const errors=[],badResponses=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)badResponses.push(r.url()+' '+r.status());});page.on('request',r=>{if(!r.url().startsWith('data:')&&new URL(r.url()).origin!==BASE_ORIGIN)external.push(r.url());});
const snap=()=>page.evaluate(()=>window.__nile.snapshot());
const report={checks:[],screenshots:[],errors,badResponses,external};
function passed(t){report.checks.push(t);console.log('PASS',t);}
async function shot(name){await page.screenshot({path:`test-results/${name}.png`});report.screenshots.push(name);}
async function guide(id){await page.locator('#guide').click();await page.waitForFunction(id=>window.__nile.snapshot().nearest===id,id,{timeout:20000});await page.locator('#interact-button').click();await page.locator('.challenge').waitFor();}
async function claim(id){await page.getByRole('button',{name:'Collect your discovery'}).click();await page.locator('#reward-next').waitFor();assert.equal((await snap()).completed.includes(id),true);await page.locator('#reward-next').click();}
try{
 await page.goto(BASE_URL);await page.waitForFunction(()=>window.__nile,null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached',timeout:60000});await shot('01-landing');passed('3D world and all six animated GLB assets load');
 assert.deepEqual((await snap()).clips.sort(),['Celebrate','Idle','Run','Walk']);assert.equal(external.length,0);passed('Assets, fonts and prepared narration are local');
 await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();const before=(await snap()).position;await page.keyboard.down('w');await page.waitForTimeout(500);assert.equal((await snap()).action,'Walk');await page.keyboard.down('Shift');await page.waitForTimeout(300);assert.equal((await snap()).action,'Run');await page.keyboard.up('Shift');await page.keyboard.up('w');assert.ok(Math.hypot(...(await snap()).position.map((v,i)=>v-before[i]))>1);passed('Real keyboard movement and walk/run animation transitions');await shot('02-exploration');
 await page.locator('#map').click();assert.ok(await page.locator('[data-go="1"]').first().isDisabled());await page.getByRole('button',{name:'Close',exact:true}).click();passed('Future missions remain gated');
 await guide(0);for(let i=1;i<=3;i++)await page.getByRole('button',{name:'Water gate '+i}).click();await page.getByRole('button',{name:'The desert sand never needed water.'}).click();assert.equal((await snap()).gems,0);await page.getByRole('button',{name:'The floodwater brought water and fertile silt.'}).click();await shot('03-irrigation');await claim(0);passed('Irrigation flow, corrective feedback and first reward');
 await guide(1);await page.getByRole('button',{name:'Check the cargo'}).click();await page.getByRole('button',{name:'Practise first with 6 baskets'}).click();for(let i=0;i<2;i++)await page.getByRole('button',{name:'Share one to each boat'}).click();await page.getByRole('button',{name:'Check the cargo'}).click();assert.equal((await snap()).completed.includes(1),false);assert.equal(await page.locator('#remaining').innerText(),'24');for(let i=0;i<8;i++)await page.getByRole('button',{name:'Share one to each boat'}).click();await shot('04-cargo');await page.getByRole('button',{name:'Check the cargo'}).click();await page.getByRole('button',{name:'3 groups of 8 use all 24 baskets.',exact:true}).click();await claim(1);passed('Smaller-number scaffold returns to original learning objective');
 await guide(2);await page.getByRole('button',{name:'It needs water from the channel.'}).click();await page.getByRole('button',{name:'The second field is dry, beyond the channel.'}).click();await claim(2);passed('English inference followed by evidence selection');
 await guide(3);await page.getByRole('button',{name:'Move Tomb discovery later'}).click();await page.getByRole('button',{name:'Move Tomb discovery later'}).click();await page.getByRole('button',{name:'Set the timeline'}).click();await shot('05-timeline');await claim(3);passed('BC/AD timeline ordering');
 await guide(4);await page.getByRole('button',{name:'Larger',exact:true}).click();await page.locator('#shadow-distance').focus();await page.keyboard.press('Home');for(let i=0;i<25;i++)await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Open the chamber',exact:true}).click();await page.getByRole('button',{name:'Nearer the lamp made the shadow larger.',exact:true}).click();await shot('06-shadow');await claim(4);passed('Prediction and keyboard-operated shadow investigation');
 await guide(5);const canvas=page.locator('.sand-layer'),box=await canvas.boundingBox();await page.mouse.move(box.x+15,box.y+15);await page.mouse.down();for(let y=10;y<box.height;y+=22){await page.mouse.move(box.x+10,box.y+y);await page.mouse.move(box.x+box.width-10,box.y+y,{steps:24});}await page.mouse.up();await page.getByRole('button',{name:'B2',exact:true}).click();await page.getByRole('button',{name:'Its position can help explain how it was used.'}).click();await shot('07-archaeology');await claim(5);passed('Pointer brushing, grid reference and archaeology evidence');
 await guide(6);for(const text of ['The Nile supported farming and travel.','His tomb was in the Valley of the Kings.','Egyptian workers were essential to Carter’s excavation team.','…its position is part of the evidence.'])await page.getByRole('button',{name:text,exact:true}).click();await claim(6);await shot('08-journal');assert.equal((await snap()).gems,210);passed('All seven missions complete; journal and rewards agree');
 await page.locator('#progress-report').click();assert.equal(await page.locator('tbody tr').count(),7);await shot('09-practice-record');await page.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.waitForFunction(()=>window.__nile,null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached',timeout:60000});assert.equal((await snap()).gems,210);await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();passed('Reload persists progress, evidence and rewards');
 await page.locator('#settings').click();await page.locator('[data-setting="largeText"]').check();await page.locator('[data-setting="reducedMotion"]').check();await page.locator('#quality').selectOption('low');await page.getByRole('button',{name:'Ready to explore'}).click();assert.equal((await snap()).settings.largeText,true);await page.waitForTimeout(300);const stillA=await page.locator('#world canvas').screenshot();await page.waitForTimeout(350);const stillB=await page.locator('#world canvas').screenshot();assert.ok(stillA.equals(stillB),'Reduced-motion world must remain visually still while stationary');passed('Reduced motion freezes environmental animation');await page.locator('#journal').click();await page.locator('#return-challenge').click();await page.getByRole('button',{name:'Dry desert far from water.',exact:true}).click();assert.ok(await page.locator('.recall-help').isVisible());assert.ok(await page.getByRole('heading',{name:'A new riverside village needs farmland. Which place is better?'}).isVisible());passed('Wrong return answer receives teaching and cannot skip the idea');for(const text of ['Land beside a water channel with fertile soil.','Six','Record its position and surroundings.']){await page.getByRole('button',{name:text,exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.tagName),'H3');}await page.locator('#recall-done').click();passed('Comfort settings and return check work');
 await page.locator('#map').click();await page.locator('.map-list [data-go="0"]').click();await page.waitForFunction(()=>window.__nile.snapshot().nearest===0,null,{timeout:20000});await page.locator('#interact-button').click();for(let i=1;i<=3;i++)await page.getByRole('button',{name:'Water gate '+i}).click();await page.getByRole('button',{name:'The floodwater brought water and fertile silt.'}).click();await claim(0);assert.equal((await snap()).gems,210);passed('Replaying a mission cannot duplicate gems');
 report.performance=await snap();assert.equal(errors.length,0);assert.equal(badResponses.length,0);passed('No page errors or failed asset requests in complete desktop playthrough');
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push('mobile: '+e.message));await phone.goto(BASE_URL);await phone.waitForFunction(()=>window.__nile,null,{timeout:60000});await phone.waitForSelector('#loading',{state:'detached',timeout:60000});await phone.locator('#begin').click();if(await phone.locator('#controls-start').isVisible())await phone.locator('#controls-start').click();await phone.screenshot({path:'test-results/10-mobile.png'});assert.equal(await phone.locator('#joystick').isVisible(),true);await phone.locator('#guide').click();await phone.waitForFunction(()=>window.__nile.snapshot().nearest===0);await phone.locator('#interact-button').click();assert.equal(await phone.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth+2),true);await phone.screenshot({path:'test-results/11-mobile-mission.png'});await phone.getByRole('button',{name:'Close',exact:true}).click();await mobile.close();passed('Mobile layout, touch controls and mission dialog fit');
 report.ok=true;
}catch(e){report.ok=false;report.failure=e.stack;await shot('FAILURE');console.error(e);process.exitCode=1;}
finally{fs.writeFileSync('test-results/browser-report.json',JSON.stringify(report,null,2));await context.close();await browser.close();}
