import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const DIR='test-results/controls-qa',BASE=process.env.NILE_CONTROLS_URL||'http://127.0.0.1:4173/?game=nile';fs.mkdirSync(DIR,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});let page;
const checks=[],errors=[];
async function check(name,fn){try{await fn();checks.push({name,pass:true});console.log('PASS',name);}catch(e){checks.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);await page.screenshot({path:`${DIR}/failure-${checks.length}.png`}).catch(()=>{});}}
const snap=()=>page.evaluate(()=>window.__nile.snapshot());
const distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
async function load(context){page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);await page.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached'});}
async function begin(){await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();}
async function close(){if(await page.locator('dialog').isVisible())await page.keyboard.press('Escape');}
async function shot(name){await page.screenshot({path:`${DIR}/${name}.png`});}
// CDP touchEnd ends the gesture; touchMove with remaining active IDs lifts just the other finger.
// https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchTouchEvent
const touch=(cdp,type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({...p,radiusX:8,radiusY:8,force:1}))});
try{
 const desktop=await browser.newContext({viewport:{width:1440,height:900}});await load(desktop);await shot('01-final-landing');
 await check('Fresh desktop first use presents controls before movement',async()=>{await page.locator('#begin').click();await page.locator('#controls-start').waitFor();assert.ok(await page.locator('dialog').isVisible());const a=(await snap()).position;await page.keyboard.press('w');await page.waitForTimeout(300);assert.equal(distance((await snap()).position,a),0);await shot('02-first-use-controls');await page.locator('#controls-start').click();});
 await check('Persistent labelled Controls reopens keyboard help and returns focus',async()=>{await page.locator('#controls-help').click();assert.ok(await page.locator('dialog').isVisible());assert.match(await page.locator('dialog').innerText(),/W|arrow|keyboard/i);await close();assert.equal(await page.evaluate(()=>document.activeElement.id),'controls-help');});
 await check('Holding run into world boundary stops displacement and footstep animation',async()=>{await page.keyboard.down('Shift');await page.keyboard.down('a');await page.keyboard.down('s');await page.waitForTimeout(10000);const a=(await snap()).position;await page.waitForTimeout(500);assert.ok(distance(a,(await snap()).position)<.02,'Still travelling rather than against corner');assert.equal((await snap()).action,'Idle');assert.ok((await snap()).controls.speed<.14);await shot('boundary-stopped');await page.keyboard.up('Shift');await page.keyboard.up('a');await page.keyboard.up('s');});
 await check('Keyboard walk accelerates, Shift runs and release settles to Idle',async()=>{await page.keyboard.down('w');await page.waitForTimeout(650);const w=(await snap()).controls.speed;assert.ok(w>1&&w<4.5,`walk speed ${w}`);for(let i=0;i<4;i++){await page.waitForTimeout(85);await shot(`walk-contact-${i}`);}await page.keyboard.down('Shift');await page.waitForTimeout(600);assert.ok((await snap()).controls.speed>w+1);await shot('run-contact');await page.keyboard.up('Shift');await page.keyboard.up('w');await page.waitForTimeout(600);assert.equal((await snap()).action,'Idle');assert.ok((await snap()).controls.speed<.14);});
 await check('Look ahead restores default pitch and zoom after camera orbit',async()=>{await page.mouse.move(900,430);await page.mouse.down();await page.mouse.move(1040,460,{steps:10});await page.mouse.up();await page.mouse.wheel(0,350);await page.locator('#camera-reset').click();const c=(await snap()).controls;assert.ok(Math.abs(c.pitch-.18)<.001);assert.equal(c.zoom,11);assert.equal(c.camera.dragging,false);});
 await check('Modal and explicitly dispatched blur handler clear held motion',async()=>{await page.keyboard.down('s');await page.waitForTimeout(300);await page.locator('#controls-help').click();const a=(await snap()).position;await page.waitForTimeout(300);assert.equal(distance(a,(await snap()).position),0);await page.keyboard.up('s');await close();await page.keyboard.down('s');await page.waitForTimeout(200);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(350);const b=(await snap()).position;await page.waitForTimeout(350);assert.equal(distance(b,(await snap()).position),0);await page.keyboard.up('s');assert.equal((await snap()).controls.runEnabled,false);});
 await check('Returning player is not forced through first-use controls again',async()=>{await page.reload();await page.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached'});await page.locator('#begin').click();await page.waitForTimeout(200);assert.equal(await page.locator('#controls-start').isVisible(),false);});await desktop.close();
 for(const [width,height] of [[1024,768],[768,1024],[844,390]]){
  const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true});await load(context);await begin();await page.waitForTimeout(500);await shot(`tablet-${width}x${height}`);const cdp=await context.newCDPSession(page),r=await page.locator('#joystick').boundingBox(),joy={id:1,x:r.x+r.width/2,y:r.y+r.height/2};
  await check(`${width}x${height} thumb control is unobstructed and touch buttons are reachable`,async()=>{
   const layout=await page.evaluate(()=>{const j=document.querySelector('#joystick').getBoundingClientRect(),m=document.querySelector('.mission-panel').getBoundingClientRect();return{overlap:Math.min(j.right,m.right)>Math.max(j.left,m.left)&&Math.min(j.bottom,m.bottom)>Math.max(j.top,m.top),controls:['run-toggle','camera-reset','controls-help'].map(id=>{const b=document.getElementById(id),r=b.getBoundingClientRect();return{id,w:r.width,h:r.height,x:r.x,y:r.y,visible:r.width>0&&r.height>0};})};});assert.equal(layout.overlap,false,'Mission panel overlaps joystick');for(const b of layout.controls){assert.ok(b.visible&&b.w>=44&&b.h>=44,`${b.id} ${b.w}x${b.h}`);assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=width+1&&b.y+b.h<=height+1,`${b.id} offscreen`);}
  });
  await check(`${width}x${height} joystick centre has a deadzone and release stops`,async()=>{const a=(await snap()).position;await touch(cdp,'touchStart',[{...joy,x:joy.x+3}]);await page.waitForTimeout(600);await touch(cdp,'touchEnd',[]);assert.ok(distance(a,(await snap()).position)<.02);await touch(cdp,'touchStart',[{...joy,y:joy.y-35}]);await page.waitForTimeout(600);assert.ok(distance(a,(await snap()).position)>.6);await touch(cdp,'touchEnd',[]);await page.waitForTimeout(500);assert.ok((await snap()).controls.speed<.14);});
  await check(`${width}x${height} two-finger move and camera orbit operate independently`,async()=>{const second={id:2,x:width*.72,y:height*.56},a=(await snap()).position,angle=(await snap()).controls.cameraAngle;await touch(cdp,'touchStart',[{...joy,y:joy.y-35}]);await touch(cdp,'touchStart',[{...joy,y:joy.y-35},second]);for(let i=1;i<=8;i++){await touch(cdp,'touchMove',[{...joy,y:joy.y-35},{...second,x:second.x+i*9}]);await page.waitForTimeout(40);}assert.ok(Math.abs((await snap()).controls.cameraAngle-angle)>.1);assert.ok(distance(a,(await snap()).position)>.4);await touch(cdp,'touchMove',[{...joy,y:joy.y-35}]);const b=(await snap()).position;await page.waitForTimeout(300);assert.ok(distance(b,(await snap()).position)>.2,'Lifting look finger must not cancel thumb movement');await touch(cdp,'touchEnd',[]);await page.waitForTimeout(500);assert.ok((await snap()).controls.speed<.14);assert.equal((await snap()).controls.camera.dragging,false);});
  await check(`${width}x${height} Run toggle, touch cancel and blur cleanup agree with labels`,async()=>{await page.locator('#run-toggle').tap();assert.equal(await page.locator('#run-toggle').getAttribute('aria-pressed'),'true');await touch(cdp,'touchStart',[{...joy,y:joy.y-35}]);await page.waitForTimeout(550);assert.ok((await snap()).controls.speed>4);await touch(cdp,'touchCancel',[]);await page.waitForTimeout(500);assert.ok((await snap()).controls.speed<.14);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await snap()).controls.runEnabled,false);assert.equal(await page.locator('#run-toggle').getAttribute('aria-pressed'),'false');assert.deepEqual((await snap()).controls.analog,[0,0]);});
  await check(`${width}x${height} mission teaching portrait and controls fit enlarged text`,async()=>{await page.locator('#settings').click();await page.locator('[data-setting="largeText"]').check();await close();await page.locator('#guide').click();await page.waitForFunction(()=>window.__nile.snapshot().nearest===0,null,{timeout:22000});await page.locator('#interact-button').tap();assert.ok(await page.locator('.guide-character img').isVisible());assert.ok(await page.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth+2;}));await shot(`mission-${width}x${height}`);await close();});await context.close();
 }
}finally{fs.writeFileSync(`${DIR}/report.json`,JSON.stringify({at:new Date().toISOString(),base:BASE,checks,errors,limitations:'Chrome headless with CDP touch emulation. Blur dispatch tests cleanup handler, not physical OS/app-switch behavior. No real iPad certification or motion-capture quality claim.'},null,2));await browser.close();}
if(checks.some(c=>!c.pass)||errors.length)process.exitCode=1;
