import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const DIR='test-results/expert',BASE=process.env.NILE_QA_URL||'http://127.0.0.1:4173/?game=nile';fs.mkdirSync(DIR,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const results=[],errors=[];let page;
const snapshot=()=>page.evaluate(()=>window.__nile.snapshot());
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);await page?.screenshot({path:`${DIR}/failure-${results.length}.png`}).catch(()=>{});}}
async function load(p){page=p;page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));await page.goto(BASE);await page.waitForFunction(()=>typeof window.__nile?.snapshot==='function',null,{timeout:60000});await page.waitForSelector('#loading',{state:'detached'});}
async function close(){if(await page.locator('dialog').isVisible())await page.keyboard.press('Escape');}
async function travel(id,settle=false){await close();await page.locator('#map').click();await page.locator(`.map-list [data-go="${id}"]`).click();await page.waitForFunction(id=>window.__nile.snapshot().nearest===id,id,{timeout:18000});if(settle)await page.locator('#travel').waitFor({state:'hidden',timeout:18000});}
async function mission(id){await travel(id);await page.locator('#interact-button').click();}
async function claim(){await page.getByRole('button',{name:'Collect your discovery'}).click();await page.locator('#reward-next').click();}
if(process.env.NILE_QA_TARGETED==='1'){
 try{
  // Reuse only the genuine earned state from this test's complete playthrough.
  const c=await browser.newContext({storageState:`${DIR}/earned-progress.json`});await load(await c.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();
  await check('Museum keyboard progression focuses next question',async()=>{await mission(6);await page.getByRole('button',{name:'The Nile supported farming and travel.',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Choose a label for Tutankhamun’s tomb.');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'H3');await close();});
  await check('Return-check keyboard progression focuses next question',async()=>{await page.locator('#journal').click();await page.locator('#return-challenge').click();await page.getByRole('button',{name:'Land beside a water channel with fertile soil.',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'H3');assert.match(await page.evaluate(()=>document.activeElement.textContent),/18 baskets/);await close();});
  await c.close();
  const phone=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,isMobile:true,storageState:`${DIR}/earned-progress.json`});await load(await phone.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();await page.locator('#settings').click();await page.locator('[data-setting="largeText"]').check();await close();
  await check('320px larger-text cargo load and unload controls operate',async()=>{await mission(1);await page.getByRole('button',{name:'Load boat 3',exact:true}).tap();assert.equal(await page.locator('.cargo-count').nth(2).textContent(),'1');assert.equal(await page.locator('.equation').textContent(),'24 ÷ 3 = ?');await page.getByRole('button',{name:'Unload boat 3',exact:true}).tap();assert.equal(await page.locator('.cargo-count').nth(2).textContent(),'0');await close();});
  await check('320px larger-text timeline reorder control operates',async()=>{await mission(3);await page.getByRole('button',{name:'Move Tomb discovery later'}).tap();assert.match(await page.locator('.timeline-card').nth(1).textContent(),/Tomb discovery/);await close();});
  await check('320px larger-text accessible excavation brush reveals recording task',async()=>{await mission(5);await page.getByRole('button',{name:'Use the guided careful brush'}).tap();await page.getByRole('button',{name:'B2',exact:true}).tap();assert.ok(await page.getByRole('heading',{name:'Why record an object before moving it?'}).isVisible());await close();});await phone.close();
  const corrupt=await browser.newContext();await corrupt.addInitScript(()=>localStorage.setItem('schoolgle-nile-v1',JSON.stringify({version:1,completed:[],evidence:[{mission:0,objective:'Valid observation except correctness type',correct:'false',support:'none',at:'2026-09-06T09:00:00.000Z'}],settings:{},recall:{}})));await load(await corrupt.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();
  await check('Valid-timestamp string false observation is rejected',async()=>{assert.equal((await snapshot()).evidence.length,0);await page.locator('#journal').click();await page.locator('#progress-report').click();assert.equal(await page.locator('tbody tr').first().locator('td').nth(2).textContent(),'0');});await corrupt.close();
 }finally{fs.writeFileSync(`${DIR}/targeted-report.json`,JSON.stringify({checkedAt:new Date().toISOString(),base:BASE,results,errors},null,2));await browser.close();}
 process.exit(results.some(r=>!r.pass)?1:0);
}
try{
 const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});await load(await context.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();
 await check('Nested practice record restores keyboard focus to world journal',async()=>{await page.locator('#journal').click();await page.locator('#progress-report').click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'journal');});
 await check('Settings modal stops held keyboard movement and no stuck input after closing',async()=>{await page.keyboard.down('w');await page.waitForTimeout(300);await page.locator('#settings').click();const a=(await snapshot()).position;await page.waitForTimeout(500);assert.deepEqual((await snapshot()).position,a);await page.keyboard.up('w');await close();await page.waitForTimeout(350);assert.deepEqual((await snapshot()).position,a);});
 await check('Closed-dialog keyboard focus remains inside native modal when tab cycling',async()=>{await page.locator('#settings').click();for(let i=0;i<20;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('dialog')||document.activeElement===document.body),true);}await close();});
 await check('Manual keyboard input cancels guided travel and Stop remains effective',async()=>{await page.locator('#guide').click();await page.waitForTimeout(100);await page.keyboard.press('a');await page.locator('#travel').waitFor({state:'hidden'});await page.locator('#guide').click();await page.locator('#stop-guide').click();await page.locator('#travel').waitFor({state:'hidden'});const a=(await snapshot()).position;await page.waitForTimeout(350);assert.deepEqual((await snapshot()).position,a);});
 await check('Seven missions completed through real visible controls',async()=>{
  await mission(0);for(let i=1;i<=3;i++)await page.getByRole('button',{name:`Water gate ${i}`}).click();await page.getByRole('button',{name:'The floodwater brought water and fertile silt.'}).click();await claim();
  await mission(1);for(let i=0;i<8;i++)await page.getByRole('button',{name:'Share one to each boat'}).click();await page.getByRole('button',{name:'Check the cargo'}).click();await page.getByRole('button',{name:'3 groups of 8 use all 24 baskets.',exact:true}).click();await claim();
  await mission(2);await page.getByRole('button',{name:'It needs water from the channel.'}).click();await page.getByRole('button',{name:'The second field is dry, beyond the channel.'}).click();await claim();
  await mission(3);for(let i=0;i<2;i++)await page.getByRole('button',{name:'Move Tomb discovery later'}).click();await page.getByRole('button',{name:'Set the timeline'}).click();await claim();
  await mission(4);await page.getByRole('button',{name:'Larger',exact:true}).click();await page.locator('#shadow-distance').focus();await page.keyboard.press('Home');for(let i=0;i<25;i++)await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Open the chamber',exact:true}).click();await page.getByRole('button',{name:'Nearer the lamp made the shadow larger.',exact:true}).click();await claim();
  await mission(5);await page.getByRole('button',{name:'Use the guided careful brush'}).click();await page.getByRole('button',{name:'B2',exact:true}).click();await page.getByRole('button',{name:'Its position can help explain how it was used.'}).click();await claim();
  await mission(6);for(let t of ['The Nile supported farming and travel.','His tomb was in the Valley of the Kings.','Egyptian workers were essential to Carter’s excavation team.','…its position is part of the evidence.'])await page.getByRole('button',{name:t,exact:true}).click();await claim();assert.equal((await snapshot()).gems,210);await close();
 });
 if((await snapshot()).completed.length===7){
  await context.storageState({path:`${DIR}/earned-progress.json`});
  // Every ordered pair: authentic earned progress; no teleport or injected completions.
  for(let from=0;from<7;from++)for(let to=0;to<7;to++)if(from!==to)await check(`Guided route ${from+1} to ${to+1} reaches destination and stops`,async()=>{await travel(from,true);await travel(to,true);});
  await page.screenshot({path:`${DIR}/world-final.png`});
  await check('Reset cancels safely and keeps earned evidence',async()=>{await page.locator('#settings').click();await page.locator('#reset').click();await page.getByRole('button',{name:'Keep my expedition'}).click();assert.equal((await snapshot()).gems,210);});
  const mobile=await browser.newContext({viewport:{width:320,height:568},isMobile:true,hasTouch:true,storageState:`${DIR}/earned-progress.json`});await load(await mobile.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();await page.locator('#settings').click();await page.locator('[data-setting="largeText"]').check();await close();
  for(let id of [0,1,3,4,5,6])await check(`320px large text mission ${id+1} fits and controls reachable`,async()=>{await mission(id);assert.ok(await page.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth+2;}),'Dialog has horizontal content overflow');const targets=await page.locator('#activity button').all();for(const b of targets)if(await b.isEnabled()){await b.scrollIntoViewIfNeeded();const box=await b.boundingBox();assert.ok(box.x>=0&&box.x+box.width<=321,'Activity control clipped horizontally');}await page.screenshot({path:`${DIR}/mobile-mission-${id+1}.png`});await close();});
  await mobile.close();
 }
 await context.close();
 const corrupt=await browser.newContext();await corrupt.addInitScript(()=>{localStorage.setItem('schoolgle-nile-v1',JSON.stringify({version:1,completed:[],position:[-85,85],evidence:[{mission:0,objective:'x',correct:'false',support:{unexpected:true}}],recall:[],settings:{}}));});await load(await corrupt.newPage());await page.locator('#begin').click();if(await page.locator('#controls-start').isVisible())await page.locator('#controls-start').click();
 await check('Invalid saved position normalised before play',async()=>{const [x,z]=(await snapshot()).position;assert.ok(x>=-6&&x<=88&&z>=-78&&z<=66,`Out-of-bounds starting position ${x},${z}`);});
 await check('Malformed correctness cannot appear as a correct answer',async()=>{await page.locator('#journal').click();await page.locator('#progress-report').click();const cells=await page.locator('tbody tr').first().locator('td').allTextContents();assert.equal(cells[2],'0');});await corrupt.close();
 const failed=await browser.newContext();page=await failed.newPage();await page.route('**/models/curator.glb',r=>r.fulfill({status:404,body:'Missing for resilience check'}));await page.goto(BASE);await check('Missing non-player asset fails visibly with recovery button',async()=>{await page.getByRole('heading',{name:'One of our expedition assets could not load.'}).waitFor();assert.ok(await page.getByRole('button',{name:'Reload',exact:true}).isVisible());});await failed.close();
}finally{fs.writeFileSync(`${DIR}/report.json`,JSON.stringify({checkedAt:new Date().toISOString(),base:BASE,results,errors,limits:'Desktop Chrome headless with touch emulation; not real device, screen-reader, pupil or statutory accessibility certification.'},null,2));await browser.close();}
if(results.some(r=>!r.pass))process.exitCode=1;
