import {completeStreetInvestigation} from './fire-investigation-flow.mjs';
import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const DIR=process.env.FIRE_QA_DIR||'test-results/fire',URL=process.env.FIRE_QA_URL||'http://127.0.0.1:4173/?game=fire&demo=1';fs.mkdirSync(DIR,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,acceptDownloads:true,reducedMotion:'reduce'});
const page=await context.newPage();let active=page;const report={at:new Date().toISOString(),url:URL,checks:[],errors:[],failedRequests:[],skipped:[]};
function watch(p){p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.failedRequests.push(`${r.status()} ${r.url()}`);});}watch(page);
await page.routeWebSocket('**',ws=>{if(ws.protocols().includes('vite-hmr'))ws.send('{"type":"connected"}');else ws.connectToServer();});
const normal=JSON.stringify({version:1,completed:[],attempts:[],started:false,settings:{character:'explorer-girl'}});
await context.addInitScript(value=>{if(localStorage.getItem('schoolgle-great-fire-v1')===null)localStorage.setItem('schoolgle-great-fire-v1',value);},normal);
// Keep the old flag as an alias; observe the real media API without replacing playback.
const captureNarration=process.env.FIRE_CAPTURE_NARRATION==='1'||process.env.FIRE_CAPTURE_SPEECH==='1';
if(captureNarration)await context.addInitScript(()=>{window.__qaNarration=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){const event={kind:'recording',src:this.currentSrc||this.src,status:'requested'};if(this.tagName==='AUDIO')window.__qaNarration.push(event);const result=play.apply(this,args);result?.then(()=>{event.status='playing';},error=>{event.status=error.name;});return result;};if(window.speechSynthesis){const speak=window.speechSynthesis.speak.bind(window.speechSynthesis);window.speechSynthesis.speak=u=>{window.__qaNarration.push({kind:'fallback',text:u.text});return speak(u);};}});
const snap=()=>page.evaluate(()=>window.__fire.snapshot()),choice=i=>page.locator(`[data-choice="${i}"]`).click();
const pass=s=>{report.checks.push(s);console.log('PASS',s);};
const pending=async n=>{assert.equal((await snap()).gems,n*20);assert.equal(await page.locator('#fire-next').count(),0);};
const earned=async n=>{assert.deepEqual((await snap()).completed,Array.from({length:n+1},(_,i)=>i));assert.equal((await snap()).gems,(n+1)*20);await page.screenshot({path:`${DIR}/discovery-${n+1}-complete.png`});await page.locator('#fire-next').click();if(n===4){assert.equal(await page.locator('#fire-exhibition-host').isVisible(),true);await page.screenshot({path:`${DIR}/final-exhibition.png`});await page.keyboard.press('Escape');await page.locator('#fire-teachers').click();}};
try{
 await page.goto(URL);await page.waitForFunction(()=>window.__fire);assert.deepEqual((await snap()).completed,[]);assert.equal((await snap()).attempts.length,0);assert.equal((await snap()).gems,0);assert.equal(await page.locator('#fire-world canvas').count(),1);await page.screenshot({path:`${DIR}/entry-desktop.png`});await page.locator('#fire-teachers').click();assert.equal(await page.locator('#fire-return').count(),0);await page.keyboard.press('Escape');await page.locator('#fire-start').click();for(let i=1;i<5;i++)assert.equal(await page.locator(`[data-chapter="${i}"]`).isDisabled(),true);pass('3D1666 scene loads; fresh Alex cannot open future discoveries or return recall');
 if(process.env.FIRE_CHECK_MOVEMENT==='1'){await page.waitForFunction(()=>__fire.snapshot().explorer?.loaded&&__fire.snapshot().explorer.arrived);const learning=s=>({chapter:s.chapter,stage:s.stage,draft:s.draft,completed:s.completed,attempts:s.attempts,gems:s.gems});const before=await snap();await page.locator('#fire-walk-focus').click();await page.locator('#fire-world').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(400);await page.keyboard.up('ArrowRight');const after=await snap();assert.ok(Math.hypot(after.explorer.position[0]-before.explorer.position[0],after.explorer.position[2]-before.explorer.position[2])>.1);assert.deepEqual(learning(after),learning(before));await page.screenshot({path:`${DIR}/first-task-movement.png`});pass('Real movement during the fresh first task changes position without submitting answers or awarding gems');}
 await page.locator('#fire-comfort').click();await page.locator('[name="fire-character"][value="explorer-girl"]').check();await page.locator('#fire-motion').check();await page.keyboard.press('Escape');assert.equal((await snap()).settings.character,'explorer-girl');await page.locator('#fire-listen').click();await page.locator('#fire-hint').click();await page.locator('#map-cathedral').click();await pending(0);await page.locator('#map-bakery').focus();await page.keyboard.press('Enter');await choice(0);await pending(0);await choice(1);await earned(0);pass('Place and date both required; wrong map/date choices prompt correction; keyboard and reading support work');
 await completeStreetInvestigation(page,{beforeGems:20,screenshotDir:DIR});await earned(1);pass('Prediction, model comparison, explanation and new-layout transfer required; wrong plans and corrections preserved');
 assert.equal(await page.locator('#source-compare').isDisabled(),true);await page.locator('[data-source="diary"]').click();assert.match(await page.locator('#source-text').innerText(),/modern summary/i);assert.equal(await page.locator('#source-compare').isDisabled(),true);await page.locator('[data-source="glass"]').click();await page.locator('#source-compare').click();await choice(1);await pending(2);await choice(0);await pending(2);await choice(0);await pending(2);await choice(2);await earned(2);pass('Both historical sources required; claims about thoughts/identity rejected; supported diary and heat inferences accepted');
 for(const id of ['rebuild','start','escape'])await page.locator(`[data-event="${id}"]`).click();await page.locator('#timeline-check').click();await pending(3);for(let i=0;i<3;i++)await page.locator('#timeline-undo').click();for(const id of ['start','escape','rebuild'])await page.locator(`[data-event="${id}"]`).click();await page.locator('#timeline-check').click();await choice(2);await pending(3);await choice(1);await earned(3);pass('Timeline must be submitted correctly and linked to people moving possessions; undo remains unassessed');
 assert.equal(await page.locator('#place-wall').isDisabled(),true);await page.locator('#material-timber').click();for(let i=0;i<3;i++)await page.locator('#place-wall').click();await page.locator('#check-house').click();await pending(4);await page.locator('#material-brick').click();assert.equal((await snap()).draft.walls,0);for(let i=0;i<3;i++)await page.locator('#place-wall').tap();assert.equal(await page.locator('#place-wall').isDisabled(),true);await page.locator('#check-house').click();await choice(0);await pending(4);await choice(2);await pending(4);pass('Wall model requires selection and three placements; timber rejected and model reset for correct rebuilding rule');
 await page.locator('#fire-final-recall').click();await page.locator('[data-recall="1"]').click();assert.equal((await snap()).gems,80);assert.ok(await page.locator('#fire-recall-help').innerText());await page.keyboard.press('Escape');await pending(4);await page.locator('#fire-final-recall').click();assert.match(await page.locator('#fire-dialog-body').innerText(),/Question 1 of 3/);for(const i of [0,1])await page.locator(`[data-recall="${i}"]`).click();await page.keyboard.press('Escape');await pending(4);await page.locator('#fire-final-recall').click();for(const i of [0,1,1])await page.locator(`[data-recall="${i}"]`).click();assert.equal((await snap()).gems,80);await page.locator('#fire-recall-done').click();await earned(4);pass('Closing final recall early cannot complete chapter; all three recalled ideas and explicit collection required for100gems');
 assert.match(await page.locator('#fire-dialog-body').innerText(),/does not assess maths/);assert.equal(await page.locator('.fire-table tbody tr').count(),5);await page.locator('#fire-return').click();await page.locator('[data-recall="2"]').click();await page.locator('#fire-recall-read').click();for(const i of [0,1,1])await page.locator(`[data-recall="${i}"]`).click();await page.locator('#fire-recall-done').click();assert.equal(await page.locator('#fire-exhibition-host').isVisible(),true);await page.keyboard.press('Escape');await page.locator('#fire-teachers').click();assert.equal((await snap()).gems,100);const completed=await snap();assert.ok(completed.attempts.some(a=>a.kind==='recall'&&!a.correct));assert.ok(completed.attempts.some(a=>a.kind==='recall'&&a.correct&&a.help.includes('corrective feedback on this question')));assert.ok(completed.attempts.some(a=>a.kind==='recall'&&a.help.includes('read aloud')));pass('Separate return practice retains wrong answer, correction, read-aloud and elapsed context without extra gems');
 await page.getByText('Inspect actual responses and help used',{exact:true}).click();const dp=page.waitForEvent('download');await page.locator('#fire-export').click();await(await dp).saveAs(`${DIR}/alex-casebook.json`);const record=JSON.parse(fs.readFileSync(`${DIR}/alex-casebook.json`));assert.equal(record.learner.id,'fictional-alex');assert.equal(record.learner.fictional,true);assert.deepEqual(record.attempts,completed.attempts);assert.ok(record.attempts.filter(a=>a.kind==='observation').every(a=>a.correct===null));await page.screenshot({path:`${DIR}/alex-casebook.png`});await context.storageState({path:`${DIR}/alex-earned.json`});pass('Teacher table and downloaded fictional Alex casebook match every actual response and neutral action');
 if(captureNarration)report.narration=await page.evaluate(()=>window.__qaNarration);
 await page.reload();await page.waitForFunction(()=>window.__fire);assert.equal((await snap()).gems,100);assert.deepEqual((await snap()).attempts,completed.attempts);assert.equal(await page.evaluate(()=>localStorage.getItem('schoolgle-great-fire-v1')),normal);await page.locator('[data-chapter="0"]').click();await page.locator('#map-bakery').click();await choice(1);assert.equal((await snap()).gems,100);pass('Reload preserves completed story and actual evidence; replay cannot duplicate gems; normal Fire save unchanged');
 await page.locator('[data-chapter="1"]').click();await page.setViewportSize({width:768,height:1024});await page.waitForTimeout(350);await page.screenshot({path:`${DIR}/tablet768.png`});await page.setViewportSize({width:320,height:740});await page.locator('#fire-comfort').click();await page.locator('#fire-text').check();await page.keyboard.press('Escape');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:`${DIR}/mobile320.png`});await page.locator('#fire-teachers').click();assert.ok(await page.locator('#fire-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2));await page.locator('#fire-return').tap();assert.ok(await page.locator('#fire-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2));await page.screenshot({path:`${DIR}/recall320.png`});pass('768px tablet and320px larger-text world, teacher dialog and recall fit; touch actions work');
 if(process.env.FIRE_SKIP_RESILIENCE==='1')report.skipped.push('Existing malformed-save/blocked-storage/WebGL resilience scenarios omitted; this run uses no seeded completions and focuses on the complete live journey.');
 for(const mode of process.env.FIRE_SKIP_RESILIENCE==='1'?[]:['malformed','storage','webgl']){const c=await browser.newContext();const p=await c.newPage();active=p;watch(p);
  if(mode==='storage')await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('QA blocked storage','SecurityError');};});
  if(mode==='webgl')await p.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...a){return /webgl/.test(type)?null:get.call(this,type,...a);};});
  if(mode==='malformed')await p.addInitScript(()=>localStorage.setItem('schoolgle-great-fire-v1-demo-alex',JSON.stringify({version:1,started:true,completed:[0,4],attempts:[{chapter:0,kind:'response',correct:false,at:'2026-09-07T09:00:00Z',question:'<img data-injected src=x onerror=window.__bad=true>',response:'<script>bad</script>',help:{malformed:1}},{chapter:99,kind:'recall',correct:true,at:'bad'}]})));
  await p.goto(URL);await p.waitForFunction(()=>window.__fire);
  if(mode==='malformed'){const restored=await p.evaluate(()=>window.__fire.snapshot());assert.deepEqual(restored.completed,[0]);assert.equal(restored.attempts.length,1);assert.deepEqual(restored.attempts[0].help,[]);await p.locator('#fire-teachers').click();await p.getByText('Inspect actual responses and help used',{exact:true}).click();assert.equal(await p.locator('[data-injected]').count(),0);assert.equal(await p.evaluate(()=>window.__bad),undefined);assert.match(await p.locator('#fire-dialog-body').innerText(),/<img data-injected/);pass('Malformed saved help/chapters recover safely and responses cannot inject teacher HTML');}
  else{await p.locator('#fire-start').click();await p.locator('#map-bakery').click();assert.equal(await p.evaluate(()=>window.__fire.snapshot().stage),1);if(mode==='storage')assert.equal(await p.locator('#fire-storage').isVisible(),true);else assert.equal(await p.locator('.fire-fallback').isVisible(),true);pass(mode==='storage'?'Blocked storage warns while task controls remain usable':'Unavailable WebGL gives an explicit fallback while tasks remain usable');}await c.close();
 }
 if(captureNarration){report.narration=[...(report.narration||[]),...await page.evaluate(()=>window.__qaNarration)];assert.ok(report.narration.some(e=>e.kind==='recording'&&/\/audio\/voices\/fire-[^/]+\.mp3$/.test(new URL(e.src).pathname)),'Read-aloud requests an actual prerecorded Fire MP3');assert.equal(report.narration.filter(e=>e.kind==='fallback').length,0,'Covered story and recall should use recordings');report.skipped.push('Real Audio.play requests observed without mocking playback; this fast journey does not establish audible pronunciation or full-clip quality. Separate recording QA covers decoding/playback.');}
 const final=await snap();report.final={completed:final.completed,gems:final.gems,attemptCount:final.attempts.length};assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);pass('No browser exceptions or failed requests across the exercised Fire journey');report.ok=true;
}catch(e){report.ok=false;report.failure=e.stack;console.error(e);await active.screenshot({path:`${DIR}/FAILURE.png`}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(`${DIR}/report.json`,JSON.stringify(report,null,2));await context.close();await browser.close();}
