import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';
const DIR=process.env.NARRATION_QA_DIR||'test-results/narration-player';fs.mkdirSync(DIR,{recursive:true});
let source=fs.readFileSync('src/narration.js','utf8').replace(/^import[^\n]+\n/gm,'').replace(/const banks=import\.meta\.glob\([^\n]+\);/,`const ASSET_BASE='/assets/';const banks={'./narration/fire-audio.json':[{text:'Recorded story',file:'story.mp3'}]};`).replaceAll('export ','');
const browser=await chromium.launch({channel:'chrome',headless:true});const report={checks:[],failures:[],errors:[]};
async function check(name,fn){const page=await browser.newPage();page.on('pageerror',e=>report.errors.push(e.message));try{await page.setContent('<button id="read">Read story</button><dialog><button id="modal-read">Read question</button></dialog>');await page.addScriptTag({content:`window.audioInstances=[];window.spoken=[];window.speechCalls=[];window.Audio=class{constructor(src){this.src=src;this.requests=[];this.pauseCalls=0;audioInstances.push(this);}play(){return new Promise((resolve,reject)=>this.requests.push({resolve,reject}));}pause(){this.pauseCalls++;}};window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{speak:u=>spoken.push(u),cancel:()=>speechCalls.push('cancel'),pause:()=>speechCalls.push('pause'),resume:()=>speechCalls.push('resume'),getVoices:()=>[]}});`+source+';window.narrator=createNarrator("fire");'});await fn(page);report.checks.push(name);console.log('PASS '+name);}catch(e){report.failures.push({name,message:e.message});console.log('FAIL '+name+': '+e.message);}finally{await page.close();}}
try{
await check('Recorded audio resolves, pauses, resumes and ends cleanly',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.evaluate(()=>audioInstances[0].requests[0].resolve());assert.match(await p.locator('.worlds-narration').innerText(),/Guide reading/);await p.getByRole('button',{name:'Pause voice',exact:true}).click();await p.getByRole('button',{name:'Resume voice',exact:true}).click();await p.evaluate(()=>audioInstances[0].requests[1].resolve());await p.evaluate(()=>audioInstances[0].onended());assert.equal(await p.locator('.worlds-narration').count(),0);assert.equal(await p.evaluate(()=>spoken.length),0);});
await check('An error event plus rejected play produces one fallback, not two',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.evaluate(()=>{const a=audioInstances[0];a.onerror();a.requests[0].reject(new DOMException('broken','NotSupportedError'));});assert.equal(await p.evaluate(()=>spoken.length),1);});
await check('Pause while loading does not start fallback after intentional AbortError',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.getByRole('button',{name:'Pause voice',exact:true}).click();await p.evaluate(()=>audioInstances[0].requests[0].reject(new DOMException('paused','AbortError')));assert.equal(await p.evaluate(()=>spoken.length),0);assert.equal(await p.getByRole('button',{name:'Resume voice',exact:true}).count(),1);});
await check('A stopped or superseded request cannot restart narration',async p=>{await p.evaluate(()=>{narrator.speak('Recorded story');window.oldError=audioInstances[0].onerror;narrator.speak('Fallback question');oldError();audioInstances[0].requests[0].reject(new Error('late'));});assert.deepEqual(await p.evaluate(()=>spoken.map(u=>u.text)),['Fallback question']);await p.evaluate(()=>narrator.stop());assert.equal(await p.locator('.worlds-narration').count(),0);});
await check('Device fallback pauses/resumes and ends; missing speech API stays readable',async p=>{await p.evaluate(()=>narrator.speak('Fallback question'));await p.getByRole('button',{name:'Pause voice',exact:true}).click();await p.getByRole('button',{name:'Resume voice',exact:true}).click();assert.deepEqual(await p.evaluate(()=>speechCalls),['pause','resume']);await p.evaluate(()=>spoken[0].onend());assert.equal(await p.locator('.worlds-narration').count(),0);await p.evaluate(()=>{delete window.speechSynthesis;narrator.speak('No voice');});assert.match(await p.locator('.worlds-narration').innerText(),/unavailable/);});
await check('Stop returns dock focus to the invoking button; modal close cancels audio',async p=>{await p.locator('#read').focus();await p.evaluate(()=>narrator.speak('Recorded story'));await p.getByRole('button',{name:'Stop voice',exact:true}).click();assert.equal(await p.evaluate(()=>document.activeElement.id),'read');await p.evaluate(()=>{document.querySelector('dialog').showModal();document.querySelector('#modal-read').focus();narrator.speak('Recorded story');});assert.equal(await p.locator('dialog .worlds-narration').count(),1);await p.evaluate(()=>document.querySelector('dialog').close());await p.waitForFunction(()=>!document.querySelector('.worlds-narration'));assert.equal(await p.evaluate(()=>audioInstances[1].pauseCalls>0),true);});
await check('Cross-world narration and pagehide leave one active speaker',async p=>{await p.evaluate(()=>{narrator.speak('Recorded story');window.second=createNarrator('plot');second.speak('Another world');});assert.equal(await p.evaluate(()=>audioInstances[0].pauseCalls>0),true);assert.equal(await p.locator('.worlds-narration').count(),1);await p.evaluate(()=>dispatchEvent(new Event('pagehide')));assert.equal(await p.locator('.worlds-narration').count(),0);});
await check('Failed resume cannot change a newer recording or leave duplicate fallback',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.evaluate(()=>audioInstances[0].requests[0].resolve());await p.getByRole('button',{name:'Pause voice',exact:true}).click();await p.getByRole('button',{name:'Resume voice',exact:true}).click();await p.evaluate(()=>{narrator.speak('Fallback question');audioInstances[0].requests[1].reject(new Error('late resume'));});assert.deepEqual(await p.evaluate(()=>spoken.map(u=>u.text)),['Fallback question']);assert.match(await p.locator('.worlds-narration').innerText(),/Device voice/);});
await check('Autoplay denial stays silent and offers an explicit retry',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.evaluate(()=>audioInstances[0].requests[0].reject(new DOMException('gesture needed','NotAllowedError')));assert.equal(await p.evaluate(()=>spoken.length),0);assert.match(await p.locator('.worlds-narration').innerText(),/Playback blocked/);await p.getByRole('button',{name:'Resume voice',exact:true}).click();await p.evaluate(()=>audioInstances[0].requests[1].resolve());assert.match(await p.locator('.worlds-narration').innerText(),/Guide reading/);});
await check('A real resume failure falls back once; a prior paused speech queue is resumed',async p=>{await p.evaluate(()=>narrator.speak('Recorded story'));await p.evaluate(()=>audioInstances[0].requests[0].resolve());await p.getByRole('button',{name:'Pause voice',exact:true}).click();await p.getByRole('button',{name:'Resume voice',exact:true}).click();await p.evaluate(()=>audioInstances[0].requests[1].reject(new Error('decoder failed')));assert.equal(await p.evaluate(()=>spoken.length),1);await p.evaluate(()=>{narrator.stop();speechSynthesis.paused=true;narrator.speak('Fresh fallback');});assert.equal(await p.evaluate(()=>speechCalls.at(-1)),'resume');assert.equal(await p.evaluate(()=>spoken.at(-1).text),'Fresh fallback');});
}finally{await browser.close();report.ok=!report.failures.length&&!report.errors.length;fs.writeFileSync(DIR+'/report.json',JSON.stringify(report,null,2)+'\n');}if(!report.ok)process.exitCode=1;
