import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const ORIGIN=process.env.WORLDS_TEST_ORIGIN||'http://127.0.0.1:4173',DIR='test-results/plot';
fs.mkdirSync(DIR,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const seed='test-results/independent-learning/cargo-earned.json';
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce',...(fs.existsSync(seed)?{storageState:seed}:{})});
const page=await context.newPage();page.setDefaultTimeout(15000);let active=page;
const report={at:new Date().toISOString(),checks:[],errors:[],failedRequests:[],notes:[]};
const smokeOnly=process.env.PLOT_QA_SMOKE_ONLY==='1';
function listen(p){p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.failedRequests.push(`${r.status()} ${r.url()}`);});}
listen(page);await page.routeWebSocket('**',ws=>{if(ws.protocols().includes('vite-hmr'))ws.send('{"type":"connected"}');else ws.connectToServer();});
const snap=()=>page.evaluate(()=>window.__plot.snapshot());
async function enterWardrobeIfNeeded(p){if(await p.locator('#wardrobe-enter').isVisible()){await p.locator('[data-wear=doublet]').click();await p.locator('#wardrobe-enter').click();}}
const click=text=>page.getByRole('button',{name:text,exact:true}).click();
const visit=i=>page.locator(`[data-visit="${i}"]`).click();
const answer=i=>page.locator(`[data-answer="${i}"]`).click();
const pass=s=>{report.checks.push(s);console.log('PASS',s);};
async function pending(i){const s=await snap();assert.equal(s.completed.includes(i),false);assert.equal(s.gems,i*20);assert.equal(await page.locator('#plot-next').count(),0);}
async function earned(i){const s=await snap();assert.equal(s.gems,(i+1)*20);assert.deepEqual(s.completed,Array.from({length:i+1},(_,n)=>n));if(i<4)await page.locator('#plot-next').click();pass(`Chapter${i+1} rewards20gems only after all its required stages`);}
async function resilience(){
 for(const mode of ['storage','webgl']){const c=await browser.newContext();const p=await c.newPage();active=p;listen(p);if(mode==='storage')await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Synthetic blocked storage','SecurityError');};});else await p.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});await p.goto(`${ORIGIN}/?game=plot`);await p.waitForFunction(()=>window.__plot);await p.locator('#plot-start').click();await enterWardrobeIfNeeded(p);await p.locator('[data-answer="0"]').click();assert.deepEqual(await p.evaluate(()=>window.__plot.snapshot().draft.roles),[0]);if(mode==='storage'){assert.equal(await p.locator('#plot-save-warning').isVisible(),true);pass('BlockedlocalStorage gives an explicit save warning while learning controls remain usable');}else{assert.equal(await p.locator('.plot-world-fallback').isVisible(),true);pass('UnavailableWebGL shows the declared fallback and keeps investigation tasks usable');}await c.close();}
}
try{
 if(smokeOnly){await page.goto(`${ORIGIN}/?game=nile`);await page.waitForFunction(()=>window.__nile&&!document.querySelector('#loading'),null,{timeout:60000});await page.locator('.brand').click();await page.getByRole('link',{name:'Play The Midnight Letter',exact:true}).waitFor();pass('Nile brand now navigates to the world selector');await page.getByRole('link',{name:'Play The Midnight Letter',exact:true}).click();await page.waitForFunction(()=>window.__plot);await page.locator('#plot-start').click();await enterWardrobeIfNeeded(page);await page.screenshot({path:`${DIR}/final-people-desktop.png`});assert.equal(await page.locator('.plot-people-strip svg').count(),3);await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(350);await page.screenshot({path:`${DIR}/final-tablet1024.png`});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));pass('Latest illustrated people task and1024tablet scene render without horizontal overflow');await resilience();assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);report.ok=true;}else{
 await page.goto(ORIGIN);const nileBefore=await page.evaluate(()=>localStorage.getItem('schoolgle-nile-v1'));assert.equal(await page.getByRole('link',{name:'Play Nile Quest',exact:true}).count(),1);await page.getByRole('link',{name:'Play The Midnight Letter',exact:true}).click();await page.waitForFunction(()=>window.__plot);assert.equal(await page.locator('#plot-world canvas').count(),1);await page.screenshot({path:`${DIR}/desktop-entry.png`});pass('Root world selector opens a separate rendered3D London investigation');
 await page.locator('[data-character="explorer-girl"]').click();await page.locator('#plot-start').click();await enterWardrobeIfNeeded(page);assert.equal((await snap()).settings.character,'explorer-girl');for(let i=1;i<5;i++)assert.equal(await page.locator(`[data-visit="${i}"]`).isDisabled(),true);pass('Character selection persists and four future chapters are locked');
 await page.locator('#plot-listen').click();await page.locator('#plot-stop').click();await answer(1);await pending(0);await answer(0);await pending(0);await answer(2);await answer(1);await pending(0);await answer(2);await earned(0);pass('People must distinguish king, leader and Fawkes; wrong role cannot unlock');
 assert.equal(await page.locator('[data-line]').count(),0);await page.locator('#plot-seal').click();await page.locator('[data-line="0"]').click();await pending(1);const partial=(await snap()).attempts;await page.reload();await page.waitForFunction(()=>window.__plot);assert.equal((await snap()).gems,20);assert.deepEqual((await snap()).attempts,partial);await page.locator('#plot-start').click();await enterWardrobeIfNeeded(page);assert.equal(await page.locator('#plot-seal').count(),1);await page.locator('#plot-seal').click();await page.locator('[data-line="1"]').click();await pending(1);await answer(0);await pending(1);await answer(1);await earned(1);pass('Letter requires seal, relevant warning line and uncertainty judgement; unfinished task restarts but evidence survives reload');
 assert.equal(await page.locator('#plot-connect').isDisabled(),true);await page.locator('[data-clue="0"]').click();const one=(await snap()).attempts.length;await page.locator('[data-clue="0"]').click();assert.equal((await snap()).attempts.length,one);await page.locator('[data-clue="2"]').click();assert.equal(await page.locator('#plot-connect').isDisabled(),true);await page.locator('[data-clue="1"]').click();await page.locator('#plot-connect').click();await pending(2);await answer(2);await pending(2);await answer(1);await earned(2);pass('Search requires three distinct inspections plus supported inference; repeated clue does not count twice');
 for(const id of ['opening','warning','search'])await page.locator(`[data-event="${id}"]`).click();await page.locator('#plot-check-order').click();await pending(3);for(let n=0;n<3;n++)await page.locator('#plot-undo').click();for(const id of ['warning','search','opening'])await page.locator(`[data-event="${id}"]`).click();await page.locator('#plot-check-order').click();await pending(3);await answer(2);await pending(3);await answer(0);await earned(3);pass('Timeline requires correct submitted order and causal explanation, with Undo correction available');
 await answer(1);await pending(4);await answer(0);await pending(4);await answer(1);await pending(4);await answer(0);await pending(4);await answer(0);await pending(4);await answer(1);await earned(4);pass('Remembrance distinguishes rhyme from eyewitness evidence, checks recall and requires accurate final account');
 const full=await snap();report.attempts=full.attempts.length;assert.ok(full.attempts.filter(a=>a.correct===false).length>=9);await page.locator('#plot-casebook').click();await page.getByText('Responses and help used',{exact:true}).click();assert.match(await page.locator('#plot-dialog').innerText(),/does not assess maths/);const dp=page.waitForEvent('download');await page.locator('#plot-export').click();const dl=await dp;await dl.saveAs(`${DIR}/casebook.json`);const exported=JSON.parse(fs.readFileSync(`${DIR}/casebook.json`,'utf8'));assert.deepEqual(exported.attempts,full.attempts);await page.screenshot({path:`${DIR}/casebook.png`});await page.keyboard.press('Escape');pass('Casebook/export retains actual wrong and corrected responses and states its limited learning scope');
 await page.reload();await page.waitForFunction(()=>window.__plot);assert.equal((await snap()).gems,100);await page.locator('#plot-start').click();await enterWardrobeIfNeeded(page);await visit(0);for(const n of [0,1,2])await answer(n);assert.equal((await snap()).gems,100);assert.equal((await snap()).completed.length,5);await context.storageState({path:`${DIR}/earned-plot.json`});pass('Five completions persist; replay never duplicates gems');
 const nileAfter=await page.evaluate(()=>localStorage.getItem('schoolgle-nile-v1'));assert.equal(nileAfter,nileBefore);await page.locator('.plot-home').click();await page.getByRole('link',{name:'Play Nile Quest',exact:true}).click();await page.waitForFunction(()=>window.__nile&&!document.querySelector('#loading'),null,{timeout:60000});if(nileBefore){assert.deepEqual(await page.evaluate(()=>window.__nile.snapshot().completed),JSON.parse(nileBefore).completed);}await page.goto(`${ORIGIN}/?view=teachers`);await page.waitForFunction(()=>window.__nile&&!document.querySelector('#loading'),null,{timeout:60000});pass('Plot save is independent of Nile; root selector and legacyteachers route still open Nile');
 const mobile=await browser.newContext({viewport:{width:320,height:740},isMobile:true,hasTouch:true,storageState:`${DIR}/earned-plot.json`,reducedMotion:'reduce'});const m=await mobile.newPage();active=m;listen(m);await m.goto(`${ORIGIN}/?game=plot`);await m.waitForFunction(()=>window.__plot);await m.locator('#plot-start').click();await enterWardrobeIfNeeded(m);await m.locator('#plot-comfort').click();await m.locator('#plot-large').check();await m.locator('#plot-comfort-done').click();await m.locator('[data-visit="1"]').tap();await m.locator('#plot-seal').focus();await m.keyboard.press('Enter');await m.locator('[data-line="1"]').tap();await m.locator('[data-answer="1"]').focus();await m.keyboard.press('Space');assert.equal(await m.evaluate(()=>window.__plot.snapshot().gems),100);await m.locator('[data-visit="2"]').tap();for(const n of [0,1,2])await m.locator(`[data-clue="${n}"]`).tap();assert.equal(await m.locator('#plot-connect').isEnabled(),true);assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await m.screenshot({path:`${DIR}/mobile320-large.png`});await m.setViewportSize({width:1024,height:768});await m.screenshot({path:`${DIR}/tablet1024.png`});await m.locator('#plot-report').tap();assert.ok(await m.locator('#plot-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2));pass('320px larger-text touch and keyboard Enter/Space complete source actions;1024tablet and casebook fit');await mobile.close();
 await page.addInitScript(()=>window.addEventListener('pageshow',e=>{window.__qaPersisted=e.persisted;}));await page.goto(`${ORIGIN}/?game=plot`);await page.waitForFunction(()=>window.__plot&&document.querySelector('#plot-world canvas'));await page.locator('.plot-home').click();await page.goBack();await page.waitForFunction(()=>window.__plot&&document.querySelector('#plot-world canvas'));assert.equal(await page.locator('#plot-world canvas').evaluate(c=>c.getContext('webgl2').isContextLost()),false);report.backForwardCacheRestored=await page.evaluate(()=>window.__qaPersisted===true);await page.locator('#plot-start').click();await enterWardrobeIfNeeded(page);await page.locator('[data-visit="1"]').click();await page.locator('#plot-seal').click();assert.equal((await snap()).stage,1);await page.screenshot({path:`${DIR}/after-history-back.png`});pass('Browser Back restores a usable renderedworld and interactive source task');if(!report.backForwardCacheRestored)report.notes.push('Back navigation worked, but Chrome did not report pageshow.persisted=true; genuine BFCache restoration not proven in this automation context.');
 const corrupt=await browser.newContext();const bad=await corrupt.newPage();active=bad;listen(bad);await bad.addInitScript(()=>localStorage.setItem('schoolgle-midnight-letter-v1',JSON.stringify({version:1,started:true,completed:[0,4],attempts:[{chapter:0,action:'match-person-role',correct:false,at:'2026-09-07T10:00:00Z',help:{broken:true},response:'<img data-qa-injected src=x onerror=window.__qaInjected=true>'},{chapter:1,action:'bad-date',correct:true,at:'invalid',response:'discard'},{chapter:9,action:'bad-chapter',correct:true,at:'2026-09-07T10:00:00Z'}]})));await bad.goto(`${ORIGIN}/?game=plot`);await bad.waitForFunction(()=>window.__plot);const restored=await bad.evaluate(()=>window.__plot.snapshot());assert.deepEqual(restored.completed,[0]);assert.equal(restored.attempts.length,1);assert.deepEqual(restored.attempts[0].help,[]);await bad.locator('#plot-report').click();await bad.getByText('Responses and help used',{exact:true}).click();assert.equal(await bad.locator('[data-qa-injected]').count(),0);assert.equal(await bad.evaluate(()=>window.__qaInjected),undefined);assert.match(await bad.locator('#plot-dialog').innerText(),/<img data-qa-injected/);await corrupt.close();pass('Malformedhelp/date/chapter saves safely recover; exportedresponse text cannot injectHTMLinto grown-up casebook');
 report.evidenceReview={readAloudTracked:full.attempts.some(a=>a.help?.some(h=>/read.aloud/i.test(h))),undoMarkedIncorrect:full.attempts.some(a=>a.action==='undo-timeline-card'&&a.correct===false)};assert.equal(report.evidenceReview.readAloudTracked,true);assert.equal(report.evidenceReview.undoMarkedIncorrect,false);pass('Read-aloud support is retained; Undo is an observation rather than a scored mistake');assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);pass('No browser exceptions or failed requests across newgame, selector and Nile routes');report.ok=true;
 }
}catch(e){report.ok=false;report.failure=e.stack;console.error(e);await active.screenshot({path:`${DIR}/FAILURE.png`}).catch(()=>{});process.exitCode=1;}
finally{fs.writeFileSync(`${DIR}/${smokeOnly?'smoke-report':'report'}.json`,JSON.stringify(report,null,2));await context.close();await browser.close();}
