import type { Connector } from '../types';

export const DFE_CONNECTORS: Connector[] = [
  {
    id: 'dfe-attendance',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE Attendance',
    description: 'Overall, authorised, unauthorised absence with persistent absence rates — historic data from DfE.',
    icon: '🏛',
    colour: '#8b5cf6',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab'],
    consumers: ['ofsted-readiness', 'school-intelligence', 'living-sef'],
    dataSource: { type: 'supabase-table', reference: 'attendance' },
  },
  {
    id: 'dfe-ks2-results',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE KS2 Results',
    description: 'Key Stage 2 attainment, progress measures, scaled scores — historic data from DfE.',
    icon: '🏛',
    colour: '#ef4444',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab'],
    consumers: ['ofsted-readiness', 'school-intelligence', 'living-sef'],
    dataSource: { type: 'supabase-table', reference: 'ks2_results' },
  },
  {
    id: 'dfe-census',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE Census',
    description: 'Pupil demographics — roll, FSM, EAL, SEN, ethnicity, mobility.',
    icon: '🏛',
    colour: '#10b981',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab', 'postcode'],
    consumers: ['ofsted-readiness', 'school-intelligence', 'living-sef', 'send-hub'],
    dataSource: { type: 'supabase-table', reference: 'census' },
  },
  {
    id: 'dfe-workforce',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE Workforce',
    description: 'FTE teachers, TAs, support staff, vacancies, pay data.',
    icon: '🏛',
    colour: '#f59e0b',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab'],
    consumers: ['ofsted-readiness', 'school-intelligence', 'living-sef'],
    dataSource: { type: 'supabase-table', reference: 'workforce' },
  },
  {
    id: 'dfe-exclusions',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE Exclusions',
    description: 'Suspensions and permanent exclusions by term and reason.',
    icon: '🏛',
    colour: '#06b6d4',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab'],
    consumers: ['ofsted-readiness', 'school-intelligence'],
    dataSource: { type: 'supabase-table', reference: 'exclusions' },
  },
  {
    id: 'dfe-ks4-results',
    layer: 1,
    category: 'dfe-historic',
    name: 'DfE KS4 Results',
    description: 'Attainment 8, Progress 8, EBacc, basics measures.',
    icon: '🏛',
    colour: '#3b82f6',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'laestab'],
    consumers: ['ofsted-readiness', 'school-intelligence'],
    dataSource: { type: 'supabase-table', reference: 'ks4_results' },
  },
];
