import type { Connector } from '../types';

export const PLANNED_CONNECTORS: Connector[] = [
  {
    id: 'arbor-api',
    layer: 2,
    category: 'mis-api',
    name: 'Arbor API',
    description: 'Direct API integration with Arbor MIS — live pupil, attendance, assessment data.',
    icon: '🔵',
    colour: '#52525b',
    dataController: 'school',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['urn', 'pupil_hash'],
    consumers: ['school-intelligence', 'ofsted-readiness'],
  },
  {
    id: 'sims-api',
    layer: 2,
    category: 'mis-api',
    name: 'SIMS API',
    description: 'Direct API integration with SIMS — when available from ESS.',
    icon: '🔵',
    colour: '#52525b',
    dataController: 'school',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['urn', 'pupil_hash'],
    consumers: ['school-intelligence', 'ofsted-readiness'],
  },
  {
    id: 'bromcom-api',
    layer: 2,
    category: 'mis-api',
    name: 'Bromcom API',
    description: 'Direct API integration with Bromcom MIS.',
    icon: '🔵',
    colour: '#52525b',
    dataController: 'school',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['urn', 'pupil_hash'],
    consumers: ['school-intelligence', 'ofsted-readiness'],
  },
  {
    id: 'police-api',
    layer: 1,
    category: 'external-api',
    name: 'Police Information API',
    description: 'Local incident data for safeguarding context — UK Police API.',
    icon: '🚔',
    colour: '#52525b',
    dataController: 'us',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['postcode'],
    consumers: ['ofsted-readiness'],
  },
  {
    id: 'la-send-portal',
    layer: 1,
    category: 'external-api',
    name: 'LA SEND Portal',
    description: 'EHCP status, funding allocations, annual review dates from local authorities.',
    icon: '🏥',
    colour: '#52525b',
    dataController: 'school',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['urn', 'pupil_hash'],
    consumers: ['send-hub'],
  },
  {
    id: 'ofsted-public-api',
    layer: 1,
    category: 'external-api',
    name: 'Ofsted Public API',
    description: 'Published inspection reports, ratings, neighbouring school comparisons.',
    icon: '👁',
    colour: '#52525b',
    dataController: 'us',
    setupType: 'planned',
    status: 'planned',
    joinKeys: ['urn'],
    consumers: ['ofsted-readiness', 'school-intelligence'],
  },
];
