import type { Connector } from '../types';

export const SCHOOLGLE_INTERNAL_CONNECTORS: Connector[] = [
  {
    id: 'eef-research',
    layer: 1,
    category: 'schoolgle-internal',
    name: 'EEF Research Corpus',
    description: '33 evidence-backed strategies with impact ratings and cost bands.',
    icon: '📚',
    colour: '#a78bfa',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: [],
    consumers: ['school-intelligence', 'actions-hub', 'ofsted-readiness'],
    dataSource: { type: 'supabase-table', reference: 'eef_strategies' },
  },
  {
    id: 'contextual-factors',
    layer: 1,
    category: 'schoolgle-internal',
    name: 'Contextual Factors',
    description: 'School-logged events and interventions — staff changes, curriculum shifts, pivotal moments.',
    icon: '📍',
    colour: '#f59e0b',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn', 'date', 'year_group'],
    consumers: ['ofsted-readiness', 'school-intelligence', 'living-sef'],
    dataSource: { type: 'supabase-table', reference: 'school_contextual_factors' },
  },
  {
    id: 'schoolgle-intelligence',
    layer: 1,
    category: 'schoolgle-internal',
    name: 'Schoolgle Intelligence',
    description: 'AI-generated cross-module analyses and narratives.',
    icon: '🧠',
    colour: '#a78bfa',
    dataController: 'us',
    setupType: 'auto',
    status: 'active',
    joinKeys: ['urn'],
    consumers: ['living-sef', 'ofsted-readiness'],
    dataSource: { type: 'supabase-table', reference: 'school_intelligence_analyses' },
  },
];
