/**
 * Incident Data Sources
 *
 * Defines where incident data originates and where it is sent.
 * Used by the incident module for form pre-population, validation,
 * and by Ed to explain data provenance.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type DataSourceType = "internal" | "external" | "mis";
export type DataSourceDirection = "source" | "destination" | "both";

export interface DataSource {
  /** Human-readable name */
  name: string;
  /** Whether the source is internal to Schoolgle, an external system, or a MIS */
  type: DataSourceType;
  /** Whether data flows into the incident module, out of it, or both */
  direction: DataSourceDirection;
  /** Specific data fields exchanged */
  fields: string[];
  /** Description for Ed and documentation */
  description: string;
}

// ---------------------------------------------------------------------------
// Data Sources
// ---------------------------------------------------------------------------

export const INCIDENT_DATA_SOURCES: DataSource[] = [
  {
    name: "Manual Form Entry",
    type: "internal",
    direction: "source",
    fields: [
      "incident_date",
      "incident_time",
      "location",
      "description",
      "injury_type",
      "injury_severity",
      "body_part",
      "first_aid_given",
      "first_aider_name",
      "immediate_actions",
      "witnesses",
      "photos",
      "reporter_name",
      "reporter_role",
    ],
    description:
      "Primary data entry point. Staff complete the incident form via the dashboard or Ed assistant, capturing the core facts of the event.",
  },
  {
    name: "MIS — Pupil Data",
    type: "mis",
    direction: "source",
    fields: [
      "pupil_id",
      "pupil_year_group",
      "pupil_class",
      "pupil_sen_status",
      "pupil_pp_status",
      "pupil_medical_flags",
      "emergency_contacts",
      "parent_guardian_details",
    ],
    description:
      "Pupil demographic and pastoral data imported from the school MIS (Arbor, SIMS, Bromcom, ScholarPack). Used to pre-populate pupil details and identify vulnerable groups. Pupil names are HMAC-hashed client-side for zero-knowledge privacy.",
  },
  {
    name: "Staff Directory",
    type: "internal",
    direction: "source",
    fields: [
      "staff_id",
      "staff_name",
      "staff_role",
      "staff_department",
      "staff_email",
      "first_aid_qualified",
      "first_aid_expiry",
      "fire_marshal",
      "dsl_status",
    ],
    description:
      "Used to identify the reporter, injured party (if staff), first aider, witnesses, and responsible persons. Also validates first aid qualification status.",
  },
  {
    name: "Asset Register",
    type: "internal",
    direction: "source",
    fields: [
      "asset_id",
      "asset_name",
      "asset_type",
      "asset_location",
      "last_inspection_date",
      "next_inspection_due",
      "maintenance_history",
      "manufacturer",
      "model",
      "installation_date",
    ],
    description:
      "Equipment and asset data from the estates module. Links incidents to specific assets, pulls maintenance history for investigation, and flags overdue inspections.",
  },
  {
    name: "Contractor Register",
    type: "internal",
    direction: "source",
    fields: [
      "contractor_id",
      "contractor_name",
      "company_name",
      "insurance_expiry",
      "dbs_status",
      "risk_assessment_on_file",
      "current_works",
      "site_induction_date",
    ],
    description:
      "If the incident involves a contractor or occurs in an area where contractor works are active, their details and compliance status are pulled automatically.",
  },
  {
    name: "Risk Register",
    type: "internal",
    direction: "both",
    fields: [
      "risk_id",
      "risk_title",
      "risk_category",
      "likelihood_score",
      "impact_score",
      "risk_score",
      "existing_controls",
      "risk_owner",
      "review_date",
    ],
    description:
      "Bidirectional: existing risks are checked during triage to link or escalate, and new risks are created from incident findings. Post-remediation scores flow back.",
  },
  {
    name: "HSE — RIDDOR F2508",
    type: "external",
    direction: "destination",
    fields: [
      "riddor_reference",
      "f2508_report_data",
      "submission_date",
      "submission_confirmation",
      "reporting_deadline",
      "incident_category_riddor",
      "injured_person_details",
      "employer_details",
    ],
    description:
      "Outbound: for RIDDOR-reportable incidents, the F2508 report is generated by the document engine and submitted to HSE. The reporting deadline (10 or 15 days) is tracked by the compliance module.",
  },
  {
    name: "Notifications Service",
    type: "internal",
    direction: "destination",
    fields: [
      "recipient_email",
      "recipient_role",
      "notification_type",
      "notification_priority",
      "incident_summary",
      "action_required",
      "deadline",
    ],
    description:
      "Outbound: alerts are dispatched to headteacher, site manager, business manager, DSL (if pupil involved), and governors (if serious). Deadline reminders for HSE reporting.",
  },
  {
    name: "Intelligence Engine",
    type: "internal",
    direction: "both",
    fields: [
      "incident_count_by_type",
      "incident_count_by_location",
      "incident_count_by_time",
      "severity_trend",
      "repeat_offender_flags",
      "seasonal_patterns",
      "benchmarking_metrics",
      "cross_module_correlations",
    ],
    description:
      "Bidirectional: incident data feeds into the intelligence engine for trend analysis and pattern detection. The engine returns insights (hotspot locations, recurring equipment failures, seasonal spikes) that inform investigation and prevention.",
  },
  {
    name: "Safeguarding Module",
    type: "internal",
    direction: "destination",
    fields: [
      "pupil_id",
      "incident_reference",
      "incident_type",
      "injury_details",
      "safeguarding_concern_flag",
      "dsl_notified",
      "cpoms_reference",
    ],
    description:
      "Outbound: when a pupil is involved in an incident, the safeguarding module is notified so the DSL can assess whether the incident raises child protection concerns.",
  },
  {
    name: "Document Engine",
    type: "internal",
    direction: "both",
    fields: [
      "template_id",
      "document_type",
      "generated_document_id",
      "placeholders_resolved",
      "document_status",
      "signed_by",
      "signed_date",
    ],
    description:
      "Bidirectional: the document engine generates F2508 reports, witness statement templates, and investigation reports from incident data. Completed documents are stored back against the incident record.",
  },
  {
    name: "Estates Helpdesk",
    type: "internal",
    direction: "both",
    fields: [
      "ticket_id",
      "ticket_status",
      "ticket_priority",
      "assigned_to",
      "location",
      "description",
      "resolution_notes",
      "completion_date",
    ],
    description:
      "Bidirectional: incidents create or link to helpdesk tickets for remedial works. Ticket progress and resolution feed back into the incident timeline.",
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Return all sources (data flowing into the incident module) */
export function getSourceSystems(): DataSource[] {
  return INCIDENT_DATA_SOURCES.filter(
    (ds) => ds.direction === "source" || ds.direction === "both",
  );
}

/** Return all destinations (data flowing out of the incident module) */
export function getDestinationSystems(): DataSource[] {
  return INCIDENT_DATA_SOURCES.filter(
    (ds) => ds.direction === "destination" || ds.direction === "both",
  );
}

/** Return data sources by type */
export function getDataSourcesByType(type: DataSourceType): DataSource[] {
  return INCIDENT_DATA_SOURCES.filter((ds) => ds.type === type);
}

/** Return all fields that flow into the incident module (useful for form pre-population) */
export function getAllSourceFields(): string[] {
  return Array.from(new Set(getSourceSystems().flatMap((ds) => ds.fields)));
}
