import { describe, expect, it } from "vitest";
import type { Meeting, MeetingChecklistItem, MeetingTemplate } from "./types";
import { generateMinutesContent, renderMinutesHtml } from "./minutes-generator";

const meeting = {
  scheduled_at: "2026-04-30T09:00:00.000Z",
  location: "Head teacher's office",
  attendee_name: "Tom",
  attendee_role: "Teacher",
  purpose: "Formal sickness review",
  notes: [{ timestamp: "2026-04-30T09:10:00.000Z", text: "Agreed phased return." }],
} as Meeting;

const template = {
  name: "Formal Sickness Review",
} as MeetingTemplate;

const checklistItems = [
  {
    phrase: "Confirm right to be accompanied",
    category: "Rights",
    status: "green",
    manually_ticked: true,
    is_critical: true,
    order_index: 1,
  },
  {
    phrase: "Agree next review date",
    category: "Actions",
    status: "red",
    manually_ticked: false,
    is_critical: false,
    order_index: 2,
  },
] as MeetingChecklistItem[];

describe("minutes-generator", () => {
  it("creates draft minutes from meeting notes rather than chair scripts", () => {
    const content = generateMinutesContent(meeting, template, checklistItems);

    expect(content.opening).toContain(
      "The draft minutes below combine the captured meeting notes with the required checklist coverage.",
    );
    expect(content.notes).toEqual(["Agreed phased return."]);
    expect(content.closing).toContain(
      "The meeting closed with the recorded points and checklist coverage noted above.",
    );
  });

  it("renders item-level minute notes so generated content is visible", () => {
    const html = renderMinutesHtml({
      ...generateMinutesContent(meeting, template, checklistItems),
      sections: [
        {
          title: "Discussion",
          items: [
            {
              phrase: "Support plan",
              covered: true,
              notes: "A phased return was agreed for the first two weeks.",
            },
          ],
        },
      ],
    });

    expect(html).toContain("A phased return was agreed for the first two weeks.");
  });

  it("renders organisation branding in generated minutes", () => {
    const html = renderMinutesHtml(
      generateMinutesContent(meeting, template, checklistItems),
      {
        logo_url: "https://example.com/school-logo.png",
        school_name: "Rawdon St Peter's C of E Primary School",
        primary_color: "#123456",
        footer_text: "Approved school minutes record.",
      },
    );

    expect(html).toContain('src="https://example.com/school-logo.png"');
    expect(html).toContain("Generated by Rawdon St Peter's C of E Primary School");
    expect(html).toContain("color:#123456");
    expect(html).toContain("Approved school minutes record.");
  });
});
