-- Staff Connector Catalogue
-- Source-of-truth role definitions used by staff profiles, Incident Hub, policies, Ed and compliance.

create table if not exists public.connector_types (
  id text primary key,
  organization_id uuid null references public.organizations(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  category text not null check (category in (
    'safeguarding',
    'send',
    'health_safety',
    'data_governance',
    'estates',
    'governance',
    'curriculum',
    'operations',
    'custom'
  )),
  is_statutory boolean not null default false,
  statutory_basis text,
  statutory_reference text,
  source_url text,
  source_publisher text,
  minimum_count integer not null default 0,
  ratio_label text,
  ratio_basis text,
  requires_training boolean not null default false,
  training_name text,
  training_renewal_months integer,
  modules text[] not null default '{}',
  policy_placeholders text[] not null default '{}',
  incident_types text[] not null default '{}',
  responsibilities text[] not null default '{}',
  icon text,
  color text,
  sort_order integer not null default 0,
  review_due_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug)
);

create index if not exists idx_connector_types_org_category
  on public.connector_types (organization_id, category, sort_order);

create index if not exists idx_connector_types_slug
  on public.connector_types (slug);

alter table public.connector_types enable row level security;

insert into public.connector_types (
  id,
  organization_id,
  name,
  slug,
  description,
  category,
  is_statutory,
  statutory_basis,
  statutory_reference,
  source_url,
  source_publisher,
  minimum_count,
  ratio_label,
  ratio_basis,
  requires_training,
  training_name,
  training_renewal_months,
  modules,
  policy_placeholders,
  incident_types,
  responsibilities,
  icon,
  color,
  sort_order,
  review_due_at
) values
  (
    'dsl',
    null,
    'Designated Safeguarding Lead (DSL)',
    'dsl',
    'Senior member of staff with lead responsibility for safeguarding and child protection, including online safety.',
    'safeguarding',
    true,
    'Keeping Children Safe in Education',
    'DSL should have appropriate status and authority within the school or college.',
    'https://www.gov.uk/government/publications/keeping-children-safe-in-education',
    'Department for Education',
    1,
    'Minimum 1; deputy cover strongly expected',
    'school',
    true,
    'Designated Safeguarding Lead training',
    24,
    array['safeguarding','compliance','governance','incidents'],
    array['DSL_NAME','DSL_EMAIL'],
    array['Safeguarding concern','Behaviour incident','Child missing / supervision failure'],
    array[
      'Receive and manage safeguarding concerns',
      'Liaise with local safeguarding partners',
      'Maintain secure safeguarding records',
      'Support staff with safeguarding decisions'
    ],
    'Shield',
    'rose',
    10,
    '2026-09-01'
  ),
  (
    'deputy-dsl',
    null,
    'Deputy Designated Safeguarding Lead',
    'deputy-dsl',
    'Trained safeguarding lead who can support or act for the DSL.',
    'safeguarding',
    true,
    'Keeping Children Safe in Education',
    'Schools should ensure safeguarding concerns can be acted on when the DSL is unavailable.',
    'https://www.gov.uk/government/publications/keeping-children-safe-in-education',
    'Department for Education',
    1,
    'Recommended 1+ deputies',
    'school',
    true,
    'Designated Safeguarding Lead training',
    24,
    array['safeguarding','compliance','incidents'],
    array['DEPUTY_DSL_NAME'],
    array['Safeguarding concern','Behaviour incident'],
    array[
      'Support the DSL with safeguarding concerns',
      'Act as safeguarding contact when DSL is unavailable',
      'Maintain awareness of open safeguarding actions'
    ],
    'ShieldCheck',
    'rose',
    20,
    '2026-09-01'
  ),
  (
    'dpo',
    null,
    'Data Protection Officer (DPO)',
    'dpo',
    'Person or service responsible for advising on UK GDPR, data protection incidents, SARs and FOI routing.',
    'data_governance',
    true,
    'UK GDPR',
    'Article 37 and public authority DPO expectations.',
    'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-officers/',
    'Information Commissioner''s Office',
    1,
    'Minimum 1; may be external',
    'organization',
    true,
    'Data protection / UK GDPR training',
    12,
    array['compliance','governance','it','incidents','documents'],
    array['DPO_NAME','DPO_EMAIL'],
    array['GDPR incident','Subject access request','Freedom of information request'],
    array[
      'Advise on data protection incidents',
      'Support SAR and FOI handling',
      'Monitor data protection compliance',
      'Advise on DPIA and data sharing risks'
    ],
    'Lock',
    'violet',
    30,
    '2026-09-01'
  ),
  (
    'senco',
    null,
    'Special Educational Needs Co-ordinator (SENCO)',
    'senco',
    'Qualified teacher or headteacher responsible for coordinating SEND provision in a mainstream school.',
    'send',
    true,
    'SEND Regulations and SENCO NPQ guidance',
    'All mainstream schools must have a SENCO; mandatory qualification window applies.',
    'https://www.gov.uk/guidance/special-educational-needs-co-ordinators-national-professional-qualification',
    'Department for Education',
    1,
    'Minimum 1',
    'school',
    true,
    'SENCO mandatory qualification / NPQ',
    null,
    array['send','compliance','governance','incidents','documents'],
    array['SENCO_NAME','SENCO_EMAIL'],
    array['SEND provision concern'],
    array[
      'Coordinate SEND provision',
      'Advise on SEND resources and support',
      'Support APDR and EHCP processes',
      'Link with parents and external professionals'
    ],
    'GraduationCap',
    'blue',
    40,
    '2026-09-01'
  ),
  (
    'first-aider',
    null,
    'First Aider',
    'first-aider',
    'Trained first aider available to provide emergency first aid support.',
    'health_safety',
    true,
    'Health and Safety (First-Aid) Regulations 1981',
    'Employers must provide adequate and appropriate first-aid equipment, facilities and personnel based on needs assessment.',
    'https://www.hse.gov.uk/firstaid/what-employers-need-to-do.htm',
    'Health and Safety Executive',
    1,
    'Needs-assessment based',
    'pupils_staff_site_risk',
    true,
    'First aid at work / emergency first aid',
    36,
    array['compliance','estates','hr','incidents'],
    array['FIRST_AIDER_NAMES'],
    array['Pupil accident','Staff accident / near miss'],
    array[
      'Provide first aid within training limits',
      'Record first aid incidents',
      'Escalate serious injuries',
      'Support parent/carer notification process'
    ],
    'HeartPulse',
    'emerald',
    50,
    '2026-09-01'
  ),
  (
    'paediatric-first-aider',
    null,
    'Paediatric First Aider',
    'paediatric-first-aider',
    'First aider with paediatric training, particularly relevant for EYFS and younger pupils.',
    'health_safety',
    true,
    'EYFS statutory framework and HSE first aid needs assessment',
    'Early years provision must have appropriate paediatric first aid arrangements.',
    'https://www.gov.uk/government/publications/early-years-foundation-stage-framework--2',
    'Department for Education',
    1,
    'EYFS cover required where applicable',
    'eyfs_pupils',
    true,
    'Paediatric first aid',
    36,
    array['compliance','hr','incidents'],
    array['PAEDIATRIC_FIRST_AIDER_NAMES'],
    array['Pupil accident'],
    array[
      'Provide age-appropriate first aid',
      'Support EYFS first aid cover',
      'Record first aid incidents',
      'Escalate serious or head injuries'
    ],
    'HeartPulse',
    'emerald',
    60,
    '2026-09-01'
  ),
  (
    'health-safety-lead',
    null,
    'Health and Safety Lead',
    'health-safety-lead',
    'Named operational lead for day-to-day health and safety coordination. This supports the employer/headteacher duty but does not transfer legal accountability.',
    'health_safety',
    false,
    'Health and Safety at Work etc. Act 1974 / Management of Health and Safety at Work Regulations',
    'Overall accountability sits with the school employer, while day-to-day running is normally delegated to the headteacher and school management team. Key staff should have clear roles and responsibilities.',
    'https://www.hse.gov.uk/education/sensible-leadership/school-leaders.htm',
    'Health and Safety Executive',
    1,
    'Minimum 1 recommended',
    'school',
    false,
    null,
    null,
    array['compliance','estates','incidents'],
    array['HEALTH_SAFETY_LEAD_NAME'],
    array['Pupil accident','Staff accident / near miss','Estates hazard','Contractor issue'],
    array[
      'Coordinate day-to-day health and safety follow-up',
      'Review hazards and near misses',
      'Ensure risk assessments are actioned',
      'Make sure staff know where to get health and safety support',
      'Escalate serious incidents'
    ],
    'HardHat',
    'amber',
    70,
    '2026-09-01'
  ),
  (
    'fire-marshal',
    null,
    'Fire Marshal / Fire Warden',
    'fire-marshal',
    'Person assigned to support local fire evacuation arrangements, checks and drills. This supports the fire safety responsible person.',
    'health_safety',
    false,
    'Regulatory Reform (Fire Safety) Order 2005',
    'The responsible person must manage fire safety arrangements, including risk assessment, emergency planning, staff information, instruction and training. Fire marshal numbers are risk-assessment based.',
    'https://www.gov.uk/workplace-fire-safety-your-responsibilities',
    'GOV.UK',
    1,
    'Risk-assessment based by site/zone',
    'site_zone',
    true,
    'Fire marshal / fire warden training',
    12,
    array['estates','compliance','incidents'],
    array['FIRE_MARSHAL_NAMES'],
    array['Estates hazard','Fire incident'],
    array[
      'Support evacuation arrangements',
      'Report fire safety defects',
      'Support fire drill processes',
      'Escalate blocked routes or alarm issues'
    ],
    'Flame',
    'orange',
    80,
    '2026-09-01'
  ),
  (
    'site-manager',
    null,
    'Site Manager / Premises Lead',
    'site-manager',
    'Person responsible for premises operations and site issue coordination.',
    'estates',
    false,
    'Local school premises management arrangements',
    'Operational responsibility defined by school/trust policy and delegation.',
    null,
    'School / Trust policy',
    1,
    'Minimum 1 recommended',
    'site',
    false,
    null,
    null,
    array['estates','compliance','incidents'],
    array['SITE_MANAGER_NAME'],
    array['Estates hazard','Contractor issue'],
    array[
      'Coordinate site response',
      'Liaise with contractors',
      'Record premises evidence',
      'Escalate urgent site risks'
    ],
    'Building2',
    'slate',
    90,
    '2026-09-01'
  ),
  (
    'educational-visits-coordinator',
    null,
    'Educational Visits Coordinator (EVC)',
    'educational-visits-coordinator',
    'Person responsible for coordinating educational visit planning and risk management.',
    'health_safety',
    false,
    'DfE health and safety advice on educational visits',
    'Schools should have clear arrangements for educational visit planning and approval.',
    'https://www.gov.uk/government/publications/health-and-safety-on-educational-visits',
    'Department for Education',
    1,
    'Minimum 1 recommended',
    'school',
    true,
    'Educational Visits Coordinator training',
    36,
    array['compliance','incidents'],
    array['EVC_NAME'],
    array['Trip incident','Pupil accident'],
    array[
      'Coordinate visit risk processes',
      'Support trip incident follow-up',
      'Maintain visit evidence and approvals'
    ],
    'Map',
    'cyan',
    100,
    '2026-09-01'
  ),
  (
    'key-stage-1-lead',
    null,
    'Key Stage 1 Lead',
    'key-stage-1-lead',
    'School-defined curriculum or phase lead for Key Stage 1.',
    'curriculum',
    false,
    'School leadership structure',
    'Good-practice school-defined responsibility.',
    null,
    'School / Trust policy',
    0,
    'Optional',
    'school',
    false,
    null,
    null,
    array['curriculum','hr','documents'],
    array['KS1_LEAD_NAME'],
    array[]::text[],
    array['Act as named lead for KS1 curriculum and operational questions'],
    'BookOpen',
    'sky',
    200,
    '2026-09-01'
  ),
  (
    'key-stage-2-lead',
    null,
    'Key Stage 2 Lead',
    'key-stage-2-lead',
    'School-defined curriculum or phase lead for Key Stage 2.',
    'curriculum',
    false,
    'School leadership structure',
    'Good-practice school-defined responsibility.',
    null,
    'School / Trust policy',
    0,
    'Optional',
    'school',
    false,
    null,
    null,
    array['curriculum','hr','documents'],
    array['KS2_LEAD_NAME'],
    array[]::text[],
    array['Act as named lead for KS2 curriculum and operational questions'],
    'BookOpen',
    'sky',
    210,
    '2026-09-01'
  )
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  category = excluded.category,
  is_statutory = excluded.is_statutory,
  statutory_basis = excluded.statutory_basis,
  statutory_reference = excluded.statutory_reference,
  source_url = excluded.source_url,
  source_publisher = excluded.source_publisher,
  minimum_count = excluded.minimum_count,
  ratio_label = excluded.ratio_label,
  ratio_basis = excluded.ratio_basis,
  requires_training = excluded.requires_training,
  training_name = excluded.training_name,
  training_renewal_months = excluded.training_renewal_months,
  modules = excluded.modules,
  policy_placeholders = excluded.policy_placeholders,
  incident_types = excluded.incident_types,
  responsibilities = excluded.responsibilities,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order,
  review_due_at = excluded.review_due_at,
  updated_at = now();
