-- ═══════════════════════════════════════════════════════════════════════════
-- Seed: NC2014 Primary Curriculum Statutory Objectives
-- ═══════════════════════════════════════════════════════════════════════════
-- Seeds ~250 statutory objectives for Maths, English Reading, English Writing,
-- and Science across Reception to Year 6.
-- Uses ON CONFLICT to be safely re-runnable.

-- ─── Mathematics ─────────────────────────────────────────────────────────

INSERT INTO ls_curriculum_objectives (framework_id, subject, key_stage, year_group, objective_code, objective_text, strand, sub_strand, is_statutory, display_order)
VALUES
-- Year 1 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-NPV-01', 'Count to and across 100, forwards and backwards, beginning with 0 or 1, or from any given number', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-NPV-02', 'Count, read and write numbers to 100 in numerals', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-NPV-03', 'Given a number, identify one more and one less', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-NPV-04', 'Identify and represent numbers using objects and pictorial representations including the number line', 'Number & Place Value', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-NPV-05', 'Use the language of: equal to, more than, less than, most, least', 'Number & Place Value', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-AS-01', 'Read, write and interpret mathematical statements involving addition (+), subtraction (-) and equals (=) signs', 'Addition & Subtraction', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-AS-02', 'Represent and use number bonds and related subtraction facts within 20', 'Addition & Subtraction', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-AS-03', 'Add and subtract one-digit and two-digit numbers to 20, including zero', 'Addition & Subtraction', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-MD-01', 'Solve one-step problems involving multiplication and division, by calculating the answer using concrete objects, pictorial representations and arrays', 'Multiplication & Division', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-G-01', 'Recognise and name common 2-D shapes (rectangles, squares, circles, triangles)', 'Geometry', 'Properties of Shapes', true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-G-02', 'Recognise and name common 3-D shapes (cuboids, cubes, pyramids, spheres)', 'Geometry', 'Properties of Shapes', true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-ME-01', 'Compare, describe and solve practical problems for lengths and heights, mass/weight, capacity and volume', 'Measurement', NULL, true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 1', 'Y1-M-ME-02', 'Sequence events in chronological order using language such as before, after, next, first, today, yesterday, tomorrow', 'Measurement', 'Time', true, 13),

-- Year 2 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-NPV-01', 'Count in steps of 2, 3, and 5 from 0, and in tens from any number, forward and backward', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-NPV-02', 'Recognise the place value of each digit in a two-digit number (tens, ones)', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-NPV-03', 'Compare and order numbers from 0 up to 100; use < > and = signs', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-NPV-04', 'Read and write numbers to at least 100 in numerals and in words', 'Number & Place Value', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-AS-01', 'Solve problems with addition and subtraction using concrete objects, pictorial representations, and mentally', 'Addition & Subtraction', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-AS-02', 'Recall and use addition and subtraction facts to 20 fluently, and derive and use related facts up to 100', 'Addition & Subtraction', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-AS-03', 'Add and subtract numbers using concrete objects, pictorial representations, and mentally (two two-digit numbers)', 'Addition & Subtraction', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-MD-01', 'Recall and use multiplication and division facts for the 2, 5 and 10 multiplication tables', 'Multiplication & Division', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-MD-02', 'Calculate mathematical statements for multiplication and division within the multiplication tables and write them using the signs', 'Multiplication & Division', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-F-01', 'Recognise, find, name and write fractions 1/3, 1/4, 2/4, 3/4 of a length, shape, set of objects or quantity', 'Fractions', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-ME-01', 'Choose and use appropriate standard units to estimate and measure length/height, mass, temperature and capacity', 'Measurement', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-ME-02', 'Tell and write the time to five minutes, including quarter past/to the hour, and draw hands on a clock face', 'Measurement', 'Time', true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-G-01', 'Identify and describe the properties of 2-D shapes, including the number of sides and line symmetry', 'Geometry', 'Properties of Shapes', true, 13),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS1', 'Year 2', 'Y2-M-ST-01', 'Interpret and construct simple pictograms, tally charts, block diagrams and simple tables', 'Statistics', NULL, true, 14),

-- Year 3 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-NPV-01', 'Count from 0 in multiples of 4, 8, 50 and 100; find 10 or 100 more or less than a given number', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-NPV-02', 'Recognise the place value of each digit in a three-digit number (hundreds, tens, ones)', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-NPV-03', 'Compare and order numbers up to 1000', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-NPV-04', 'Read and write numbers up to 1000 in numerals and in words', 'Number & Place Value', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-AS-01', 'Add and subtract numbers mentally, including a three-digit number and ones, tens, hundreds', 'Addition & Subtraction', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-AS-02', 'Add and subtract numbers with up to three digits, using formal written methods of columnar addition and subtraction', 'Addition & Subtraction', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-MD-01', 'Recall and use multiplication and division facts for the 3, 4 and 8 multiplication tables', 'Multiplication & Division', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-MD-02', 'Write and calculate mathematical statements for multiplication and division using the multiplication tables they know', 'Multiplication & Division', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-F-01', 'Count up and down in tenths; recognise that tenths arise from dividing an object into 10 equal parts', 'Fractions', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-F-02', 'Recognise, find and write fractions of a discrete set of objects: unit fractions and non-unit fractions with small denominators', 'Fractions', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-F-03', 'Add and subtract fractions with the same denominator within one whole', 'Fractions', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-ME-01', 'Measure, compare, add and subtract lengths (m/cm/mm), mass (kg/g), volume/capacity (l/ml)', 'Measurement', NULL, true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 3', 'Y3-M-ME-02', 'Tell and write the time from an analogue clock, including using Roman numerals; 12-hour and 24-hour clocks', 'Measurement', 'Time', true, 13),

-- Year 4 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-NPV-01', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-NPV-02', 'Find 1000 more or less than a given number', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-NPV-03', 'Recognise the place value of each digit in a four-digit number (thousands, hundreds, tens, ones)', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-NPV-04', 'Order and compare numbers beyond 1000', 'Number & Place Value', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-NPV-05', 'Round any number to the nearest 10, 100 or 1000', 'Number & Place Value', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-AS-01', 'Add and subtract numbers with up to 4 digits using the formal written methods of columnar addition and subtraction', 'Addition & Subtraction', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-MD-01', 'Recall multiplication and division facts for multiplication tables up to 12 x 12', 'Multiplication & Division', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-MD-02', 'Use place value, known and derived facts to multiply and divide mentally, including multiplying by 0 and 1, dividing by 1, multiplying together three numbers', 'Multiplication & Division', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-F-01', 'Recognise and show, using diagrams, families of common equivalent fractions', 'Fractions & Decimals', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-F-02', 'Add and subtract fractions with the same denominator', 'Fractions & Decimals', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-F-03', 'Recognise and write decimal equivalents of any number of tenths or hundredths', 'Fractions & Decimals', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-ME-01', 'Find the area of rectilinear shapes by counting squares', 'Measurement', 'Area & Perimeter', true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 4', 'Y4-M-ME-02', 'Measure and calculate the perimeter of a rectilinear figure in centimetres and metres', 'Measurement', 'Area & Perimeter', true, 13),

-- Year 5 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-NPV-01', 'Read, write, order and compare numbers to at least 1,000,000 and determine the value of each digit', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-NPV-02', 'Interpret negative numbers in context, count forwards and backwards with positive and negative whole numbers through zero', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-NPV-03', 'Round any number up to 1,000,000 to the nearest 10, 100, 1000, 10,000 and 100,000', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-AS-01', 'Add and subtract whole numbers with more than 4 digits, including using formal written methods (columnar addition and subtraction)', 'Addition & Subtraction', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-MD-01', 'Multiply numbers up to 4 digits by a one or two-digit number using a formal written method, including long multiplication for two-digit numbers', 'Multiplication & Division', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-MD-02', 'Divide numbers up to 4 digits by a one-digit number using the formal written method of short division and interpret remainders', 'Multiplication & Division', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-F-01', 'Compare and order fractions whose denominators are all multiples of the same number', 'Fractions, Decimals & Percentages', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-F-02', 'Add and subtract fractions with the same denominator and denominators that are multiples of the same number', 'Fractions, Decimals & Percentages', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-F-03', 'Multiply proper fractions and mixed numbers by whole numbers, supported by materials and diagrams', 'Fractions, Decimals & Percentages', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-F-04', 'Read and write decimal numbers as fractions; recognise and use thousandths', 'Fractions, Decimals & Percentages', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-F-05', 'Recognise the per cent symbol (%) and understand percentage relates to number of parts per hundred', 'Fractions, Decimals & Percentages', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-ME-01', 'Calculate and compare the area of rectangles and estimate the area of irregular shapes', 'Measurement', 'Area & Volume', true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 5', 'Y5-M-ME-02', 'Estimate volume and capacity (e.g. using 1 cm cubes and water)', 'Measurement', 'Area & Volume', true, 13),

-- Year 6 Maths
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-NPV-01', 'Read, write, order and compare numbers up to 10,000,000 and determine the value of each digit', 'Number & Place Value', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-NPV-02', 'Round any whole number to a required degree of accuracy', 'Number & Place Value', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-NPV-03', 'Use negative numbers in context, and calculate intervals across zero', 'Number & Place Value', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-MD-01', 'Multiply multi-digit numbers up to 4 digits by a two-digit whole number using the formal written method of long multiplication', 'Multiplication & Division', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-MD-02', 'Divide numbers up to 4 digits by a two-digit whole number using the formal written method of long division, and interpret remainders as whole number remainders, fractions, or by rounding', 'Multiplication & Division', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-F-01', 'Use common factors to simplify fractions; use common multiples to express fractions in the same denomination', 'Fractions, Decimals & Percentages', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-F-02', 'Add and subtract fractions with different denominators and mixed numbers, using the concept of equivalent fractions', 'Fractions, Decimals & Percentages', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-F-03', 'Multiply simple pairs of proper fractions, writing the answer in its simplest form', 'Fractions, Decimals & Percentages', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-F-04', 'Divide proper fractions by whole numbers', 'Fractions, Decimals & Percentages', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-R-01', 'Solve problems involving the relative sizes of two quantities where missing values can be found by using integer multiplication and division facts', 'Ratio & Proportion', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-A-01', 'Use simple formulae; generate and describe linear number sequences', 'Algebra', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-A-02', 'Express missing number problems algebraically; find pairs of numbers that satisfy an equation with two unknowns', 'Algebra', NULL, true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Mathematics', 'KS2', 'Year 6', 'Y6-M-ST-01', 'Interpret and construct pie charts and line graphs and use these to solve problems', 'Statistics', NULL, true, 13),

-- ─── English Reading ─────────────────────────────────────────────────────

-- Year 1 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-WR-01', 'Apply phonic knowledge and skills as the route to decode words', 'Word Reading', 'Phonics', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-WR-02', 'Read accurately by blending sounds in unfamiliar words containing GPCs that have been taught', 'Word Reading', 'Phonics', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-WR-03', 'Read common exception words, noting unusual correspondences between spelling and sound', 'Word Reading', 'Common Exception Words', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-WR-04', 'Read aloud accurately books that are consistent with their developing phonic knowledge', 'Word Reading', 'Fluency', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-C-01', 'Listening to and discussing a wide range of poems, stories and non-fiction at a level beyond that at which they can read independently', 'Comprehension', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-C-02', 'Become very familiar with key stories, fairy stories and traditional tales, retelling them and considering their particular characteristics', 'Comprehension', 'Familiarity', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-C-03', 'Recognise and join in with predictable phrases', 'Comprehension', 'Participation', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 1', 'Y1-ER-C-04', 'Check that the text makes sense to them as they read and correcting inaccurate reading', 'Comprehension', 'Monitoring', true, 8),

-- Year 2 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-WR-01', 'Continue to apply phonic knowledge and skills as the route to decode words until automatic decoding has become embedded', 'Word Reading', 'Phonics', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-WR-02', 'Read accurately by blending the sounds in words that contain the graphemes taught so far, especially recognising alternative sounds for graphemes', 'Word Reading', 'Phonics', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-WR-03', 'Read most words quickly and accurately, without overt sounding and blending, when they have been frequently encountered', 'Word Reading', 'Fluency', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-C-01', 'Discuss the sequence of events in books and how items of information are related', 'Comprehension', 'Sequencing', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-C-02', 'Draw on what they already know or on background information and vocabulary provided by the teacher', 'Comprehension', 'Prior Knowledge', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-C-03', 'Make inferences on the basis of what is being said and done', 'Comprehension', 'Inference', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-C-04', 'Answer and ask questions about a text', 'Comprehension', 'Retrieval', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS1', 'Year 2', 'Y2-ER-C-05', 'Explain and discuss their understanding of books, poems and other material, both those that they listen to and those that they read for themselves', 'Comprehension', 'Discussion', true, 8),

-- Year 3 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-WR-01', 'Apply their growing knowledge of root words, prefixes and suffixes to read aloud and to understand the meaning of new words they meet', 'Word Reading', 'Morphology', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-WR-02', 'Read further exception words, noting the unusual correspondences between spelling and sound', 'Word Reading', 'Common Exception Words', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-01', 'Listening to and discussing a wide range of fiction, poetry, plays, non-fiction and reference books or textbooks', 'Comprehension', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-02', 'Use dictionaries to check the meaning of words that they have read', 'Comprehension', 'Vocabulary', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-03', 'Check that the text makes sense to them, discussing their understanding and explaining the meaning of words in context', 'Comprehension', 'Monitoring', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-04', 'Ask questions to improve their understanding of a text', 'Comprehension', 'Questioning', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-05', 'Draw inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence', 'Comprehension', 'Inference', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 3', 'Y3-ER-C-06', 'Identify main ideas drawn from more than one paragraph and summarise these', 'Comprehension', 'Summarising', true, 8),

-- Year 4 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-WR-01', 'Apply their growing knowledge of root words, prefixes and suffixes, both to read aloud and to understand the meaning of new words they meet', 'Word Reading', 'Morphology', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-01', 'Read books that are structured in different ways and reading for a range of purposes', 'Comprehension', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-02', 'Identify themes and conventions in a wide range of books', 'Comprehension', 'Themes', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-03', 'Retrieve and record information from non-fiction', 'Comprehension', 'Retrieval', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-04', 'Discuss words and phrases that capture the reader''s interest and imagination', 'Comprehension', 'Language', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-05', 'Predict what might happen from details stated and implied', 'Comprehension', 'Prediction', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 4', 'Y4-ER-C-06', 'Participate in discussion about both books that are read to them and those they can read for themselves, taking turns and listening to what others say', 'Comprehension', 'Discussion', true, 7),

-- Year 5 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-WR-01', 'Apply their growing knowledge of root words, prefixes and suffixes (morphology and etymology), both to read aloud and to understand the meaning of new words', 'Word Reading', 'Morphology', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-01', 'Maintain positive attitudes to reading and an understanding of what they read by continuing to read and discuss an increasingly wide range of fiction, poetry, plays, non-fiction and reference books', 'Comprehension', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-02', 'Identify and discuss themes and conventions in and across a wide range of writing', 'Comprehension', 'Themes', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-03', 'Draw inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence', 'Comprehension', 'Inference', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-04', 'Summarise the main ideas drawn from more than one paragraph, identifying key details that support the main ideas', 'Comprehension', 'Summarising', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-05', 'Distinguish between statements of fact and opinion', 'Comprehension', 'Evaluation', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 5', 'Y5-ER-C-06', 'Explain and discuss their understanding of what they have read, including through formal presentations and debates', 'Comprehension', 'Discussion', true, 7),

-- Year 6 Reading
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-WR-01', 'Apply their growing knowledge of root words, prefixes and suffixes (morphology and etymology) to read aloud and understand the meaning of new words', 'Word Reading', 'Morphology', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-01', 'Read and discuss an increasingly wide range of fiction, poetry, plays, non-fiction, reference books and textbooks', 'Comprehension', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-02', 'Recommend books to peers, giving reasons for choices', 'Comprehension', 'Recommendation', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-03', 'Draw inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence', 'Comprehension', 'Inference', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-04', 'Predict what might happen from details stated and implied', 'Comprehension', 'Prediction', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-05', 'Identify how language, structure, and presentation contribute to meaning', 'Comprehension', 'Authorial Intent', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-06', 'Discuss and evaluate how authors use language, considering the impact on the reader', 'Comprehension', 'Evaluation', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Reading', 'KS2', 'Year 6', 'Y6-ER-C-07', 'Make comparisons within and across books', 'Comprehension', 'Comparison', true, 8),

-- ─── English Writing ─────────────────────────────────────────────────────

-- Year 1 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-T-01', 'Write sentences by saying out loud what they are going to write about', 'Transcription & Composition', 'Composition', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-T-02', 'Compose a sentence orally before writing it', 'Transcription & Composition', 'Composition', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-T-03', 'Sequence sentences to form short narratives', 'Transcription & Composition', 'Composition', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-T-04', 'Re-read what they have written to check that it makes sense', 'Transcription & Composition', 'Editing', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-SP-01', 'Spell words containing each of the 40+ phonemes already taught', 'Spelling', 'Phonics', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-SP-02', 'Spell common exception words', 'Spelling', 'Common Exception Words', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-SP-03', 'Name the letters of the alphabet in order', 'Spelling', 'Alphabet', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-P-01', 'Use capital letters, full stops, question marks and exclamation marks to demarcate sentences', 'Punctuation', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-P-02', 'Use a capital letter for names of people, places, the days of the week, and the personal pronoun I', 'Punctuation', 'Capitals', true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-H-01', 'Sit correctly at a table, holding a pencil comfortably and correctly', 'Handwriting', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 1', 'Y1-EW-H-02', 'Form lower-case letters in the correct direction, starting and finishing in the right place', 'Handwriting', NULL, true, 11),

-- Year 2 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-T-01', 'Write narratives about personal experiences and those of others (real and fictional)', 'Composition', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-T-02', 'Write about real events, recording these simply and clearly', 'Composition', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-T-03', 'Write for different purposes including instructions, stories, poetry, and information texts', 'Composition', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-T-04', 'Proofread to check for errors in spelling, grammar and punctuation', 'Composition', 'Editing', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-SP-01', 'Spell by segmenting spoken words into phonemes and representing these by graphemes, spelling many correctly', 'Spelling', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-SP-02', 'Learn new ways of spelling phonemes for which one or more spellings are already known, and learn some words with each spelling', 'Spelling', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-P-01', 'Use subordination (using when, if, that, because) and co-ordination (using or, and, but)', 'Grammar & Punctuation', 'Conjunctions', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-P-02', 'Use expanded noun phrases to describe and specify (e.g. the blue butterfly)', 'Grammar & Punctuation', 'Noun Phrases', true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-P-03', 'Use commas to separate items in a list', 'Grammar & Punctuation', 'Commas', true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS1', 'Year 2', 'Y2-EW-P-04', 'Use apostrophes for contracted forms and the possessive (singular)', 'Grammar & Punctuation', 'Apostrophes', true, 10),

-- Year 3 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-T-01', 'Plan writing by discussing writing similar to that which they are planning to write, to understand and learn from its structure, vocabulary and grammar', 'Composition', 'Planning', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-T-02', 'Draft and write by organising paragraphs around a theme', 'Composition', 'Paragraphs', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-T-03', 'In narratives, create settings, characters and plot', 'Composition', 'Narrative', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-T-04', 'In non-narrative material, use simple organisational devices (headings and sub-headings)', 'Composition', 'Non-Fiction', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-G-01', 'Express time, place and cause using conjunctions (when, before, after, while, so, because), adverbs (then, next, soon, therefore) or prepositions (before, after, during, in, because of)', 'Grammar & Punctuation', 'Conjunctions & Adverbs', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-G-02', 'Use the present perfect form of verbs instead of the simple past (e.g. He has gone out to play)', 'Grammar & Punctuation', 'Verb Tenses', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-G-03', 'Use inverted commas to punctuate direct speech', 'Grammar & Punctuation', 'Speech', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 3', 'Y3-EW-SP-01', 'Use further prefixes and suffixes and understand how to add them (e.g. un-, dis-, mis-, re-, -ful, -ly, -ment)', 'Spelling', 'Morphology', true, 8),

-- Year 4 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-T-01', 'Plan writing by discussing and recording ideas', 'Composition', 'Planning', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-T-02', 'Draft and write by composing and rehearsing sentences orally, progressively building a varied and rich vocabulary', 'Composition', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-T-03', 'Organise paragraphs around a theme, with appropriate opening and closing', 'Composition', 'Paragraphs', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-G-01', 'Use fronted adverbials (e.g. Later that day, I heard the bad news)', 'Grammar & Punctuation', 'Fronted Adverbials', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-G-02', 'Use commas after fronted adverbials', 'Grammar & Punctuation', 'Commas', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-G-03', 'Choose nouns or pronouns appropriately for clarity and cohesion and to avoid repetition', 'Grammar & Punctuation', 'Pronouns', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-G-04', 'Use and punctuate direct speech correctly (including punctuation within and around inverted commas)', 'Grammar & Punctuation', 'Speech', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 4', 'Y4-EW-SP-01', 'Spell words that are often misspelt (English Appendix 1 word list)', 'Spelling', NULL, true, 8),

-- Year 5 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-T-01', 'Plan writing by identifying the audience for and purpose of the writing, selecting the appropriate form', 'Composition', 'Planning', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-T-02', 'Draft and write by selecting appropriate grammar and vocabulary, understanding how such choices can change and enhance meaning', 'Composition', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-T-03', 'Use a wide range of devices to build cohesion within and across paragraphs (then, after that, firstly, adverbials)', 'Composition', 'Cohesion', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-G-01', 'Use relative clauses beginning with who, which, where, when, whose, that, or an omitted relative pronoun', 'Grammar & Punctuation', 'Relative Clauses', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-G-02', 'Use modal verbs (might, should, will, must) to indicate degrees of possibility', 'Grammar & Punctuation', 'Modal Verbs', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-G-03', 'Use brackets, dashes or commas to indicate parenthesis', 'Grammar & Punctuation', 'Parenthesis', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-G-04', 'Convert nouns or adjectives into verbs using suffixes (e.g. -ate, -ise, -ify)', 'Grammar & Punctuation', 'Word Classes', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 5', 'Y5-EW-SP-01', 'Use further prefixes and suffixes and understand the guidance for adding them', 'Spelling', 'Morphology', true, 8),

-- Year 6 Writing
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-T-01', 'Plan writing by identifying the audience for and purpose of the writing, selecting the appropriate form and using other similar writing as models for their own', 'Composition', 'Planning', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-T-02', 'Draft and write by selecting appropriate grammar and vocabulary, understanding how such choices can change and enhance meaning', 'Composition', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-T-03', 'Use a wide range of devices to build cohesion within and across paragraphs (repetition, adverbials, ellipsis)', 'Composition', 'Cohesion', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-01', 'Use the passive voice to affect the presentation of information in a sentence', 'Grammar & Punctuation', 'Passive Voice', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-02', 'Use the subjunctive form in very formal writing (e.g. If I were, Were they to come)', 'Grammar & Punctuation', 'Subjunctive', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-03', 'Recognise vocabulary and structures that are appropriate for formal speech and writing, including subjunctive forms', 'Grammar & Punctuation', 'Formality', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-04', 'Use the semi-colon, colon and dash to mark the boundary between independent clauses', 'Grammar & Punctuation', 'Semicolons & Colons', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-05', 'Use the colon to introduce a list and use of semi-colons within lists', 'Grammar & Punctuation', 'Lists', true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-G-06', 'Use hyphens to avoid ambiguity (e.g. man eating shark versus man-eating shark)', 'Grammar & Punctuation', 'Hyphens', true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'English Writing', 'KS2', 'Year 6', 'Y6-EW-SP-01', 'Use dictionaries to check the spelling and meaning of words', 'Spelling', NULL, true, 10),

-- ─── Science ─────────────────────────────────────────────────────────────

-- Year 1 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-PL-01', 'Identify and name a variety of common wild and garden plants, including deciduous and evergreen trees', 'Plants', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-PL-02', 'Identify and describe the basic structure of a variety of common flowering plants, including trees', 'Plants', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-AN-01', 'Identify and name a variety of common animals including fish, amphibians, reptiles, birds and mammals', 'Animals Including Humans', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-AN-02', 'Describe and compare the structure of a variety of common animals (fish, amphibians, reptiles, birds and mammals)', 'Animals Including Humans', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-AN-03', 'Identify, name, draw and label the basic parts of the human body and say which part of the body is associated with each sense', 'Animals Including Humans', 'Human Body', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-MA-01', 'Distinguish between an object and the material from which it is made', 'Everyday Materials', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-MA-02', 'Identify and name a variety of everyday materials, including wood, plastic, glass, metal, water and rock', 'Everyday Materials', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-MA-03', 'Describe the simple physical properties of a variety of everyday materials', 'Everyday Materials', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-SE-01', 'Observe changes across the four seasons', 'Seasonal Changes', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 1', 'Y1-SC-SE-02', 'Observe and describe weather associated with the seasons and how day length varies', 'Seasonal Changes', NULL, true, 10),

-- Year 2 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-LT-01', 'Explore and compare the differences between things that are living, dead, and things that have never been alive', 'Living Things & Their Habitats', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-LT-02', 'Identify that most living things live in habitats to which they are suited and describe how different habitats provide for the basic needs of different kinds of animals and plants', 'Living Things & Their Habitats', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-LT-03', 'Describe how animals obtain their food from plants and other animals, using the idea of a simple food chain', 'Living Things & Their Habitats', 'Food Chains', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-MA-01', 'Identify and compare the suitability of a variety of everyday materials for particular uses', 'Uses of Everyday Materials', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-MA-02', 'Find out how the shapes of solid objects made from some materials can be changed by squashing, bending, twisting and stretching', 'Uses of Everyday Materials', NULL, true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-AN-01', 'Notice that animals, including humans, have offspring which grow into adults', 'Animals Including Humans', 'Growth', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-AN-02', 'Find out about and describe the basic needs of animals, including humans, for survival (water, food, air)', 'Animals Including Humans', 'Health', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS1', 'Year 2', 'Y2-SC-AN-03', 'Describe the importance for humans of exercise, eating the right amounts of different types of food, and hygiene', 'Animals Including Humans', 'Health', true, 8),

-- Year 3 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-PL-01', 'Identify and describe the functions of different parts of flowering plants: roots, stem/trunk, leaves and flowers', 'Plants', NULL, true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-PL-02', 'Explore the requirements of plants for life and growth (air, light, water, nutrients, room to grow) and how they vary', 'Plants', NULL, true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-PL-03', 'Investigate the way in which water is transported within plants', 'Plants', NULL, true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-AN-01', 'Identify that animals, including humans, need the right types and amount of nutrition', 'Animals Including Humans', 'Nutrition', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-AN-02', 'Identify that humans and some other animals have skeletons and muscles for support, protection and movement', 'Animals Including Humans', 'Skeletons', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-RO-01', 'Compare and group together different kinds of rocks on the basis of their appearance and simple physical properties', 'Rocks', NULL, true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-RO-02', 'Describe in simple terms how fossils are formed when things that have lived are trapped within rock', 'Rocks', 'Fossils', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-LI-01', 'Recognise that they need light in order to see things and that dark is the absence of light', 'Light', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-LI-02', 'Recognise that shadows are formed when the light from a light source is blocked by an opaque object', 'Light', 'Shadows', true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-FM-01', 'Compare how things move on different surfaces', 'Forces & Magnets', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-FM-02', 'Notice that some forces need contact between two objects, but magnetic forces can act at a distance', 'Forces & Magnets', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 3', 'Y3-SC-FM-03', 'Describe magnets as having two poles and predict whether two magnets will attract or repel each other', 'Forces & Magnets', 'Magnets', true, 12),

-- Year 4 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-LT-01', 'Recognise that living things can be grouped in a variety of ways', 'Living Things & Their Habitats', 'Classification', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-LT-02', 'Explore and use classification keys to help group, identify and name a variety of living things in their local and wider environment', 'Living Things & Their Habitats', 'Classification', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-LT-03', 'Recognise that environments can change and that this can sometimes pose dangers to living things', 'Living Things & Their Habitats', 'Environment', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SM-01', 'Compare and group materials together, according to whether they are solids, liquids or gases', 'States of Matter', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SM-02', 'Observe that some materials change state when they are heated or cooled (e.g. water changing to ice, evaporation, condensation)', 'States of Matter', 'Changes', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SM-03', 'Identify the part played by evaporation and condensation in the water cycle', 'States of Matter', 'Water Cycle', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SO-01', 'Identify how sounds are made, associating some of them with something vibrating', 'Sound', NULL, true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SO-02', 'Find patterns between the pitch of a sound and features of the object that produced it', 'Sound', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-SO-03', 'Find patterns between the volume of a sound and the strength of the vibrations that produced it', 'Sound', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-EL-01', 'Identify common appliances that run on electricity', 'Electricity', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-EL-02', 'Construct a simple series electrical circuit, identifying and naming its basic parts', 'Electricity', 'Circuits', true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-AN-01', 'Describe the simple functions of the basic parts of the digestive system in humans', 'Animals Including Humans', 'Digestion', true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 4', 'Y4-SC-AN-02', 'Identify the different types of teeth in humans and their simple functions', 'Animals Including Humans', 'Teeth', true, 13),

-- Year 5 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-LT-01', 'Describe the differences in the life cycles of a mammal, an amphibian, an insect and a bird', 'Living Things & Their Habitats', 'Life Cycles', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-LT-02', 'Describe the life process of reproduction in some plants and animals', 'Living Things & Their Habitats', 'Reproduction', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-AN-01', 'Describe the changes as humans develop to old age', 'Animals Including Humans', 'Growth & Development', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-PM-01', 'Compare and group together everyday materials on the basis of their properties, including hardness, solubility, transparency, conductivity (electrical and thermal), and response to magnets', 'Properties of Materials', NULL, true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-PM-02', 'Know that some materials will dissolve in liquid to form a solution, and describe how to recover a substance from a solution', 'Properties of Materials', 'Dissolving', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-PM-03', 'Use knowledge of solids, liquids and gases to decide how mixtures might be separated, including through filtering, sieving and evaporating', 'Properties of Materials', 'Separating', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-PM-04', 'Demonstrate that dissolving, mixing and changes of state are reversible changes', 'Properties of Materials', 'Reversible Changes', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-ES-01', 'Describe the movement of the Earth and other planets relative to the Sun in the solar system', 'Earth & Space', NULL, true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-ES-02', 'Describe the movement of the Moon relative to the Earth', 'Earth & Space', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-ES-03', 'Use the idea of the Earth''s rotation to explain day and night and the apparent movement of the sun across the sky', 'Earth & Space', 'Day & Night', true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-FO-01', 'Explain that unsupported objects fall towards the Earth because of the force of gravity acting between the Earth and the falling object', 'Forces', 'Gravity', true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 5', 'Y5-SC-FO-02', 'Identify the effects of air resistance, water resistance and friction, that act between moving surfaces', 'Forces', 'Resistance & Friction', true, 12),

-- Year 6 Science
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-LT-01', 'Describe how living things are classified into broad groups according to common observable characteristics and based on similarities and differences', 'Living Things & Their Habitats', 'Classification', true, 1),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-LT-02', 'Give reasons for classifying plants and animals based on specific characteristics', 'Living Things & Their Habitats', 'Classification', true, 2),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-AN-01', 'Identify and name the main parts of the human circulatory system, and describe the functions of the heart, blood vessels and blood', 'Animals Including Humans', 'Circulatory System', true, 3),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-AN-02', 'Recognise the impact of diet, exercise, drugs and lifestyle on the way their bodies function', 'Animals Including Humans', 'Health', true, 4),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-AN-03', 'Describe the ways in which nutrients and water are transported within animals, including humans', 'Animals Including Humans', 'Circulatory System', true, 5),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EV-01', 'Recognise that living things have changed over time and that fossils provide information about living things that inhabited the Earth millions of years ago', 'Evolution & Inheritance', 'Fossils', true, 6),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EV-02', 'Recognise that living things produce offspring of the same kind, but normally offspring vary and are not identical to their parents', 'Evolution & Inheritance', 'Variation', true, 7),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EV-03', 'Identify how animals and plants are adapted to suit their environment in different ways and that adaptation may lead to evolution', 'Evolution & Inheritance', 'Adaptation', true, 8),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-LI-01', 'Recognise that light appears to travel in straight lines', 'Light', NULL, true, 9),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-LI-02', 'Use the idea that light travels in straight lines to explain that objects are seen because they give out or reflect light into the eye', 'Light', NULL, true, 10),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-LI-03', 'Explain that we see things because light travels from light sources to our eyes or from light sources to objects and then to our eyes', 'Light', NULL, true, 11),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EL-01', 'Associate the brightness of a lamp or the volume of a buzzer with the number and voltage of cells used in the circuit', 'Electricity', NULL, true, 12),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EL-02', 'Compare and give reasons for variations in how components function, including the brightness of bulbs, the loudness of buzzers and the on/off position of switches', 'Electricity', NULL, true, 13),
((SELECT id FROM ls_curriculum_frameworks WHERE code = 'NC2014'), 'Science', 'KS2', 'Year 6', 'Y6-SC-EL-03', 'Use recognised symbols when representing a simple circuit in a diagram', 'Electricity', 'Circuit Diagrams', true, 14)

ON CONFLICT (framework_id, objective_code) DO NOTHING;
